### ISSUE TITLE
(After upgrading to `v0.11.14`) `DowngradeParameterTypeWideningRector` still very slow

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#6490] opened 2021-06-06 03:36 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.14             |

This issue is still happening: https://github.com/rectorphp/rector/issues/6435

I'm running Rector on a set of 2000 files. With `DowngradeParameterTypeWideningRector` it takes 39 seconds. Without it, it takes 14 seconds. Check this gif:

![bug-rector-still-happening](https://user-images.githubusercontent.com/1981996/120911534-c5d1a680-c6ba-11eb-93be-ceb54c9c03c6.gif)

You can see it on my CI also: there was no improvement, the downgrade on 7400 files is still taking 19 minutes:

https://github.com/leoloso/PoP/pull/685/checks?check_run_id=2755516410

<img width="1225" alt="Screenshot 2021-06-06 at 11 33 08 AM" src="https://user-images.githubusercontent.com/1981996/120911578-147f4080-c6bb-11eb-90c8-ada3eea338ad.png">

To check the time it takes to run the script:

```bash
start_time=`date +%s` &&
vendor/bin/rector process \
--config=rector-downgrade-php72.php \
--dry-run \
--no-diffs \
src || true &&
end_time=`date +%s` &&
echo "execution time was `expr $end_time - $start_time` s." &&
vendor/bin/rector --version
```

**Comment by TomasVotruba** [comment] 2021-06-22 10:55
Closing as not a bug. Performance improvement of any rule is welcomed :+1:

**Closed by TomasVotruba** 2021-06-22 10:55 UTC
Labels: bug

**Comment by leoloso** [comment] 2021-06-22 11:36
hhhhhhm... sorry, but this rule is taking 19 min to run... how don't you call that a bug?

My code has 7000 files. Rector has less, so when downgrading it you don't see a significant increase of time. But even in your case, the increase may be 15 or 30 seconds, or maybe 1 or 2 minutes. Have you checked it out? Have you downgraded Rector without `DowngradeParameterTypeWideningRector` and then with it, as to see how much slower it got?

[Wouldn't you want to fix that (more than anyone else)?](https://tomasvotruba.com/blog/2020/01/13/why-is-first-instant-feedback-crucial-to-developers)

> some improvements were made

I didn't see any improvement at all. I know supposedly there was, but in my CI it took the same amount of time before/after the fix. I have shared the links, I can share them again if needed.

If you don't plan to fix this, I see only one solution (at least for my project): to stop using `DowngradeParameterTypeWideningRector` altogether, and create a new rule to remove all input and return types, always! (That'd be a horrible solution)
