### ISSUE TITLE
Again PHP Fatal Error: Cannot redeclare Functional\*

### ISSUE THREAD

**Issue by thomasvargiu** [rectorphp/rector#7146] opened 2022-05-02 10:27 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `0.12.23`            |

Same problem of #3383.

**Comment by TomasVotruba** [comment] 2022-05-02 11:56
We'll need a reproducable repository.

**Comment by samsonasik** [comment] 2022-05-02 22:08
I can't reproduce in latest dev-main, feel free to provide sample reproduced repository for it. Thank you.

**Comment by samsonasik** [comment] 2022-05-11 14:58
I am closing it, we can't provide a solution for issue that not reproducible. Feel free to provide a sample repository when you have a chance.

**Closed by samsonasik** 2022-05-11 14:58 UTC
Labels: bug
