### ISSUE TITLE
Formatting bug for Symfony Constraints

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#3645] opened 2020-07-03 16:06 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@0a8bef3             |
| Installed as   | docker latest image                      |

```diff
 <?php

 use Symfony\Component\Validator\Constraints as Assert;

 class User
 {
     /**
-     * @Assert\Email(message = "email.email")
+     * @Assert\Email(message=email.email)
      */
     private $email;
 }
```

## Expected Behaviour

Rector should not touch it.

SF 4.4 application. My rector.yaml:
```yaml
services:
    Rector\Php74\Rector\Property\TypedPropertyRector:
    Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector:

parameters:
    auto_import_names: true
    import_short_classes: false
    autoload_paths:
        - /project/config/bootstrap.php 
```
Can't run demo, getting ` Function 'mail()' is not allowed.`.
![Screenshot at 2020-07-03 18-09-59](https://user-images.githubusercontent.com/25783196/86485218-78391500-bd58-11ea-8702-9587b34b7623.png)

**Comment by TomasVotruba** [comment] 2020-07-03 16:11
> Can't run demo, getting Function 'mail()' is not allowed.

The code needs to be complete. Include it to the analysed code:

```php
function mail() {}
```

**Comment by javaDeveloperKid** [comment] 2020-07-03 16:15
Getting `Fix PHP syntax` wherever I put this function (inside class, outside class).

**Comment by TomasVotruba** [comment] 2020-07-03 16:24
Could you share the link to demo?

**Comment by javaDeveloperKid** [comment] 2020-07-03 16:33
I can't. It's still /demo when I press **Process**. Form is filled as in the picture above.

**Comment by TomasVotruba** [comment] 2020-07-03 17:34
I see.

**Comment by TomasVotruba** [comment] 2020-07-03 17:43
As for annotation formatting, there is often nothing we can do, as there is no tool to preserve format.

If the behavior doesn't change, we close it as won't fix.

**Comment by javaDeveloperKid** [comment] 2020-07-03 18:37
Actually NotNull cannot be used as $email should be validated with @Email. I wonder why rector even touches this line (especially with this configuration). 
This will happen only with @Email annotation or there are plenty of others annotations that will couse this buggy formatting?

**Comment by sstok** [comment] 2020-07-04 08:54
Had something similar.

```
2) src/UI/Web/Action/Security/ConfirmPasswordResetAction.php    
---------- begin diff ----------
--- Original
+++ New
@@ -23,9 +23,9 @@
      * @Route(
      *     path="/password-reset/confirm/{token}",
      *     name="park_manager.security_confirm_password_reset",
-     *     requirements={"token": ".+"},
-     *     methods={"GET", "POST"}
-     * )
+     *     requirements={"token"=".+"}, methods={"GET",
+     *     "POST"} )
+     *
      *
      * @return RouteRedirectResponse|TwigResponse
      */
    ----------- end diff -----------
```

https://getrector.org/demo/27dfaf50-93ae-4eb2-9f8a-4fc2d4d50f11

**Comment by TomasVotruba** [comment] 2020-07-04 10:03
> Actually NotNull cannot be used as $email 

It can. It's not relevant for this example. It is basically "any annotation class".

> Can I skip this line with @Email somehow?

The solution is to correct formatting in whole project. Anything else will disable Rector rules.

**Comment by TomasVotruba** [comment] 2020-12-05 00:30
Related to and duplicate of #4334

**Closed by TomasVotruba** 2020-12-05 00:30 UTC
Labels: bug, format-preserving-phpdoc-printer
