### ISSUE TITLE
TernaryToBooleanOrFalseToBooleanAndRector bug

### ISSUE THREAD

**Issue by escopecz** [rectorphp/rector#2765] opened 2020-01-26 16:40 UTC
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | Rector v0.6.13                   |
| PHP version    | PHP 7.2                                        |
| Full Command   | bin/rector process --config rector.yaml           | 
| Demo link      | https://getrector.org/demo/cf547aa3-85e8-4029-a442-157b5bdec92e  | 
| rector.yaml    | below             | 

rector.yaml:
```yml
services:
    Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector:
    Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector:
    Rector\DeadCode\Rector\Ternary\TernaryToBooleanOrFalseToBooleanAndRector:

parameters:
    paths:
        - app/bundles

    exclude_paths:
        - '*/tests/*'
        - '*/Tests/*'
        - '*/Test/*'
        - '*/test/*'
        - '*/InstallFixtures/*'
        - '*/Fixtures/*'
        - '*.html.php'

```

## Minimal PHP Code Causing Issue

  

```php
<?php declare(strict_types=1);

final class DemoFile
{
    public function run(string $status)
    {
        return ('published' === $status) ? true : false;
    }
}
```

## Expected Behaviour
I'd expect something like
```php
// Original line that can be simplified:
return ('published' === $status) ? true : false;

// Rector changed it to:
return 'published' === $status && true;

// I'd expect:
return 'published' === $status;
```

**Comment by TomasVotruba** [comment] 2020-01-26 16:43
That looks like a space for new rule. 

Care to make it?

**Comment by escopecz** [comment] 2020-01-26 16:50
I can try. But don't know where to start. Is there some similar rule I can look as an inspiration? I'm looking at https://github.com/rectorphp/rector/blob/master/packages/DeadCode/src/Rector/Ternary/TernaryToBooleanOrFalseToBooleanAndRector.php but it did not click for me.

**Comment by TomasVotruba** [comment] 2020-01-26 16:55
Might be  this one https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#simplifyduplicatedternaryrector

**Comment by TomasVotruba** [comment] 2020-02-01 08:06
Closing as not a bug and feature is welcomed.

**Closed by TomasVotruba** 2020-02-01 08:06 UTC
