### ISSUE TITLE
"Carbon\Traits\Localization" could not be found in the located source

### ISSUE THREAD

**Issue by HDVinnie** [rectorphp/rector#4582] opened 2020-11-11 19:45 UTC
# Bug Report
Rector 0.8.49
Config file: rector.php

```
 [ERROR] Could not process "app/Models/User.php" file, due to:                                                          
         "_HumbugBoxb854c950819b\Roave\BetterReflection\Reflection\ReflectionClass "Carbon\Traits\Localization" could   
         not be found in the located source".
```

## Minimal PHP Code Causing Issue

I have not been able to track it down 100% but it seems this error occurs on all files that have a `use Carbon\Carbon;` inport and `$current = Carbon::now();` var.

**Comment by ronnylt** [comment] 2020-11-12 06:59
Same here. 

This error occurs on  files that have a use `Carbon\Carbon`.

Stack trace:

`
PHP Fatal error:  Uncaught _HumbugBoxb854c950819b\Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: _HumbugBoxb854c950819b\Roave\BetterReflection\Reflection\ReflectionClass "Carbon\Traits\Localization" could not be found in the located source in phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): _HumbugBoxb854c950819b\Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(_HumbugBoxb854c950819b\Roave\BetterReflection\Identifier\Identifier))
#1 phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): _HumbugBoxb854c950819b\Roave\BetterReflection\Reflector\ClassReflector->reflect('Carbon\\Traits\\L...')
#2 phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/ in phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 24
Fatal error: Uncaught _HumbugBoxb854c950819b\Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: _HumbugBoxb854c950819b\Roave\BetterReflection\Reflection\ReflectionClass "Carbon\Traits\Localization" could not be found in the located source in phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): _HumbugBoxb854c950819b\Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(_HumbugBoxb854c950819b\Roave\BetterReflection\Identifier\Identifier))
#1 phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): _HumbugBoxb854c950819b\Roave\BetterReflection\Reflector\ClassReflector->reflect('Carbon\\Traits\\L...')
#2 phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/ in phar:///opt/xxxxxx/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 24
`

**Comment by TomasVotruba** [comment] 2020-11-12 10:26
Duplicate of https://github.com/rectorphp/rector/issues/4406

**Closed by TomasVotruba** 2020-11-12 10:26 UTC
