### ISSUE TITLE
phpdoc duplication with PropertyTypeDeclarationRector

### ISSUE THREAD

**Issue by orklah** [rectorphp/rector#3541] opened 2020-06-17 18:55 UTC
# Bug Report

Rector seems to duplicate phpdoc in front of a similar one with PropertyTypeDeclarationRector

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f15d5eca-ead5-4385-a2cf-f9743f547280

## Expected Behaviour

Nothing changing in the given example

**Comment by TomasVotruba** [comment] 2020-08-31 20:52
Updated Demo link in PHP config: https://getrector.org/demo/cb8a0637-0f3f-49ff-a486-6937c6c79aa2#result

The problem is SAFE_TYPES. With `false` value it works

**Comment by TomasVotruba** [comment] 2020-09-03 17:16
Thanks for adresing this. With current implementation, I feel this causes more harm than value.
As we depend on PHPStan in ~90 % cases of type resolving, this cannot be resolved for `/vendor`, thus causing random bugs/useless.

I think it might be better to simply remove safe_types feature, as it doesn't bring any value at the moment. What do you think?

**Comment by orklah** [comment] 2020-09-03 17:20
I think so too. A partial implementation for a safety feature supposed to be absolute is the same as no implementation at all.

Let's see how phpstan evolve, it may become relevant once again in the future

**Comment by TomasVotruba** [comment] 2020-09-03 17:50
Allrgith, thank you for your feedback and patience with this. I'm going to revert it now to prevent any more confusion.

**Closed** 2020-09-03 18:02 UTC
Labels: bug
