### ISSUE TITLE
`Could not process` after update to 0.6.14

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2837] opened 2020-02-10 23:32 UTC
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | e.g. v0.6.14 (invoke `vendor/bin/rector --version`)                   |
| PHP version    | e.g. PHP 7.4.2 (invoke `php -v`)                                        |

## Current Behaviour 

After update from 0.6.13 to 0.6.14 I get a lot of errors like:
```
 [ERROR] Could not process                                                      
         "/var/www/module/ProductRelations/src/Implementation/MockRelatedProduct
         sQuery.php" file, due to:                                              
         "Class '_HumbugBoxebb6c51d1e3e\JetBrains\PHPStormStub\PhpStormStubsMap'
         not found".
```

I use prefixed version.

**Comment by snapshotpl** [comment] 2020-02-10 23:37
There's also:
```
 [ERROR] Could not process                                                      
         "/var/www/module/Przelewy24/src/Domain/Transaction.php" file, due to:  
         "Argument 1 passed to                                                  
         Rector\PhpParser\Node\Manipulator\ClassManipulator::getProperty() must 
         be an instance of PhpParser\Node\Stmt\ClassLike, null given, called in 
         phar:///var/www/vendor/rector/rector-prefixed/rector/packages/CodeQuali
         ty/src/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector.php  
         on line 149".
```

**Comment by snapshotpl** [comment] 2020-02-11 09:19
Looks like first error appear when I have method with `iterable` as return type:
```php
public function getItems(): iterable {
  return $this->items;
}
```

**Comment by TomasVotruba** [comment] 2020-02-11 10:51
Duplicate of https://github.com/rectorphp/rector/issues/2749

We're now waiting for new relase of PHPStan, where it should be fixed

**Closed by TomasVotruba** 2020-02-11 10:51 UTC

**Comment by snapshotpl** [comment] 2020-02-11 10:53
@TomasVotruba thanks!
