### ISSUE TITLE
Rector hangs with no output whatsoever

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#7586] opened 2022-11-10 13:12 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.7 |

Running `rector process` gives absolutely no output whatsoever. A breakpoint shows it gets to [here](https://github.com/composer/xdebug-handler/blob/ced299686f41dce890debac69273b47ffe98a40c/src/XdebugHandler.php#L300) and then freezes. It seems to be some problematic interaction with Xdebug. However, even if I run `rector/rector/bin/rector` directly, to get rid of the Composer wrapper, the issue persists. It seems the XdebugHandler always gets called anyway, no matter what I do.

**Comment by samsonasik** [comment] 2022-11-10 13:17
is increasing timeout seconds help?

```php
$rectorConfig->parallel(240);
```

or is disable parallel make it working?

```php
$rectorConfig->disableParallel();
```

**Comment by Bilge** [comment] 2022-11-10 13:46
After waiting about 10 minutes, it finally printed the progress bar, but it's just stuck on 0%. It is simply too slow to ever be usable in practice.

**Comment by Bilge** [comment] 2022-11-10 14:38
It is working now with `$rectorConfig->disableParallel();`, but a lot slower than I remember in the past. It takes about 3 minutes per run with a small configuration. It completely blows up all memory and dies without disabling parallel, though, even with 16GB allocation available.

**Comment by Bilge** [comment] 2022-11-10 14:41
It is working now with `$rectorConfig->disableParallel();`, but a lot slower than I remember in the past. It takes about 3 minutes per run with a small configuration. Most of the time it just sits there not outputting anything, though, which is not a good user experience.

It completely blows up all memory and dies without disabling parallel, though, even with 16GB allocation available.

Running with `--debug` prints `frontend/src/Kernel.php` after waiting about 60 seconds, then it hangs again for about another 60 seconds, before finally spamming the console with all the files it's processing.

**Comment by Wohlie** [comment] 2022-11-11 10:05
I have the same problem since today. Yesterday my CI pipeline runs without any issue (took ~5 min) and today it gets killed after ~13 min, without any code changed.

```
   20/1897 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   1%
  160/1897 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   8%
  200/1897 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
  320/1897 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  16%
  480/1897 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  25%
  540/1897 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  28%
  580/1897 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%
  680/1897 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  35%
  760/1897 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%
  900/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  47%
  960/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
 1020/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  53%
 1080/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  56%
 1120/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  59%
 1200/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  63%
 1280/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  67%
 1340/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  70%
 1420/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░]  74%
 1460/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  76%
 1480/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  78%
 1520/1897 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80%
 [ERROR] Could not process                                                      
         "/rector/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueOb
         ject/ParallelProcess.php" file, due to:                                
         "Child process timed out after 120 seconds". On line: 103              
 [ERROR] Could not process some files, due to:                                  
         "Reached system errors count limit of 50, exiting...".   
```

The composer dependencies changes today to the following:
```patch
Index: .config/JetBrains/PhpStorm2022.2/scratches/scratch_61.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.config/JetBrains/PhpStorm2022.2/scratches/scratch_61.txt b/.config/JetBrains/PhpStorm2022.2/scratches/scratch_61.txt
--- a/.config/JetBrains/PhpStorm2022.2/scratches/scratch_61.txt	
+++ b/.config/JetBrains/PhpStorm2022.2/scratches/scratch_61.txt	(date 1668160500156)
@@ -14,7 +14,7 @@
   - Locking phpdocumentor/reflection-common (2.2.0)
   - Locking phpdocumentor/reflection-docblock (5.3.0)
   - Locking phpdocumentor/type-resolver (1.6.1)
-  - Locking phpstan/phpstan (1.9.1)
+  - Locking phpstan/phpstan (1.9.2)
   - Locking phpstan/phpstan-phpunit (1.2.2)
   - Locking phpstan/phpstan-webmozart-assert (1.2.2)
   - Locking phpunit/php-code-coverage (9.2.18)
@@ -45,15 +45,15 @@
   - Locking sebastian/version (3.0.2)
   - Locking symfony/console (v5.4.15)
   - Locking symfony/deprecation-contracts (v2.5.2)
-  - Locking symfony/polyfill-ctype (v1.26.0)
-  - Locking symfony/polyfill-intl-grapheme (v1.26.0)
-  - Locking symfony/polyfill-intl-normalizer (v1.26.0)
-  - Locking symfony/polyfill-mbstring (v1.26.0)
-  - Locking symfony/polyfill-php73 (v1.26.0)
-  - Locking symfony/polyfill-php80 (v1.26.0)
+  - Locking symfony/polyfill-ctype (v1.27.0)
+  - Locking symfony/polyfill-intl-grapheme (v1.27.0)
+  - Locking symfony/polyfill-intl-normalizer (v1.27.0)
+  - Locking symfony/polyfill-mbstring (v1.27.0)
+  - Locking symfony/polyfill-php73 (v1.27.0)
+  - Locking symfony/polyfill-php80 (v1.27.0)
   - Locking symfony/service-contracts (v2.5.2)
   - Locking symfony/string (v5.4.15)
   - Locking theseer/tokenizer (1.2.1)
   - Locking tysonandre/var_representation_polyfill (0.1.3)
   - Locking webmozart/assert (1.11.0)
```

Maybe the PHPStan update is the root of the problem?

**Comment by Bilge** [comment] 2022-11-11 10:28
Easiest way to check is to lock phpstan to that previous version.

**Comment by samsonasik** [comment] 2022-11-11 10:39
It probably caused by PHPStan if it slow down after update PHPStan.

By the way, I created 3 PRs to improve performance on Rector side: 

- https://github.com/rectorphp/rector-src/pull/3043
- https://github.com/rectorphp/rector-src/pull/3043
- https://github.com/rectorphp/rector-src/pull/3047

**Comment by Bilge** [comment] 2022-11-11 10:41
@samsonasik The first two links are the same.

**Comment by samsonasik** [comment] 2022-11-11 10:44
@Bilge updated 👍

**Comment by Bilge** [comment] 2022-11-11 10:51
I derive no performance benefit from downgrading PHPStan 1.9.2 => 1.9.1.

**Comment by Wohlie** [comment] 2022-11-11 11:53
I also perform a test run with PHPStan 1.9.1, and also can't measure any difference. So my problem is maybe not related to Rector/PHPStan.
Sorry :/

**Comment by samsonasik** [comment] 2022-11-14 16:58
Rector 0.14.8 released with various performance improvement https://github.com/rectorphp/rector/releases/tag/0.14.8

If you have very huge codebase, you may still need to tweak configuration and/or extract per-directory run like at https://github.com/rectorphp/rector/issues/7600#issuecomment-1312539617

**Comment by Bilge** [comment] 2022-11-16 17:57
$ `rector process --config=config/rector.php --clear-cache frontend/src '--dry-run'`

### 0.14.7
| Local 1 | Local 2 | CI |
|-|-|-|
| real    4m13.136s | real    4m0.968s | real    0m51.900s |

### 0.14.8
| Local 1 | Local 2 | CI |
|-|-|-|
| real    3m37.081s | real    4m1.282s | real    0m51.620s |

There seems to be no difference for me.

**Comment by samsonasik** [comment] 2022-12-15 12:06
I am closing it as there are already various performance improvement, crash handling, and infinite loop handling in recent releases.

Feel free to provide another performance improvement PR when you can :)

**Closed by samsonasik** 2022-12-15 12:06 UTC
Labels: bug
