### ISSUE TITLE
Class PHPUnit\Framework\TestCase not found

### ISSUE THREAD

**Issue by Knallcharge** [rectorphp/rector#6531] opened 2021-06-28 06:03 UTC
# Question
I've been using rector for a couple of months now and starting last week I get loads of errors "[ERROR] Analyze error: "Class PHPUnit\Framework\TestCase not found."." when including my tests-directory in rector.php-file (which was included before the errors started) without changing my config.

I'm using rector 0.11.27 with PHP 7.4.20 and symfony 5.3.2 (with phpunit-bridge).

I start rector using: `vendor\bin\rector process -c build\rector.php --dry-run`

My rector.php file includes my src- as well as my test-folder like this
`$parameters->set(Option::PATHS, [__DIR__ . '/../src', __DIR__ . '/../tests']);`

As the error states "Include your files in "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config." I added this to my config (this wasn't necessary until now):
`$parameters->set(Option::AUTOLOAD_PATHS, [__DIR__ . '/../vendor/bin/.phpunit/phpunit/src/Framework']);`
as well as trying other paths (going down as far as including "../vendor", which will take several minutes indexing before even starting the analysis), but the error remains.

How can I make rector work again also for my tests-directory?

**Comment by TomasVotruba** [comment] 2021-06-28 10:42
Hi, there could be a number of reason causing this.
Could you create a reproducible repository on Github with failing CI? We'll be able to fix it then

**Comment by Knallcharge** [comment] 2021-06-29 13:11
I switched to the native phpunit-library today as using symfony's phpunit-bridge was too much of a hassle for several other reasons. Now the errors disappeared and I see rector-suggestions for my test-files for the first time ever.

I'll leave this open as there are probably still people using phpunit-bridge that run into this issue, but for me it's solved.

**Comment by TomasVotruba** [comment] 2021-06-29 17:04
Congrats! We use PHPUnit this way everywhere and since then we never had the version miss-match bug. Seeing new major PHPUnit version every year this is every important.

That's a good enough solution :+1: 

--

I think we would have to fake the TestCase class anyway. We'll need a reproducible repository to be able to fix it.  Closing as there reproducible repository is missing.

**Closed by TomasVotruba** 2021-06-29 17:04 UTC
