### ISSUE TITLE
Cannot get Rector to work

### ISSUE THREAD

**Issue by CZechBoY** [rectorphp/rector#307] opened 2018-02-03 10:10 UTC
Hi,
I am trying Rector for the first time.

My environment
------------------
`composer-plugin-bin` installed globally
app project runs on old php 5 - that means i have old libraries that Rector uses as well
app is in nette 2.3 and i am trying to dry-run nette 2.4 checks

rector is installed in `/vendor-bin/rector`
application source is located in `/web/App`
application libraries are located in `/web/vendor/`

I have tried
------------
1)
command: `\web\vendor\bin>rector.bat process ../../App --level nette24 --dry-run`
output:
```
In ProcessCommand.php line 172:

  [Rector\Exception\Command\FileProcessingException]
  Processing of "../../App\Components\SomeControl\SomeControl.php" file failed.


Exception trace:
 Rector\Console\Command\ProcessCommand->processFiles() at \vendor-bin\rector\vendor\rector\rector\src\Console\Command\ProcessCommand.php:137
 Rector\Console\Command\ProcessCommand->execute() at \vendor-bin\rector\vendor\symfony\console\Command\Command.php:252
 Symfony\Component\Console\Command\Command->run() at \vendor-bin\rector\vendor\symfony\console\Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at \vendor-bin\rector\vendor\symfony\console\Application.php:241
 Symfony\Component\Console\Application->doRun() at \vendor-bin\rector\vendor\symfony\console\Application.php:143
 Symfony\Component\Console\Application->run() at \vendor-bin\rector\vendor\rector\rector\bin\rector:44

In IdentifierNotFound.php line 33:

  [Rector\BetterReflection\Reflector\Exception\IdentifierNotFound]
  Rector\BetterReflection\Reflection\ReflectionClass "Nette\Application\UI\Control" could not be found in the located source

```

2) with custom autoloader
custom autoloader code:
```php
<?php
require_once __DIR__ . '/autoload.php';

(new \Nette\Loaders\RobotLoader())
    ->addDirectory(__DIR__ . '/../App')
    ->setCacheStorage(new \Nette\Caching\Storages\DevNullStorage())
    ->register();
```
command: `\web\vendor\bin>rector.bat process ../../App --autoload-file ../rector_autoload.php --level nette24 --dry-run`
output:
```
0/1057 [>---------------------------]   0% < 1 secPHP Warning:  file_get_contents(\web\vendor/../App): failed to open stream: Permission denied in \vendor-bin\rector\vendor\rector\b
etter-reflection\src\SourceLocator\Type\AutoloadSourceLocator.php on line 66

Warning: file_get_contents(\web\vendor/../App): failed to open stream: Permission denied in \vendor-bin\rector\vendor\rector\better-reflection\src\SourceLocator\Type\AutoloadSourceLocat
or.php on line 66


In ProcessCommand.php line 172:

  [Rector\Exception\Command\FileProcessingException]
  Processing of "../../App\Components\OtherControl\OtherControl.php" file failed.
```

3) composer autoloader
command: `\web\vendor\bin>rector.bat process ../../App --autoload-file ../autoload.php --level nette24 --dry-run`
output:
```
0/1057 [>---------------------------]   0% < 1 secPHP Notice:  Undefined index: App\Components\ComponentAbcdef\ComponentAbcdef in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplac
erRector.php on line 154

Notice: Undefined index: App\PrivateModule\Components\ResourceManager\ResourceManager in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplacerRector.php on line 154
PHP Notice:  Undefined index: Nette\ComponentModel\IComponent in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplacerRector.php on line 154

Notice: Undefined index: Nette\ComponentModel\IComponent in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplacerRector.php on line 154
PHP Notice:  Undefined index: Nette\ComponentModel\IContainer in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplacerRector.php on line 154

Notice: Undefined index: Nette\ComponentModel\IContainer in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplacerRector.php on line 154
PHP Notice:  Undefined index: Nette\Application\UI\ISignalReceiver in \vendor-bin\rector\vendor\rector\rector\src\Rector\Dynamic\MethodNameReplacerRector.php on line 154
```

Thanks for help!

**Comment by TomasVotruba** [comment] 2018-02-03 12:37
Hey, could you try exactly [this approach in README](https://github.com/rectorphp/rector#do-you-have-conflicts)? It solved similar issues before.

Any non-standard Rector placement breaks autoloading for it or for BetterReflection.

**Comment by CZechBoY** [comment] 2018-02-03 12:59
That is exactly what i am looking at. What is different in my calls?

**Comment by TomasVotruba** [comment] 2018-02-03 13:08
Right in the beggining I see:

> rector is installed in /vendor-bin/rector

**Comment by CZechBoY** [comment] 2018-02-03 16:52
After maybe 10-15 minutes of running I got same errors.

**Comment by carusogabriel** [comment] 2018-02-04 07:28
@CZechBoY Performances improvements are being discussing in #273

**Comment by CZechBoY** [comment] 2018-02-04 11:00
@carusogabriel  I am not here for performance issues. I am here for "not working" or "i don not know how to run" issues.

**Comment by TomasVotruba** [comment] 2018-02-08 15:32
@CZechBoY Could you reply to these? https://github.com/rectorphp/rector/issues/307#issuecomment-362804842

**Comment by CZechBoY** [comment] 2018-02-08 20:23
@TomasVotruba What more info do you need?

input command:
`\web>"vendor/bin/rector.bat" process App --level nette24 --dry-run`

full output:
```
16 Loaded Rectors
=================

 - Rector\Rector\Contrib\Nette\Utils\NetteObjectToSmartTraitRector
 - Rector\Rector\Contrib\Nette\Utils\MagicMethodRector
 - Rector\Rector\Contrib\Nette\Application\ValidateControlRector
 - Rector\Rector\Contrib\Nette\Application\TemplateMagicInvokeFilterCallRector
 - Rector\Rector\Contrib\Nette\Application\TemplateRegisterHelperRector
 - Rector\Rector\Contrib\Nette\DI\SetEntityToStatementRector
 - Rector\Rector\Contrib\Nette\DI\ExpandFunctionToParametersArrayRector
 - Rector\Rector\Contrib\Nette\DI\ExpandFunctionToStaticExpandFunctionRector
 - Rector\Rector\Contrib\Nette\DI\CompilerCompileArgumentsRector
 - Rector\Rector\Contrib\Nette\DI\CompilerGenerateCodeArgumentsRector
 - Rector\Rector\Contrib\Nette\Forms\ChoiceDefaultValueRector
 - Rector\Rector\Contrib\Nette\Forms\FormNegativeRulesRector
 - Rector\Rector\Contrib\Nette\Forms\FormCallbackRector
 - Rector\Rector\MagicDisclosure\GetAndSetToMethodCallRector
 - Rector\Rector\MagicDisclosure\UnsetAndIssetToMethodCallRector
 - Rector\Rector\Dynamic\MethodNameReplacerRector

Processing 1057 files
=====================

    0/1057 [>---------------------------]   0% < 1 sec

In ProcessCommand.php line 172:

  [Rector\Exception\Command\FileProcessingException]
  Processing of "App\Components\SomeControl\SomeControl.php" file failed.


Exception trace:
 Rector\Console\Command\ProcessCommand->processFiles() at \vendor-bin\rector\vendor\rector\rector\src\Console\Command\ProcessCommand.php:137
 Rector\Console\Command\ProcessCommand->execute() at \vendor-bin\rector\vendor\symfony\console\Command\Command.php:252
 Symfony\Component\Console\Command\Command->run() at \vendor-bin\rector\vendor\symfony\console\Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at \vendor-bin\rector\vendor\symfony\console\Application.php:241
 Symfony\Component\Console\Application->doRun() at \vendor-bin\rector\vendor\symfony\console\Application.php:143
 Symfony\Component\Console\Application->run() at \vendor-bin\rector\vendor\rector\rector\bin\rector:44

In IdentifierNotFound.php line 33:

  [Rector\BetterReflection\Reflector\Exception\IdentifierNotFound]
  Rector\BetterReflection\Reflection\ReflectionClass "Nette\Application\UI\Control" could not be found in the located source


Exception trace:
 Rector\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier() at \vendor-bin\rector\vendor\rector\better-reflection\src\Reflector\ClassReflector.php:40
 Rector\BetterReflection\Reflector\ClassReflector->reflect() at \vendor-bin\rector\vendor\rector\better-reflection\src\Reflection\ReflectionClass.php:807
 Rector\BetterReflection\Reflection\ReflectionClass->getParentClass() at \vendor-bin\rector\vendor\rector\better-reflection\src\Reflection\ReflectionClass.php:1216
 Rector\BetterReflection\Reflection\ReflectionClass->getInheritanceClassHierarchy() at \vendor-bin\rector\vendor\rector\better-reflection\src\Reflection\ReflectionClass.php:1219
 Rector\BetterReflection\Reflection\ReflectionClass->getInheritanceClassHierarchy() at \vendor-bin\rector\vendor\rector\better-reflection\src\Reflection\ReflectionClass.php:825
 Rector\BetterReflection\Reflection\ReflectionClass->getParentClassNames() at \vendor-bin\rector\vendor\rector\rector\packages\NodeTypeResolver\src\PerNodeTypeResolver\PropertyTypeResolver.php:97
 Rector\NodeTypeResolver\PerNodeTypeResolver\PropertyTypeResolver->addParentClasses() at \vendor-bin\rector\vendor\rector\rector\packages\NodeTypeResolver\src\PerNodeTypeResolver\PropertyTypeResolver.php:81
 Rector\NodeTypeResolver\PerNodeTypeResolver\PropertyTypeResolver->resolve() at \vendor-bin\rector\vendor\rector\rector\packages\NodeTypeResolver\src\NodeTypeResolver.php:38
 Rector\NodeTypeResolver\NodeTypeResolver->resolve() at \vendor-bin\rector\vendor\rector\rector\packages\NodeTypeResolver\src\NodeVisitor\TypeNodeVisitor.php:23
 Rector\NodeTypeResolver\NodeVisitor\TypeNodeVisitor->enterNode() at \vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:179
 PhpParser\NodeTraverser->traverseArray() at \vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:108
 PhpParser\NodeTraverser->traverseNode() at \vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:197
 PhpParser\NodeTraverser->traverseArray() at \vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:108
 PhpParser\NodeTraverser->traverseNode() at \vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:197
 PhpParser\NodeTraverser->traverseArray() at \vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:85
 PhpParser\NodeTraverser->traverse() at \vendor-bin\rector\vendor\rector\rector\src\NodeTraverser\StandaloneTraverseNodeTraverser.php:46
 Rector\NodeTraverser\StandaloneTraverseNodeTraverser->traverse() at \vendor-bin\rector\vendor\rector\rector\packages\NodeTraverserQueue\src\NodeTraverserQueue.php:56
 Rector\NodeTraverserQueue\NodeTraverserQueue->processFileInfo() at \vendor-bin\rector\vendor\rector\rector\src\Application\FileProcessor.php:59
 Rector\Application\FileProcessor->processFileToString() at \vendor-bin\rector\vendor\rector\rector\src\Console\Command\ProcessCommand.php:190
 Rector\Console\Command\ProcessCommand->processFile() at \vendor-bin\rector\vendor\rector\rector\src\Console\Command\ProcessCommand.php:169
 Rector\Console\Command\ProcessCommand->processFiles() at \vendor-bin\rector\vendor\rector\rector\src\Console\Command\ProcessCommand.php:137
 Rector\Console\Command\ProcessCommand->execute() at \vendor-bin\rector\vendor\symfony\console\Command\Command.php:252
 Symfony\Component\Console\Command\Command->run() at \vendor-bin\rector\vendor\symfony\console\Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at \vendor-bin\rector\vendor\symfony\console\Application.php:241
 Symfony\Component\Console\Application->doRun() at \vendor-bin\rector\vendor\symfony\console\Application.php:143
 Symfony\Component\Console\Application->run() at \vendor-bin\rector\vendor\rector\rector\bin\rector:44

process [--dry-run] [--autoload-file AUTOLOAD-FILE] [--] <source> (<source>)...
```

**Comment by TomasVotruba** [comment] 2018-02-08 21:13
Thanks, I didn't see the command you've run.

Last question: where is "Nette\Application\UI\Control" located?

**Comment by CZechBoY** [comment] 2018-02-08 22:10
somewhere in `web/vendor/nette/`...

**Comment by TomasVotruba** [comment] 2018-02-08 22:39
Alright, that should work, I'll try to simulate the use case.

Just in case this is somehow related only to Windows, could you confirm that on some *nix system?

**Comment by TomasVotruba** [comment] 2018-02-14 17:04
Closing as duplicate of #303

**Comment by CZechBoY** [comment] 2018-02-14 22:15
Same errors on Debian with php7.1.

**Comment by CZechBoY** [comment] 2018-02-14 22:35
btw I got some error about class not found for this case:
```php
namespace AAA;
class BBB
{
    /**
      * @see Oracle http://def.gh
      */
    public function ccc() {}
}
```

**Comment by CZechBoY** [comment] 2018-02-15 10:17
And other with custom garbage in phpdoc
```
  [InvalidArgumentException]
  "\App\AfsModule\Components\EntityHistory\array[string" is not a valid Fqsen.
```
for code
```php
/**
     * @var array[string month => int times]
     */
    private $monthTimes = [];
```

**Comment by CZechBoY** [comment] 2018-02-15 10:37
or callable with additional info
```
[InvalidArgumentException]
  "\App\IpMap\callable[];" is not a valid Fqsen.

```
for code:
```php
    /**
     * @var callable[]; function (IpMap $map)
     */
    public $onDataRequest = [];
```

**Comment by TomasVotruba** [comment] 2018-03-06 15:14
Closing as original issue is resolved and does not show other unrelated issues

**Closed by TomasVotruba** 2018-03-06 15:14 UTC
Labels: Bug, PHAR

**Comment by TomasVotruba** [comment] 2018-03-06 15:16
Follow up in https://github.com/rectorphp/rector/issues/345
