### ISSUE TITLE
Dead code varibale detection do not work in if statement

### ISSUE THREAD

**Issue by rogoit** [rectorphp/rector#6847] opened 2021-12-05 20:43 UTC
# Bug Report

version 0.11.60

I want to detect a unused variable. It is a if statement for a special case.

## Minimal PHP Code Causing Issue

The use case is here 

https://github.com/nevercodealone/waterpolo/blob/d2c3d8fed66a3d8a5f7e3e12b3ac6bb436dcc667/src/Service/GrabberService.php#L53

If i add a new arraz on line 44 the dead code detection work fine. When i run it now nothing is found.

## Expected Behaviour

The $news var should be removed and detected

I like to help you with this issue my friend. maybe you can tell me how to start.

See you
Roland

**Comment by TomasVotruba** [comment] 2021-12-05 21:03
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by rogoit** [comment] 2021-12-05 21:21
Ok, I now cut the video about this. Hope I can do later. Thx for your passion!!

**Comment by rogoit** [comment] 2021-12-05 22:12
Like this? https://getrector.org/demo/1ec56185-9861-6932-9a22-3b2c671121dd

**Comment by TomasVotruba** [comment] 2021-12-06 05:47
Thanks! Could you narrow it to minimal code so we can easily see the required code that cashed the bug? 
Should be around 3-5 lines.

**Comment by rogoit** [comment] 2021-12-06 08:29
So now its easier. The first $news var in if statement. Is ok?

https://getrector.org/demo/1ec566e6-e7dc-6bfe-8053-3d3b3b6c1ead

**Comment by TomasVotruba** [comment] 2021-12-06 08:31
Should be 3-5 lines, as the other code is not needed to reproduce the code. It makes fixing bug and maintaing regression easier, e.g.:

```php
 if ('key' === $sourceDomain) {
       $news = [];
  } else {
  }
````

**Comment by rogoit** [comment] 2021-12-06 08:51
So maybe now. The thing is that you need the foreach and if statement combination. Could also be that in this case also the $allNews has to be detected.

https://getrector.org/demo/1ec56716-b9b2-6f6e-ae96-c5c9f771fdfe

**Comment by TomasVotruba** [comment] 2021-12-06 10:33
That's the one! Thanks 👍

**Comment by TomasVotruba** [comment] 2021-12-06 10:33
Could you send a failing test case in a pull-request, so we have it covered in Rector?
You can click "Create a Test" button at demo page.

**Comment by rogoit** [comment] 2021-12-07 10:49
I do not get. I do not know how to do things in rector. Cant you see the behaviour in the code example?

**Comment by rogoit** [comment] 2021-12-07 21:38
Ok i have problem on PHP and composer version for a composer install on my local setup with DDEV. I try going forward

**Comment by TomasVotruba** [comment] 2021-12-14 15:13
I've checked the rule and at the moment there is none that checks nested foreach with if/else variables. Closing as not a bug.

It would be nice addition to have rule like this one. If you decide to contribute, we can help you with the first rule :+1:

**Closed by TomasVotruba** 2021-12-14 15:13 UTC
Labels: bug

**Comment by rogoit** [comment] 2021-12-14 15:23
Sure I try to do want to work on it yesterday night. I am on it this evening...when you have time for a virtual sideview i will be there for you ;)

**Comment by TomasVotruba** [comment] 2021-12-14 22:11
If you can submit PR with new rule, we can review.

**Comment by rogoit** [comment] 2021-12-15 09:48
I do not know how to do. Can we do this live on YT with Screensharing, that would be a good push for the community I think ;)

**Comment by TomasVotruba** [comment] 2021-12-15 10:36
The best start is the documentation for making a rule:
https://github.com/rectorphp/rector/blob/main/docs/create_own_rule.md

**Comment by rogoit** [comment] 2021-12-15 11:22
Thx i will check tonight ;)
