### ISSUE TITLE
Errors from custom rector swallowed without any notice

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#6498] opened 2021-06-08 14:18 UTC
# Bug Report

Following rector produces no error when run:

```php
final class SomeRector extends AbstractRector
{
    /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
        return [Node\Stmt\Return_::class];
    }

    /**
     * @param Node\Stmt\Return_ $node
     */
    public function refactor(Node $node): ?Node
    {
        return false; // type error here
    }

    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('TBD', [new CodeSample('', '')]);
    }

}
```

Run:
```
$ vendor/bin/rector process src/SomeClass.php

 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

[OK] Rector is done! 

```

Used version: 0.11.16 and set up [exacly as described in docs](https://github.com/rectorphp/rector/blob/main/docs/create_own_rule.md).

## Minimal PHP Code Causing Issue

See above.

## Expected Behaviour

Proper error produced:

```
Return value of Utils\Rector\SomeRector::refactor() must implement interface PhpParser\Node or be null, bool returned
```

**Comment by sabbelasichon** [comment] 2021-06-08 17:39
Run it with -vvv please and you will get the error. If it works, please close the issue. Thanks

**Comment by janedbal** [comment] 2021-06-09 08:42
It works, but I disagree that default behaviour should hide errors.

**Comment by sabbelasichon** [comment] 2021-06-09 09:14
I am not saying that the default behaviour is good. Agree with you. 

@TomasVotruba What do you think, should we change the default behaviour in case of an error?

**Comment by TomasVotruba** [comment] 2021-06-09 09:38
:+1: I agree, this is definitely a bug. Errors should be displayed

**Comment by joachim-n** [comment] 2021-06-11 13:41
I am seeing this too:

```
    public function refactor(Node $node): ?Node
    {
        dump(get_class($node));
        dump($node->attributes);
        dump("DOES NOT GET OUTPUT");
```

$node->attributes is protected, so causing an error.

**Comment by joachim-n** [comment] 2021-06-11 13:43
The current behaviour doesn't seem like good DX to me.

Furthermore, it's inconsistent, as:

1. Notices caused by the custom rector DO get output, e.g. 'Notice: Undefined property: PhpParser\Node\Expr\Array_::$name in /Users/joachim/Sites/dcb-repos/repo/drupal-code-builder/MyFirstRector.php on line 42'
2. Errors in the analysed PHP code also get output

**Closed** 2021-06-22 19:21 UTC
Labels: bug

**Comment by sabbelasichon** [comment] 2021-06-22 19:23
@TomasVotruba Thank you. I knew it was that simple.
