### ISSUE TITLE
PHP Fatal error:  Uncaught _PHPStan_5c71ab23c\Nette\FileNotFoundException: File 'phar://phpstan.phar/conf/bleedingEdge.neon'

### ISSUE THREAD

**Issue by underground20** [rectorphp/rector#7696] opened 2022-12-26 19:53 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.6            |
| PHP version | v7.4         |
| Phpstan version | v1.9.4           |

Current issue duplicate https://github.com/rectorphp/rector/issues/2431

## Current behavior
After run process: (`rector process --dry-run`)
```
PHP Fatal error:  Uncaught _PHPStan_5c71ab23c\Nette\FileNotFoundException: File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable. in phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php:29
Stack trace:
#0 phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/NeonLoader.php(29): _PHPStan_5c71ab23c\Nette\DI\Config\Loader->load('phar://phpstan....', false)
#1 phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php(43): PHPStan\DependencyInjection\NeonLoader->load('phar://phpstan....', false)
#2 phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/NeonLoader.php(29): _PHPStan_5c71ab23c\Nette\DI\Config\Loader->load('/var/www/billin...', false)
#3 phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php(43): P in phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29
```

## Minimal PHP Code Causing Issue
My phpstan config includes `bleedingEdge.neon`

includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon

## Expected Behaviour
No fatal, bleedingEdge included.

**Comment by TomasVotruba** [comment] 2022-12-26 22:16
Upgrade Rector and PHPStan to the latest versions.

**Comment by underground20** [comment] 2022-12-27 03:39
Phpstan v1.9.4 is latest, update rector to v0.15.2, the error is still there

**Comment by TomasVotruba** [comment] 2022-12-27 10:44
We'll need a reproducible repository.

**Comment by underground20** [comment] 2022-12-27 11:11
I create repository on Github https://github.com/underground20/rector-sandbox

**Comment by samsonasik** [comment] 2022-12-28 12:16
That's seems due to use in Docker, you may need to run from vendor from root project:

```
vendor/bin/rector process --dry-run
```

**Comment by underground20** [comment] 2022-12-28 15:00
> That's seems due to use in Docker, you may need to run from vendor from root project:
> 
> ```
> vendor/bin/rector process --dry-run
> ```

I run command `vendor/bin/rector process --dry-run` on native php (without docker),  the error is still there

**Comment by samsonasik** [comment] 2022-12-29 01:48
You may need to configure using phar url:

```
includes:
    - phar://vendor/phpstan/phpstan/phpstan.phar/conf/bleedingEdge.neon
```

I test locally and it seems working ok with phar url.

**Comment by underground20** [comment] 2022-12-29 04:22
> - phar://vendor/phpstan/phpstan/phpstan.phar/conf/bleedingEdge.neon

Yes, it is works in my local repository https://github.com/underground20/rector-sandbox, but it is not working in other repository
```
PHP Fatal error:  Uncaught _PHPStan_76bd347d2\Nette\Schema\ValidationException: Unexpected item 'parameters › featureToggles › listType'. in phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Processor.php:75
Stack trace:
#0 phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Processor.php(38): _PHPStan_76bd347d2\Nette\Schema\Processor->throwsErrors()
#1 phar:///var/www/billing/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ParametersSchemaExtension.php(44): _PHPStan_76bd347d2\Nette\Schema\Processor->process(Object(_PHPStan_76bd347d2\Nette\Schema\Elements\Structure), NULL)

```
Is there any other way to make this work without crutches?

**Comment by samsonasik** [comment] 2022-12-29 05:35
parameters error usually due to different version between phpstan in vendor and phpstan in prefixed rector vendor, try latest dev-main

**Comment by samsonasik** [comment] 2022-12-29 05:35
parameters error usually due to different version between phpstan in vendor and phpstan in prefixed rector vendor, try latest dev-main

**Comment by underground20** [comment] 2023-01-06 11:19
> - phar://vendor/phpstan/phpstan/phpstan.phar/conf/bleedingEdge.neon

I upgrade rector to v0.15.2 (latest) and use configuration via phar url, the error is no longer reproduced

**Comment by samsonasik** [comment] 2023-01-06 11:21
@underground20 Thank you for verify, I am closing it then ;)

**Closed by samsonasik** 2023-01-06 11:21 UTC
Labels: bug

**Comment by underground20** [comment] 2023-01-06 11:29
> @underground20 Thank you for verify, I am closing it then ;)

Thank you for Rector)
