### ISSUE TITLE
Couldn't find constant expose:true

### ISSUE THREAD

**Issue by ThomasTr** [rectorphp/rector#3225] opened 2020-04-23 11:15 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.17              |
| Installed as   | composer dependency                       |

Rector changes options={"expose"=true} in @ Route annotation, causes error:

[Semantical Error] Couldn't find constant expose:true, method App\Controller\API\AccountingController::contact() in .... 
Make sure annotations are installed and enabled.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/e0fc28be-0156-41a9-bc98-5ccabf9b76d3

## Expected Behaviour

Rector should not touch options={"expose"=true} in @Route annotation.

Expose=true comes from FOSJsRoutingBundle.

**Comment by ThomasTr** [comment] 2020-04-23 12:10
Also in phpdoc but here in @Assert\Choice:
```
      * @Assert\Choice(
-     *         choices = {"Open", "Close", "Deleted"},
-     *         message = "Bitte gültigen Status wählen.",
-     *         strict = true
-     * )
+     *         {"Offen", "In Bearbeitung", "Geschlossen", "Rechnung", "Veröffentlichung", "Feedback"}, strict=true )
```
and here:
```
-     * @ORM\Column(name="customer_id", type="integer", nullable=false, options={"default" = 0})
+     * @ORM\Column(name="customer_id", type="integer", nullable=false, options={default:0})
```

**Comment by TomasVotruba** [comment] 2020-04-23 12:25
You need to remove spaces around ` = `, see https://github.com/rectorphp/rector/issues/3212#issuecomment-617792010

**Comment by ThomasTr** [comment] 2020-04-23 15:50
changed the spacing, but problem still exists here for me, here it suggests expose without quotes, which breaks:

```diff
     /**
-     * @Route("/{contactId}/edit/{page}", name="accounting_contact_edit", options={"expose"=true})
+     * @Route("/{contactId}/edit/{page}", name="accounting_contact_edit", options={expose:true})
      */
     public function edit(Request $request, Contact $contact, int $page = 0): Response

**Comment by ThomasTr** [comment] 2020-04-23 15:56
Here it whipes the message out (event without spaces)
```diff
      * @Assert\Choice(
      *         choices={"Offen", "In Bearbeitung", "Geschlossen", "Rechnung", "Veröffentlichung", "Feedback"},
-     *         message="Bitte gültigen Status wählen.",
-     *         strict=true
-     * )
+     *         strict=true )
```

**Comment by ThomasTr** [comment] 2020-04-23 15:58
In doctrine annotations it suggests default with quotes which breaks
```diff
      *
      * @Assert\Range(min = 0, max = 1)
      *
-     * @ORM\Column(name="agency", type="smallint", length=1, nullable=false, options={"default":0})
+     * @ORM\Column(name="agency", type="smallint", length=1, nullable=false, options={default:0})
      */
     private $agency;
```

**Comment by stephanvierkant** [comment] 2020-04-24 11:05
@TomasVotruba I see `\Rector\BetterPhpDocParser\Tests\PhpDocParser\TagValueNodeReprint\Fixture\SymfonyRoute\RouteWithCondition` uses a colon instead of an equal sign. Why?

Both Doctrine and Symfony are using `=` in there documention.

**Comment by stephanvierkant** [comment] 2020-04-24 15:42
What about using `\Rector\BetterPhpDocParser\PhpDocNode\AbstractTagValueNode::printArrayItemWithSeparator` instead of `printArrayItem` in `\Rector\BetterPhpDocParser\PhpDocNode\Symfony\SymfonyRouteTagValueNode::__toString`?

**Comment by TomasVotruba** [comment] 2020-05-04 17:29
Closing as original issue was resolved.

**Closed by TomasVotruba** 2020-05-04 17:29 UTC

**Comment by tavy315** [comment] 2020-06-15 19:18
@stephanvierkant do you have a link for the documentation where Doctrine is using `=`? Examples on Doctrine's documentation are with semicolon. See [example](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/annotations-reference.html#line-number-8f3e950b7cf37a3ab5ef14ee89a4561aa0df5f58-1).

**Comment by TomasVotruba** [comment] 2020-06-15 21:57
@tavy315 It might be confusing to see different pattern at 2 lines (don't mind the @Route, can be @Assert).

```php
 /**
     * @Route("/{contactId}/edit/{page}", options={"expose"=true})
     * @ORM\Column(options={default:0})
     */
```

Personally I'd go with `=`, as Symfony "standard" is more spread.

**Comment by tavy315** [comment] 2020-06-16 12:22
Well, can't see a standard yet, their documentation is using both cases even on same page ([example](https://symfony.com/doc/current/routing.html#slash-characters-in-route-parameters))
```
@Route("/share/{token}", name="share", requirements={"token"=".+"})
@Route("/blog/{page}", name="blog_index", defaults={"page": 1, "title": "Hello world!"})
```
Assert also uses `:` in this [example](https://symfony.com/doc/current/reference/constraints/Expression.html#values).
```
    /**
     * @Assert\Expression(
     *     "value + error_margin < threshold",
     *     values = { "error_margin": 0.25, "threshold": 1.5 }
     * )
     */
```

The problem is that I was using the example from Doctrine documentation and rector refactored my code for no reason, since both are correct.

So, it's either opinionated and you recommend the usage of `=`, either we should ignore or support both cases (so it doesn't change the code if the other case is used).

**Comment by TomasVotruba** [comment] 2020-06-16 13:20
> So, it's either opinionated and you recommend the usage of =

:+1: 

> either we should ignore or support both cases (so it doesn't change the code if the other case is used).

If you need this feature, I'm open to PR.

> Sorry for pushing the subject, I guess that's why I never liked using annotations (for routes, validations, entities nor templating). 

Personally I use regex to change the code to comply with this standard, than focus on coding instead :wink:

**Comment by Charl13** [comment] 2020-12-20 12:35
> If you need this feature, I'm open to PR.

@TomasVotruba I've created a PR that aims to support both cases.
