### ISSUE TITLE
rector does nothing.

### ISSUE THREAD

**Issue by N6REJ** [rectorphp/rector#8943] opened 2024-12-18 19:48 UTC
I'm trying to upgrade from php 5.6.40 to php 8.2.26
I followed these instructions since my code is currently built for php 5.6.40
https://getrector.com/documentation/how-to-run-on-php-53 and what I get is just a blank return.

![image](https://github.com/user-attachments/assets/c59beb22-c7ae-4f40-8787-821bae9a2a82)

From what I understand its supposed to show a progress bar and take only a few minutes.  I've had it running for hours with nothing indicating its doing anything.
I also noticed it left out my `bins` folder.
And I'm not sure that it will process all the .php files in my `classes` folder, which it needs to do.
What am I doing wrong?
i'm using php 8.3.11 for my active php
![image](https://github.com/user-attachments/assets/9c9758e3-8f67-44e3-ae79-3d7b802e2618)
and composer is 2.7.9
![image](https://github.com/user-attachments/assets/ded4ef71-939e-4b7e-87cb-95760b48725a)

**Comment by samsonasik** [comment] 2024-12-18 22:33
`composer require` without `composer init` cause `composer.json` not created, could you try initialization:

```
composer init
```

to ensure `composer.json` exists in the first place on `rector-standalone` directory, then re-run `composer require rector/rector --dev`

```
composer init
composer require rector/rector --dev
```

**Comment by N6REJ** [comment] 2024-12-19 00:47
I did that and nothing changed.
![image](https://github.com/user-attachments/assets/398cc770-4787-4f10-bf7d-92fee0685eea)

**Comment by samsonasik** [comment] 2024-12-19 04:50
I tried and it seems working ok 

![Screenshot 2024-12-19 at 11 48 03](https://github.com/user-attachments/assets/24db284e-723f-4bf6-80c7-14fe09fb74d0)

could you try single file only to target file, eg:

```
../rector-standalone/vendor/bin/rector process actions/Foo.php  --dry-run
```

if that works, please narrow down to locate what file that cause it 

Read this post: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by N6REJ** [comment] 2024-12-19 04:54
still didn't work.  idk wth I'm doing wrong.
![image](https://github.com/user-attachments/assets/0b9c0f28-c5e5-42ae-8028-650aebd2c71d)

**Comment by samsonasik** [comment] 2024-12-19 05:06
It seems you're using windows, could you try to use command prompt (cmd) or bash for Windows ? see readme for it

https://github.com/rectorphp/rector?tab=readme-ov-file#known-drawbacks

If still not works, could you try disable parallel? Add:

```
->withoutParallel();
```

in the config

**Comment by N6REJ** [comment] 2024-12-19 07:04
I was using the jetbrains IDEA ide terminal.  I just tried with command prompt with same result.  
![image](https://github.com/user-attachments/assets/46686cf8-919a-41cf-9650-414c55483134)
![image](https://github.com/user-attachments/assets/9d52284d-0e1e-43b9-9619-63ba86d8f2f3)

**Comment by samsonasik** [comment] 2024-12-19 07:26
Not sure, could you share simple repository with minimal files to let us try? We don't have windows env locally, but let see if we can reproduce it in other os

**Comment by N6REJ** [comment] 2024-12-19 23:58
I appreciate all your help.  The only folder we need to be concerned with is `/core/classes` and its children.
https://github.com/Bearsampp/sandbox/tree/rector/core/classes

**Comment by samsonasik** [comment] 2024-12-20 00:38
I tried that, it seems working ok:

```diff
➜  classes git:(main) ✗ ../rector-standalone/vendor/bin/rector process --dry-run |more
 44/44 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
44 files with changes
=====================

1) tpls/app/class.tpl.app.nodejs.php:38

    ---------- begin diff ----------
@@ @@
         return TplApp::getMenuEnable(
             $bearsamppLang->getValue(Lang::NODEJS),
             self::MENU,
-            get_called_class(),
+            static::class,
             $bearsamppBins->getNodejs()->isEnable()
         );
     }
@@ @@
         // Enable
         $tplEnable = TplApp::getActionMulti(
             self::ACTION_ENABLE,
-            array($isEnabled ? Config::DISABLED : Config::ENABLED),
-            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
+            [$isEnabled ? Config::DISABLED : Config::ENABLED],
+            [$bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''],
             false,
-            get_called_class()
+            static::class
         );
```

is that any different if you run rector on github action or same directory inside classes itself?

**Comment by N6REJ** [comment] 2024-12-20 02:51
I don't understand what you mean.  How can I do that.  I'll happily change ANYTHING.  Also how do I make sure it does the file in classes as well as all sub directories

**Comment by samsonasik** [comment] 2024-12-20 05:49
You may can setup github action for windows, with set `windows-latest` on os matrix, create steps in the config so it can run on github, for example:

https://github.com/rectorphp/rector-src/blob/main/.github/workflows/tests.yaml#L20

**Comment by staabm** [comment] 2024-12-21 08:00
I think your php is halting because you have something like "break on first statement" enabled in phpstorm. 

Try disabling xdebug in your php CLI

**Comment by samsonasik** [comment] 2024-12-27 14:13
I am closing this as we can't reproduce it, as @staabm suggestion above, try disable xdebug in case there is because of it.

**Closed by samsonasik** 2024-12-27 14:13 UTC
