### ISSUE TITLE
Php4ConstructorRector rule not applied

### ISSUE THREAD

**Issue by akash-grexit** [rectorphp/rector#8100] opened 2023-07-31 14:52 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.7             |

## Minimal PHP Code Causing Issue

foo.php
```
<?php

class Foo {
    function Foo() { 
        echo 'Constructed!';
    }
}
```

rector.php
```
<?php

use Rector\Config\RectorConfig;
use Rector\Php70\Rector\ClassMethod\Php4ConstructorRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([__DIR__ . '/public/src/foo.php']);
    // register single rule
    $rectorConfig->rule(Php4ConstructorRector::class);
};
```

## Expected Behaviour

```
 <?php
 
 class Foo {
    function __construct() { 
         echo 'Constructed!';
     }
 }
 ```

Demo: https://getrector.com/demo/8e684b99-3c59-48a1-8730-d9cddc88aaac

I tested the rule in this demo environment, and it's working there. However, it's not working on my machine.

**Comment by samsonasik** [comment] 2023-08-01 15:41
We unfortunatelly can't help without reproducible code, it possibly due to typo or some case sensitive in part of name class. I am closing it, feel free to re-open with reproducible code when you can, thank you,

**Comment by dimov-cz** [comment] 2023-10-19 12:15
### Title: Inconsistent Output between PHP 7 and PHP 8 in Rector v0.18.5

#### Description

Noticed the same issue, not applied rules. I'm observing different behaviors when running Rector v0.18.5 on PHP 7 and PHP 8, despite the `composer.json` indicating support for both versions (`"php": "^7.2|^8.0"`). 

#### Steps to Reproduce

1. Install Rector v0.18.5.
2. Run Rector on a codebase using PHP 7.

#### Expected Behavior

The output should be consistent regardless of the PHP version used.

#### Actual Behavior

The output is not the same when using PHP 7.

#### Environment

- **Rector version:** 0.18.5
- **PHP version:** 7.x
- **Operating System:** [Your OS]

#### Additional Information

I noticed the same issue as above.

**Comment by samsonasik** [comment] 2023-10-19 12:19
Again, we can't help without reproducible code.

**Comment by dimov-cz** [comment] 2023-10-19 13:10
I have created minimal repo to reproduce, code taken from the report above. 

Steps to reproduce:
```
git clone git@github.com:dimov-cz/rector-issue8100.git .
composer install
vendor/bin/rector process --dry-run --debug
```

PHP 8.1 environment output:

```
/mnt/devCode/y/src/foo.php

1 file with changes
===================

1) src/foo.php:0

    ---------- begin diff ----------
@@ @@
 <?php

 class Foo {
-    function Foo() {
+    function __construct() {
         echo 'Constructed!';
     }
 }
    ----------- end diff -----------


 [OK] 1 file would have changed (dry-run) by Rector
```

PHP 7.4 environment output:

```
/mnt/devCode/x/src/foo.php


 [OK] Rector is done!
```

**Comment by samsonasik** [comment] 2023-10-19 13:36
I see, the :

```php
if (!$classReflection->hasConstructor()) {
```

seems only detected on php8+, while on php 7.x, it not detected.

**Closed** 2023-10-19 13:44 UTC
Labels: bug
