### ISSUE TITLE
Massive slowdown after upgrading to Rector 0.12.22

### ISSUE THREAD

**Issue by bobvandevijver** [rectorphp/rector#7144] opened 2022-04-30 13:40 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.22             |

After upgrading to from 0.12.21 to 0.12.22, I experience a massive slowdown. The most extreme slowdown seems to originate from the `SymfonyLevelSetList::UP_TO_SYMFONY_60` setlist, but also without that setlist you can see a more than 2 times slowdown on my codebase.

I have run the following command to test (explictly with clear cache every time), limited to a subdirectory to speed up:

```
time cs_tools/vendor/bin/rector process  --autoload-file=vendor/autoload.php --clear-cache src/Service
```

| Rector version | UP_TO_SYMFONY_60 enabled | Time | Slowdown factor |
| ----- | -- | ---- | - |
| 0.12.21 | yes | real    1m10.599s / user    1m8.372s / sys     0m1.902s | - |
| 0.12.22 | yes | real    10m2.571s / user    10m0.432s / sys     0m1.907s | ~9x |
| 0.12.21 | no | real    0m28.561s / user    0m26.901s / sys     0m1.571s | - |
| 0.12.22 | no | real    0m57.258s / user    0m55.734s / sys     0m1.484s | ~2x |

I'm still waiting on the full folder analysis being done in my automated pipeline, which is current already working for 55 minutes while it took about 10 minutes before the upgrade 😅 (I guess it will be killed before it completes - _yes, it did indeed_)

<details>
<summary>rector.php</summary>

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Php74\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Php80\Rector\Class_\AnnotationToAttributeRector;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Php80\ValueObject\AnnotationToAttribute;
use Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SensiolabsSetList;
use Rector\Symfony\Set\SymfonyLevelSetList;
use Rector\Symfony\Set\SymfonySetList;
use Rector\TypeDeclaration\Rector\ClassMethod\ReturnNeverTypeRector;

return static function (RectorConfig $rc): void {
  $rc->paths([__DIR__ . '/src']);
  $rc->importNames();
  $rc->skip([
      ReadOnlyPropertyRector::class, // Cannot be used with proxies yet (https://github.com/Ocramius/ProxyManager/issues/737)
      ReturnNeverTypeRector::class, // Not working properly
      ClassPropertyAssignToConstructorPromotionRector::class, // Messes up the annotations
      TypedPropertyRector::class, // Not usable yet, since the serializer has a bug (https://github.com/schmittjoh/serializer/issues/1282)
      ArraySpreadInsteadOfArrayMergeRector::class, // Not very useful, leads to Phan issue
  ]);

  $rc->import(DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES);
  $rc->import(SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES);
  $rc->import(SensiolabsSetList::FRAMEWORK_EXTRA_61);
  $rc->import(LevelSetList::UP_TO_PHP_81);
  $rc->import(SetList::TYPE_DECLARATION_STRICT);
  $rc->import(SymfonyLevelSetList::UP_TO_SYMFONY_60);
  $rc->import(DoctrineSetList::DOCTRINE_CODE_QUALITY);

  $rc->ruleWithConfiguration(AnnotationToAttributeRector::class, [
    // Drenso
      new AnnotationToAttribute(Drenso\Shared\LockableController\UseLock::class),
      new AnnotationToAttribute(Drenso\Shared\FeatureFlags\RequireFeature::class),
    // Doctrine
      new AnnotationToAttribute(Doctrine\ORM\Mapping\AssociationOverrides::class),
      new AnnotationToAttribute(Doctrine\ORM\Mapping\AssociationOverride::class),
    // Symfony missed validator
      new AnnotationToAttribute(Symfony\Component\Validator\Constraints\All::class),
    // Gedmo
      new AnnotationToAttribute(Gedmo\Mapping\Annotation\SoftDeleteable::class),
    // JMS Serializer
      new AnnotationToAttribute(JMS\Serializer\Annotation\Exclude::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\Expose::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\ExclusionPolicy::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\Type::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\Groups::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\VirtualProperty::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\Discriminator::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\SerializedName::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\Accessor::class),
      new AnnotationToAttribute(JMS\Serializer\Annotation\MaxDepth::class),
    // Vich
      new AnnotationToAttribute(Vich\UploaderBundle\Mapping\Annotation\Uploadable::class),
      new AnnotationToAttribute(Vich\UploaderBundle\Mapping\Annotation\UploadableField::class),
    // PhoneNumber
      new AnnotationToAttribute(Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber::class),
  ]);
};
```

(I removed a couple of the `AnnotationToAttribute` that referenced our internal validators, 33 to be precise)
</details>

**Comment by TomasVotruba** [comment] 2022-04-30 15:50
Hi, thanks for report. Could you narrow down the rule that is causing it? I assume it will be that loops over single piece of code too many times :)

Reproducible repository would be helpful as well.

**Comment by jrmcpeek** [comment] 2022-04-30 17:42
Potentially related, but the codebase we use rector on (~300 files, ~25k SLOC) could no longer run with `parallel()` set after 0.12.22, even with multiple passes and cache enabled.

We receive an error that the child/worker process timed out after 120 seconds.

On 0.12.21 with `parallel()` set, we get:

```
real	0m54.650s
user	0m1.440s
sys	0m0.228s
```

The error message referenced a `symplify` dependency and looked to be parsing through our `vendor` folder despite not being included in the search paths.

I reverted back to 0.12.21 and it fixed the issue, so I don't have the exact error message (and running with `--debug` didn't generate anything different).

If I get some time, I may re-up the rector version and see if I can get more concrete details.

**Comment by bobvandevijver** [comment] 2022-04-30 18:31
Wait, there is an option for `parallel`? Today I learned, should have known about that earlier! But it does indeed throw an error:


```
bobvandevijver@webdev81:/var/www/dev$ time cs_tools/vendor/bin/rector process  --autoload-file=vendor/autoload.php --clear-cache src/Service/
 43/63 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  68%

 [ERROR] Could not process
         "/var/www/dev/cs_tools/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php" file, due to:
         "Child process timed out after 120 seconds". On line: 103

 [ERROR] Could not process some files, due to:
         "Reached system errors count limit of 50, exiting...".
```

To be honest, I do not think it is caused by a single rule, but more like an exponentially grow with the amount of rules. I tried with a couple of settings,

**Comment by jrmcpeek** [comment] 2022-04-30 18:33
> Wait, there is an option for parallel

Surprise! 🥳

The error you've got is the same we saw under 0.12.22.

**Comment by TomasVotruba** [comment] 2022-04-30 18:52
Could you narrow down which of rules in `SymfonyLevelSetList::UP_TO_SYMFONY_60` are the slow pokes?
Then we could find out what has changed in those.

**Comment by bobvandevijver** [comment] 2022-04-30 19:54
That's the thing, it seems to be the `RenameMethodRector` configuration in the Symfony30 set, but that one did not change at all (I edited my previous comment, as I accidentally posted it before I finished it, so you might not have seen that part).

I created an xdebug profile to see if I could see anything, but that only seems to point to [RenameClassConstFetchRector](https://github.com/rectorphp/rector-src/blob/main/rules/Renaming/Rector/ClassConstFetch/RenameClassConstFetchRector.php), which also hasn't changed in the past two months...

![image](https://user-images.githubusercontent.com/1835343/166120673-5bcb9283-d6e8-4ff8-8f54-db7c747f2325.png)

![image](https://user-images.githubusercontent.com/1835343/166120704-a388ec7c-f57a-4c0b-a33e-e26532a4084b.png)

**Comment by samsonasik** [comment] 2022-04-30 20:37
I can see it 4x slowdown in CodeIgniter project as well, so I increase the timeout:
https://github.com/codeigniter4/CodeIgniter4/blob/aee95af56f9d036aca55ee254740fb7e50291a1d/rector.php#L169

It probably happen after we move out from attribute check to loop the stmts/parent lookup.

I will lookup into it, but possibly after holiday next week ( I bring old - slow laptop )

**Comment by samsonasik** [comment] 2022-04-30 21:15
I was guessing it was because of parent class lookup property, but after disable `TypedPropertyRector`, it still happen, so it unrelated with that:

```
 time vendor/bin/rector process system --dry-run --clear-cache
 100/404 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  24%
                                                                                                                        
 [ERROR] Could not process                                                                                              
         "/Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/Parallel
         Process.php" file, due to:                                                                                     
         "Child process timed out after 240 seconds". On line: 103                                                      
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process some files, due to:                                                                          
         "Reached system errors count limit of 50, exiting...".                                                         
                                                                                                                        
```

**Comment by samsonasik** [comment] 2022-04-30 21:24
ref  https://github.com/rectorphp/rector/issues/7126

**Comment by samsonasik** [comment] 2022-05-01 06:44
@TomasVotruba it possibly related with change by lookup file->getNewStmts() on BetterNodeFinder->findFirstPrevious, which seems make it find all stms over again if not found, which current node itself is hit again by search.

https://github.com/rectorphp/rector-src/commit/e7caae2a5ca85ac9d909f4d66bbad361d72c1482#diff-a658c135f88f0c6bfdd6a0dc7c25761a25747c595ce47a701fb6f7dc2859c74e

from PR:
- https://github.com/rectorphp/rector-src/pull/2136

**Comment by samsonasik** [comment] 2022-05-01 13:39
ref for improvement of `BetterNodeFinder::findFirstPrevious()` to only lookup of previous of parent when no previous stmt.

- https://github.com/rectorphp/rector-src/pull/2209

**Comment by TomasVotruba** [comment] 2022-05-01 13:47
@samsonasik Feel fre to merge, if it works well, so we can test it :+1:

**Comment by samsonasik** [comment] 2022-05-01 14:00
@TomasVotruba merged 👍 

@bobvandevijver could you try latest dev-main and verify if there is speed improvement? Thank you.

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by bobvandevijver** [comment] 2022-05-01 14:55
Yes, this absolutely caused a significant improvement!

real    1m22.219s
user    1m20.160s
sys     0m1.863s

**Comment by samsonasik** [comment] 2022-05-01 14:58
@bobvandevijver thank you for verify. I am closing it then ;)

**Closed by samsonasik** 2022-05-01 14:58 UTC
Labels: bug

**Comment by bobvandevijver** [comment] 2022-05-01 15:04
@samsonasik Great work, thank you! Just verified it is also fixed in our pipeline now, and the `parallel` option now also works like I charm. I would love to see a quick release with this fix!

@jrmcpeek Thanks again for pointing to the `parallel` option by the way, our pipeline now completes in three minutes instead of 10 😄

**Comment by TomasVotruba** [comment] 2022-05-01 15:40
Thank you guys for handling this one :+1: 
I'll manage release in a couple minutes....
