### ISSUE TITLE
Comments on else line cause missing open brace on processing

### ISSUE THREAD

**Issue by phpfui** [rectorphp/rector#3639] opened 2020-07-02 20:02 UTC
# Bug Report

| Subject          | Details                                                                                     |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.41                                                                                    |
| Installed as   | composer dependency / php vendor\rector\rector\bin\rector    |

The processed code is missing an opening brace for the else clause.

rector.yaml file contents:
services:
    Rector\Php70\Rector\FunctionLike\Php4ConstructorRector: null

## Minimal PHP Code Causing Issue

~~~php
if(false){}else // on else line, can be // or /**/
{ // comment in braces of else, must be // not /**/
	$this_must_be_here = false;}

if(false){}else /* on else line, can be // or /**/
{ // comment in braces of else, must be // not /**/
	$this_must_be_here = false;}

if(false){}else // on else line, can be // or /**/
{ /* comment in braces of else, this works */
	$this_must_be_here = false;}

if(false){}else
{ // comment in braces of else, this works because no prior comment
	$this_must_be_here = false;}

if(false){}else
{ /* comment in braces of else, this works because no prior comment */
	$this_must_be_here = false;}
~~~

First two if statements don't work, last three work.

https://getrector.org/demo/b0f21b43-545a-4072-8a2b-712f1f521707#result

## Expected Behaviour

No change to the file.  Generates syntactically incorrect file.

**Comment by TomasVotruba** [comment] 2020-07-02 20:15
Could you verify this is handled in pure php-parser?  

There was similar bug recently closed as won't fix: https://github.com/rectorphp/rector/issues/3504#issuecomment-644019926

**Comment by phpfui** [comment] 2020-07-03 00:20
This code seems to reconstruct from the AST.

~~~php
<pre>
<?php
include 'vendor/autoload.php';
$factory = new \PhpParser\ParserFactory();
$parser = $factory->create(\PhpParser\ParserFactory::PREFER_PHP7);
$code = '<?php
if(false){}else // on else line, can be // or /**/
{ // comment in braces of else, must be // not /**/
	$this_must_be_here = false;}';
$ast = $parser->parse($code);
$prettyPrinter = new \PhpParser\PrettyPrinter\Standard(['shortArraySyntax' => true]);
echo $prettyPrinter->prettyPrint($ast);
~~~

**Comment by TomasVotruba** [comment] 2020-07-03 12:52
What's the output?

**Comment by phpfui** [comment] 2020-07-03 13:47
Same as input, or close enough. Keeps the open brace on the else, where
Rector does not.

**Comment by TomasVotruba** [comment] 2020-07-03 14:09
So it's correct php-parser but broken in Rector?

**Comment by phpfui** [comment] 2020-07-03 14:46
Exactly.  Did some debugging and found the oldStmts array was correct, but
did not get past that when I had to finish for the day. Forgot exactly
where in the code that was.

It's a holiday here, so going out for a bike ride, but should be back in
afternoon. Will see if I can figure out more then. Let me know if there is
anything specific I can help with. This project is great and want to help
any way I can.

**Comment by plasticlobster** [comment] 2020-07-15 17:29
I should also mention (from #3711, which I closed because it's a duplicate of this issue) - It doesn't have to be in an else line. If the comment is after an if statement, the same issue occurs. See #3711 for my examples.

**Comment by TomasVotruba** [comment] 2020-07-16 11:56
If you hurry on this, you can use this sniff as hotfix: SlevomatCodingStandard\Sniffs\Commenting\DisallowCommentAfterCodeSniff

**Comment by TomasVotruba** [comment] 2020-07-26 17:30
I'm looking into this

**Closed** 2020-07-26 17:34 UTC
Labels: bug

**Comment by TomasVotruba** [comment] 2020-07-26 17:36
Thanks for reporting and broken code example. It helped me to fix it effectively :+1:
