### ISSUE TITLE
`DowngradeFlexibleHeredocSyntaxRectorTest` on windows fails

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#6571] opened 2021-07-16 07:30 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. b001e38 (invoke `vendor/bin/rector --version`)             |

running `vendor/bin/phpunit rules-tests/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector/DowngradeFlexibleHeredocSyntaxRectorTest.php` on windows leads to the following error:

```diff
1) Rector\Tests\DowngradePhp73\Rector\String_\DowngradeFlexibleHeredocSyntaxRector\DowngradeFlexibleHeredocSyntaxRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 SELECT *
 FROM `table`
 WHERE `column` = true;
-SQL;
+SQL
+;
         $this->setOnClick(<<<SQL
 SELECT *
 FROM `table`

C:\dvl\GitHub\rector-src-staabm\packages\Testing\PHPUnit\AbstractRectorTestCase.php:131
C:\dvl\GitHub\rector-src-staabm\packages\Testing\PHPUnit\AbstractRectorTestCase.php:92
C:\dvl\GitHub\rector-src-staabm\rules-tests\DowngradePhp73\Rector\String_\DowngradeFlexibleHeredocSyntaxRector\DowngradeFlexibleHeredocSyntaxRectorTest.php:21
```

I don't know why on windows there is a additional newline in this heredoc part

**Comment by staabm** [comment] 2021-07-19 08:42
also affects `rules-tests/DowngradePhp70/Rector/String_/DowngradeGeneratedScalarTypesRector/DowngradeGeneratedScalarTypesRectorTest.php`

**Comment by staabm** [comment] 2021-07-19 10:02
same for `rules-tests/Defluent/Rector/ClassMethod/ReturnThisRemoveRector/ReturnThisRemoveRectorTest.php`

**Comment by staabm** [comment] 2021-07-19 10:12
and here: `rules-tests/Php73/Rector/String_/SensitiveHereNowDocRector/SensitiveHereNowDocRectorTest.php`

**Comment by TomasVotruba** [comment] 2021-07-19 10:23
I think once the issue is solved, lot of files will be fixed. No need to report them all :)

**Comment by staabm** [comment] 2021-07-19 10:25
I think the list is now complete. :)

**Comment by TomasVotruba** [comment] 2021-07-19 11:16
I see 👍

**Comment by TomasVotruba** [comment] 2021-08-08 19:56
Thanks for reporting. This could grow into huge list of Windows-related issues, and clutter the issue tracker. Mostly is related to whitespace/newlines, common case for Windows. Instead of reporting every single rule, **it is more useful to fix the found cases via PR**.

Saying that, I'm closing this issue to keep focus on general issues affecting any OS.
Thank you for understanding.

**Closed by TomasVotruba** 2021-08-08 19:56 UTC
Labels: bug
