### ISSUE TITLE
Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers()  must be of the type int, null given

### ISSUE THREAD

**Issue by bramdevries** [rectorphp/rector#3718] opened 2020-07-15 19:07 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `^0.7.20`              |
| Installed as   | Docker image                      |

I have set up the following alias to run `rector` through a docker container in the current directory:

```bash
function rector {
  docker run --rm -v $(pwd):/project rector/rector:0.7.48 process /project/app --config /project/rector.yaml --autoload-file /project/vendor/autoload.php
}

$ rector
```

Once I run this I see a lot of notices and errors appear: 

```bash
Notice: Undefined property: PhpParser\Node\Param::$flags in /project/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 21

...

[ERROR] Could not process
         "../project/app/Projects/Processing/Traits/KnowsProcessors.php" file,
         due to:
         "Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers()
         must be of the type int, null given, called in
         /project/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.p
         hp on line 21".
```

This issue seems to have been reported before in https://github.com/rectorphp/rector/issues/3640 but was mentioned to be fixed, which is why I opened a new one. I tried running various versions and the errors are present in all versions starting from 0.7.20.

**Comment by TomasVotruba** [comment] 2020-07-15 19:32
This probably won't be resolved until PHPStan upgrade to php-parser 4.6

**Comment by bramdevries** [comment] 2020-07-15 19:35
Just to clarify: Is this something caused by the code in my project? It seems very strange to me that all published releases from the past 3 months are unusable due to this bug.

**Comment by TomasVotruba** [comment] 2020-07-15 19:37
Nope. This is due to conflicting dependencies of Rector, PHPStan, they're using php-parser in different version.

**Comment by bramdevries** [comment] 2020-07-15 19:51
From what I can tell the [`0.7.48`](https://github.com/rectorphp/rector/blob/v0.7.48/composer.json#L21) release of Rector is locked to `nikic/php-parser:4.5` and the [`0.12.32`](https://github.com/phpstan/phpstan-src/blob/0.12.32/composer.json#L22) release of PHPStan is using [`^4.5`](https://semver.mwl.be/#!?package=nikic%2Fphp-parser&version=%5E4.5.0&minimum-stability=stable) which would already result in the `4.6` release being installed.


You mention we should wait for PHPStan to upgrade to 4.6 but it seems like Rector should be the one to upgrade?

**Comment by TomasVotruba** [comment] 2020-07-15 21:08
> You mention we should wait for PHPStan to upgrade to 4.6 but it seems like Rector should be the one to upgrade?

Could you confirm it helps?

**Comment by bramdevries** [comment] 2020-07-16 20:22
I tried upgrading to `nikic/php-parser:4.6` but that didn't fix it:

I ran with the `-vvv` flag to see if there's any additional information about the error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\PrettyPrinterAbstract::pModifiers() must be of the type int, null given, called in /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 21 and defined in /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:1035
Stack trace:
#0 /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(21): PhpParser\PrettyPrinterAbstract->pModifiers(NULL)
#1 /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pParam(Object(PhpParser\Node\Param))
#2 /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(389): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\ in /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php on line 1035
```

So it looks like the error is coming from the installed version of `nikic/php-parser` in my application? That seems super weird to me, any idea why it would do that?

**Comment by TomasVotruba** [comment] 2020-07-16 20:25
It's hard to say where the issure is. 

- Can you reproduce the error with php-parser alone?
- What php-parser version is packed in `phpstan.phar`?

**Comment by bramdevries** [comment] 2020-07-16 20:38
> Can you reproduce the error with php-parser alone?

How would I approach trying to reproduce it using php-parser alone? 

> What php-parser version is packed in phpstan.phar?

In which `phpstan.phar`? In my own project I'm using https://github.com/nunomaduro/larastan and a `composer show nikic/php-parser` shows:

```
name     : nikic/php-parser
descrip. : A PHP parser written in PHP
keywords : parser, php
versions : * v4.6.0
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage :
source   : [git] https://github.com/nikic/PHP-Parser.git c346bbfafe2ff60680258b631afb730d186ed864
dist     : [zip] https://api.github.com/repos/nikic/PHP-Parser/zipball/c346bbfafe2ff60680258b631afb730d186ed864 c346bbfafe2ff60680258b631afb730d186ed864
path     : /Users/bramdevries/Documents/madewithlove/ChangeHub/application/vendor/nikic/php-parser
names    : nikic/php-parser

autoload
psr-4
PhpParser\ => lib/PhpParser

requires
ext-tokenizer *
php >=7.0

requires (dev)
ircmaxell/php-yacc 0.0.5
phpunit/phpunit ^6.5 || ^7.0 || ^8.0
```

But I would still like to know why Rector is using the dependencies of my own application? I was under the assumption that by using the Docker image it would run as a standalone binary, with it's own dependencies.

**Comment by TomasVotruba** [comment] 2020-07-16 20:43
> How would I approach trying to reproduce it using php-parser alone?

Creating [Parser](https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#parsing) and [Printer](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown#basic-usage).

> In which phpstan.phar?

I'd look to `vendor/phpstan/phpstan/*`

> But I would still like to know why Rector is using the dependencies of my own application? 

It works with static analysis of your code, also for reflection. So it needs to access to all classes that your application has, via `vendor/autoload.php`

So it uses it's own dependencies in Docker, but still works with your project's context.

**Comment by Aerendir** [comment] 2020-07-17 12:55
The dependency is locked because the version 4.6 causes the bug.

You have to specifcy in your composer json the key `conflict`.

Try this: maybe it will solve your problem:

```json
"conflict": {
        "nikic/php-parser": "4.6.0"
    }
```

**Comment by TomasVotruba** [comment] 2020-07-26 16:17
Resolved by https://github.com/rectorphp/rector/pull/3788

**Closed by TomasVotruba** 2020-07-26 16:17 UTC
