### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by CosaroLisa** [rectorphp/rector#8361] opened 2023-12-14 12:06 UTC
Running with php 7.4 and
```
"require-dev": {
        "symplify/easy-coding-standard": "12.*",
        "phpstan/phpstan": ">1.10",
        "phpstan/extension-installer": ">1.3",
        "rector/rector": "0.18.6",
        "tomasvotruba/type-coverage": ">0.2",
        "tomasvotruba/cognitive-complexity": ">0.1"
    },
```
I get 
<img width="528" alt="Screenshot 2023-12-14 130440" src="https://github.com/rectorphp/rector/assets/113430756/9ea46b2e-adb3-40ec-9806-1cbe9730a51c">
This only happens for  versions higher than 0.18.6.

**Comment by TomasVotruba** [comment] 2023-12-14 13:44
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment] 2023-12-14 14:07
It seems you're using windows, just copy paste the error, the solution is probably on stackoverflow already https://stackoverflow.com/questions/24782826/the-filename-directory-name-or-volume-label-syntax-is-incorrect-inside-batch

**Comment by scollovati** [comment] 2023-12-15 10:43
Seems that this exception on Windows with XDEBUG active.
In fact, this exception is related to this LOC change in `XdebugHandler.php` (that is loaded in the source code of Rector rather then via Composer): https://github.com/rectorphp/rector/commit/45987b0066a8b17f7d6504d1ae6cba0793304e1c#diff-27a6b916747c306f2a8c14d3ebcaeb25ecf6e4359daeb4541f0277712dd1a40c

This change has been introduced in v0.18.6, and still present on 0.18.12.

So it's not related to the SO page attached.

**Comment by samsonasik** [comment] 2023-12-15 10:58
This probably related with PR:

- https://github.com/rectorphp/rector-downgrade-php/pull/199

@garas could you verify with relevancy? Thank you.

**Comment by garas** [comment] 2023-12-15 13:26
I'm unable to reproduce issue. Rector runs fine on Windows.

Do you still get same error if you allow Xdebug with `.\vendor\bin\rector  --xdebug`?

**Comment by scollovati** [comment] 2023-12-15 16:57
@garas it works super super slowly. I cannot even perform a search on a project with 16 files in a reasonable time. 
The point is that until version 18.5 it was possible to leave XDebug ready for web debugging (by using a dedicated cookie) in PHP.ini (`xdebug.mode = develop,debug`), while not creating any issue in Rector. 

As said above, the source code of that helper library is different from the one that you have. Don't know if an updated version may solve the issue.

**Comment by scollovati** [comment] 2023-12-15 17:03
According to my analysis, the issue lies here https://github.com/rectorphp/rector-downgrade-php/pull/199. 

`escapeshellarg` behaves very differently on Linux and Windows. Typically, the native function does not work in a naive way under Windows, and it creates issues in a lot of contexts. The community suggests to implement a dedicated function for Windows environments. References here:
- (good comment in official PHP Docs) https://www.php.net/manual/en/function.escapeshellarg.php#123718
- https://stackoverflow.com/questions/58519037/how-do-i-use-escapeshellarg-on-windows-but-aimed-for-linux-and-vice-versa

**Comment by samsonasik** [comment] 2023-12-15 17:37
@scollovati based on php manual comment, is changing with something like:

```diff
-$process = \proc_open(\is_array($cmd) ? \implode(' ', \array_map('escapeshellarg', $cmd)) : $cmd, [], $pipes);
+$process = \proc_open(\is_array($cmd) ? \implode(' ', \array_map(
+         function($path) {
+              return '"' . addcslashes($path, '\\"') . '"';
+         }, $cmd)) : $cmd, [], $pipes);
```

is working? It is unfortunately that we don't have windows env for testing and example code that produce the error. If you can provide a github repo with github action for windows, that would be great to test and fix together.

**Comment by scollovati** [comment] 2023-12-19 08:10
Not working either. I've manually changed the LOC to go back to [the previous version](https://github.com/rectorphp/rector/commit/45987b0066a8b17f7d6504d1ae6cba0793304e1c#diff-27a6b916747c306f2a8c14d3ebcaeb25ecf6e4359daeb4541f0277712dd1a40c) and it works.
Same said by using the official package here https://github.com/composer/xdebug-handler/blob/main/src/XdebugHandler.php#L298

**Comment by samsonasik** [comment] 2023-12-23 16:58
We need a reproducible repo, with github action for windows, so we can fix together, otherwise, it is just guessing and cause old bug show again.

@scollovati I am closing it, feel free to create new issue when you have a chance to create reproducible repo for it, as @garas unable to reproduce it.

**Closed by samsonasik** 2023-12-23 16:58 UTC
