### ISSUE TITLE
v1.1.0 is running 8x slower than v1.0.4

### ISSUE THREAD

**Issue by chescos** [rectorphp/rector#8679] opened 2024-06-20 20:17 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.1.0             |

I'm running Rector on a larger project (660 processed files). Performance downgraded significantly starting with v1.0.5. Here are the measured times per version:

| Version        | Time                                                         |
| :------------- | :---------------------------------------------------------------|
| v1.0.3 | 2 minutes |
| v1.0.4 | 2 minutes |
| v1.0.5 | 21 minutes |
| v1.1.0 | 16 minutes |

**Comment by samsonasik** [comment] 2024-06-20 22:59
That may be due to phpstan 1.11.x, see issue

- https://github.com/rectorphp/rector/issues/8638 

I tested on rector-src code base with 2180 files, and it only took 37 seconds on 8 core, and 1.5 to 2 minutes on 2 cores.

If you can share the source, we may probably can look up the bottlenect, but that may mostly on PHPStan internal as I guess...

If you can't share the reproducible code, try narrow down rules half by half until it found the minimal rule(s) that cause it,
and the expected output.

Read this post: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by TomasVotruba** [comment] 2024-06-21 01:20
Reopening to have this in attention. We should address this clearly.

**Comment by TomasVotruba** [comment] 2024-06-21 07:46
Thanks everyone for patience to all :pray:  I'm now travelling and connection is sometime challange to get here. I know I should have check this more deeply sooner.

Resolved in https://github.com/rectorphp/rector-src/pull/5995

**Closed by TomasVotruba** 2024-06-21 07:46 UTC
Labels: bug
