### ISSUE TITLE
AnnotationToAttributeRector not applied

### ISSUE THREAD

**Issue by vichanse** [rectorphp/rector#5517] opened 2021-02-12 06:51 UTC
# Question
I can't get the AnnotationToAttributeRector being applied on my code
I reproduced the behaviours here
https://getrector.org/demo/138439e7-e2cf-4fed-94de-4b83bbe51f77

What am i doing wrong?

I'm using rector-prefixed as i'm unable to run rector with php8. I have the Rector SymfonyConsole class not found error

**Comment by TomasVotruba** [comment] 2021-02-12 11:36
Hi,

this one is a bit tricky, because it requires symfony/framework-bundle of version 5.2 to be installed.

The demo only uses code that you paste in it. The `@Route` class is not be present, so the result is expected.

You have to either complete it, or better provide example on Github repository

**Comment by 7system7** [comment] 2021-02-15 16:56
Hello,

I have the same issue. It is a freshly created symfony 5.2.x project, I have a User entity in `src/Entity`:

```php
<?php
...

/**
 * Class User
 *
 * @ApiResource
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @Gedmo\Loggable
 */
class User implements UserInterface, Timestampable

...
```

I have a rector php file:

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php80\Rector\Class_\AnnotationToAttributeRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // paths to refactor; solid alternative to CLI arguments
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
    ]);

    // Define what rule sets will be applied
    $parameters
        ->set(Option::SETS, [
            SetList::PHP_80,
            SetList::SYMFONY_52,
            SetList::SYMFONY_AUTOWIRE,
            SetList::SYMFONY_CODE_QUALITY,
        ])
        ->set(Option::AUTOLOAD_PATHS, [
            __DIR__ . '/vendor/autoload.php',
        ]);

    // get services (needed for register a single rule)
    $services = $containerConfigurator->services();

    $services->set(AnnotationToAttributeRector::class);
};
```

I run rector w/ this `$ php8.0 vendor/bin/rector process` (I have multiple php versions on the system.)

**After that nothing happened w/ the User entity's annotations. What am i doing wrong?**

**Comment by TomasVotruba** [comment] 2021-02-15 19:34
Hi, whas is the expected behavior? 
We'll need a failing repository on Github to verify

**Comment by 7system7** [comment] 2021-02-15 19:42
I think the entity should look like this, after the process:

```php
/**
 * Class User
 */
 #[ApiResource]
 #[Gedmo\Loggable]
 #[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, Timestampable
{
...
}
```

... if I am not wrong. :)

**Comment by TomasVotruba** [comment] 2021-02-15 19:56
I see :) Could you provide links to Attribute classes on Github?

AFAIK Doctrine does not provide attributes yet.

If that's wrong, we'll add support for them :+1: But we need exact existing classes with `#[Attribute]`

**Comment by aless673** [comment] 2021-02-19 20:12
Hi, here the diff produced by Rector with `AnnotationToAttributeRector` rule : 

```
      * @ORM\Column(name="email", type="string", length=180, unique=true, nullable=true)
      * @Assert\Type("string")
      * @Assert\Length(max="180")
-     * @Assert\Email(groups={"registration"})
      * @Assert\NotNull(groups={"registration"})
      */
+    #[\Symfony\Component\Validator\Constraints\Email(groups: ['registration'])]
     private $email;
```

This is not working correctly, as you can see only the assert Email annotation is handled and nothing else.

**Comment by TomasVotruba** [comment] 2021-02-19 20:39
I see. We'll need a failing fixture for `AnnotationToAttributeRectorTest` to be able to fix it.
Here is how you can add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by OskarStark** [comment] 2021-02-23 08:48
I have the same problem with the following entity:
```php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Domain\Identifier\UserId;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`users`")
 * @UniqueEntity(fields={"email"}, message="Es existiert bereits ein Account mit dieser Email")
 */
class User implements UserInterface
{
```

So `@UniqueEntity` should be replaced by an Attribute

I already use Symfony 5.2 which includes:
```php
namespace Symfony\Bridge\Doctrine\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * Constraint for the Unique Entity validator.
 *
 * @Annotation
 * @Target({"CLASS", "ANNOTATION"})
 *
 * @author Benjamin Eberlei <kontakt@beberlei.de>
 */
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
class UniqueEntity extends Constraint
{
```

**Comment by OskarStark** [comment] 2021-02-23 08:53
> AFAIK Doctrine does not provide attributes yet.

@TomasVotruba In this case the example should not show ORM as example in: 
https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#annotationtoattributerector

😃

**Comment by TomasVotruba** [comment] 2021-02-23 10:08
> @OskarStark I have the same problem with the following entity:

We'll need a test case for that.

**Comment by TomasVotruba** [comment] 2021-02-23 10:08
> @TomasVotruba In this case the example should not show ORM as example in:

Good point 🙂 could you sent PR with fix?

**Comment by OskarStark** [comment] 2021-02-23 12:04
Sure, shall I update the README file or is it located somewhere else and generated afterwards?

**Comment by TomasVotruba** [comment] 2021-02-23 12:05
In the rule itself, there is a code sample that docs is generated from

**Comment by TomasVotruba** [comment] 2021-02-27 13:29
It seems the problem is in prefixed version only: https://github.com/rectorphp/rector-prefixed/blob/dee8c1207c4d0d94ce59867545bbe29efcfa72fa/packages/better-php-doc-parser/src/ValueObject/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php#L20

Here the class should be skipped

**Comment by OskarStark** [comment] 2021-03-17 10:17
What do you mean? Which class should be skipped? 🤔

**Comment by TomasVotruba** [comment] 2021-03-17 11:29
The linked line:

```diff
    /**
     * @var string
     */
-   public const CLASS_NAME = \RectorPrefix20210227\Symfony\Component\Routing\Annotation\Route::class;
+   public const CLASS_NAME = \Symfony\Component\Routing\Annotation\Route::class;
```

Scoper is now prefixing it, but it should be skipped

**Comment by OskarStark** [comment] 2021-03-17 12:10
Ah, yes that makes sense

**Comment by TomasVotruba** [comment] 2021-03-17 18:23
This is fixed on `rector/rector-prefixed` `dev-main`: https://github.com/rectorphp/rector-prefixed/blob/7372fd08156d0ad34824041dd483420dcaa61438/packages/BetterPhpDocParser/ValueObject/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php#L19

**Closed** 2021-03-20 23:16 UTC

**Comment by TomasVotruba** [comment] 2021-03-21 11:51
The thign is, the route class must be present there:

I've updated the demo link and the migration now works as expected:
https://getrector.org/demo/9b0bc64e-38f4-4fa9-8925-09e3fc456738

Also note, the SYMFONY_52 set must be used, as both framework and PHP versoin is relevant. PHP 8 on Symfony 5.1 would not work.

<br><br>

I've also added test workflow to rector-prefixed and it works there too :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/924196/111903725-ec7d2b00-8a43-11eb-8c53-325cc26b5942.png)

**Comment by OskarStark** [comment] 2021-03-21 16:11
Nice thank you for the clarification 👌🏻
