### ISSUE TITLE
PhpParser\NodeTraverser::traverse() -> must be of the type array

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#922] opened 2019-01-02 00:19 UTC
error:
```
[ERROR] Could not process "/home/lmoelleken/testing/git/portable-utf8/tests/Utf8GlobalTest.php" file, due to:          
         "Argument 1 passed to PhpParser\NodeTraverser::traverse() must be of the type array, null given, called in     
         /home/lmoelleken/testing/git/portable-utf8/vendor/rector/rector/src/Application/FileProcessor.php on line 102".
```

command:
```
vendor/bin/rector process tests --level phpunit-yield-data-provider
```

**Comment by voku** [comment] 2019-01-02 22:15
Comes "also" from Invalid Sequence Identifier ...

```php
   public function testStripTags()
    {
        $tests = [
            "<span>κόσμε\xa0\xa1</span>-<span>öäü</span>öäü" => 'κόσμε-öäüöäü',
        ];

        foreach ($tests as $before => $after) {
            static::assertSame($after, strip_tags($before));
        }
    }
```


... so I think it's more my very special use-case for testing invalid UTF-8 chars? Close this issue, also?

**Comment by TomasVotruba** [comment] 2019-01-02 23:49
Probably duplicate of #921

**Closed by TomasVotruba** 2019-01-02 23:49 UTC
Labels: Bug
