### ISSUE TITLE
locked "nikic/php-parser": "4.9.0" prevents install

### ISSUE THREAD

**Issue by phazei** [rectorphp/rector#4251] opened 2020-09-17 20:44 UTC
I have a dependency that has "nikic/php-parser" v4.9.1 locked in, so it won't install

```
Problem 1
    - Can only install one of: nikic/php-parser[v4.9.1, v4.9.0].
    - Can only install one of: nikic/php-parser[v4.9.0, v4.9.1].
    - Can only install one of: nikic/php-parser[v4.9.0, v4.9.1].
    - rector/rector v0.8.7 requires nikic/php-parser 4.9.0 -> satisfiable by nikic/php-parser[v4.9.0].
    - Installation request for rector/rector ^0.8.7 -> satisfiable by rector/rector[v0.8.7].
    - Installation request for nikic/php-parser (locked at v4.9.1) -> satisfiable by nikic/php-parser[v4.9.1].
```

Any reason it can't be "^4.9" in the composer.json instead of the "4.9.1" that's there?

**Comment by TomasVotruba** [comment] 2020-09-17 21:52
Duplicate of https://github.com/rectorphp/rector/issues/4198

**Closed by TomasVotruba** 2020-09-17 21:52 UTC
