### ISSUE TITLE
Inject services in class

### ISSUE THREAD

**Issue by dannyvw** [rectorphp/rector#8115] opened 2023-08-04 11:12 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.17.1            |

In release 0.17.1 autowiring array parameters is removed (https://github.com/rectorphp/rector-src/pull/4186/files). Now custom classes no longer get the services injected. I tried it will the configuration below but the argument is always empty. Is there something wrong with this configuration?

## Minimal PHP Code Causing Issue

```php
return static function (RectorConfig $rectorConfig): void {
    $services = $rectorConfig->services();

    $services->set(SomeCustomClass::class)->tag(SomeInterface::class); 

    $services->instanceof(SomeInterface::class)->tag(SomeInterface::class);
    $services->set(CustomProcessor::class)->arg('$rectors', tagged_iterator(SomeInterface::class));
};
```

## Expected Behaviour

Services should be injected in the class.

**Comment by TomasVotruba** [comment] 2023-08-04 11:20
Afaik, there is a bug with instanceof and tag combination in Symfony DI, so this doesn't work as expected:

```php
$services->instanceof(SomeInterface::class)->tag(SomeInterface::class);
```

The tagging should work though, as that's how we pass `RectorInterface` collection and other tagged services:
https://github.com/rectorphp/rector-src/blob/3b9c2f1b533fc9b8c600c6fcbd2f152eb9403a72/config/config.php#L276-L326

What exactly is your goal?

**Comment by dannyvw** [comment] 2023-08-04 11:25
We have some custom FileProcessors and we need to inject services with an specific interface to this class so we can loop through all given services.

This https://github.com/rectorphp/rector-src/blob/3b9c2f1b533fc9b8c600c6fcbd2f152eb9403a72/config/config.php#L276-L326 is what I tried to configure but it looks like services don't get tagged.

**Comment by TomasVotruba** [comment] 2023-08-04 12:16
Using `FileProcessorInterface::class` tag should be enough: https://github.com/rectorphp/rector-src/blob/3b9c2f1b533fc9b8c600c6fcbd2f152eb9403a72/config/config.php#L319-L320

Be sure to make use of autowire/autoconfigure/public too, as not sure how Symfony handles multiple configs.

If that doesn't help, please make a minimal reproducer repository on Github. I'll check it

**Comment by samsonasik** [comment] 2023-08-04 12:20
@dannyvw you may need to configure:

```php
    $rectorConfig->services()->set(MyFileProcessor::class)->tag(FileProcessorInterface::class);
```

it is like how custom NodeVisitor documented with set and tagging with interface https://getrector.com/documentation/creating-a-node-visitor

**Comment by TomasVotruba** [comment] 2023-08-04 13:02
We'll need a reproducible repository to be able to help.

**Comment by dannyvw** [comment] 2023-08-04 13:55
@TomasVotruba See https://github.com/dannyvw/rector-issue. I used the same classes as in the issue. Hopefully this helps to clarify the issue.

**Comment by samsonasik** [comment] 2023-08-04 14:17
@dannyvw you need to set `instanceof()` before `load()`, like this:

```php
    $services->instanceof(CustomInterface::class)->tag(CustomInterface::class);
    $services->load('App\\', __DIR__ . '/src');

    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);
    $rectorConfig->sets([\Rector\Set\ValueObject\SetList::DEAD_CODE]);

    // Lines below not configured before rector 0.17.1
    $services->set(CustomProcessor::class)->arg('$rectors', tagged_iterator(CustomInterface::class));
```

**Comment by samsonasik** [comment] 2023-08-04 14:19
@dannyvw I create a PR https://github.com/dannyvw/rector-issue/pull/1 for that :)

**Comment by samsonasik** [comment] 2023-08-04 14:36
@dannyvw with above found solution, feel free to add documentation PR to https://github.com/rectorphp/getrector-com, this should need to be filled in 2 locations paths:

- https://github.com/rectorphp/getrector-com/tree/main/resources/docs
- https://github.com/rectorphp/getrector-com/blob/main/src/Documentation/DocumentationMenuFactory.php

**Comment by dannyvw** [comment] 2023-08-04 15:18
@samsonasik I hadn't tried that yet. Thanks!

**Comment by samsonasik** [comment] 2023-08-04 15:21
no worries, we need more documentation, feel free to create PR documentation when you have a chance  :)

**Comment by TomasVotruba** [comment] 2023-08-12 17:19
Circling back to this issue. After back and forht thinking, we're moving Rector to php-only refactoring past week: https://github.com/rectorphp/rector-src/pull/4761

How do you

**Comment by samsonasik** [comment] 2023-08-12 17:32
@TomasVotruba keeping `FileProcessorInterface` is reasonable for me, for usecase, we can look to how @sabbelasichon in his typo3-rector 

https://github.com/sabbelasichon/typo3-rector/blob/main/src/FileProcessor/TypoScript/TypoScriptFileProcessor.php

**Comment by TomasVotruba** [comment] 2023-08-12 18:35
@samsonasik I'm aware of those, but that's the only case. Also, Rector should handle PHP files, not configs/templates. The rest should be another tool, or custom script. E.g. regexes in templates/configs should only load info from `rector.php`, but work standalone. We might come up with such a standalone tool later :)

**Comment by samsonasik** [comment] 2023-08-13 04:45
@TomasVotruba updating config service from Symfony DI to Laravel DI just need documentation for how to register service, and I think user will be easy to migrate.

Marking `FileProcessorInterface` as `@internal` is ok, but migrating the existing code will be very task demanding, we don't responsible for what issue will come with custom processor, but the support is there to user that rely to the rector cli command.

The issue is equal for what PHPStan Printer final class, that user can't extends, and no interface to apply different logic per use case that force us to not use that, due to Spaceless node usage, see:

- https://github.com/phpstan/phpdoc-parser/pull/206

BC break is ok, as far as there is still option open.

**Comment by dannyvw** [comment] 2023-08-13 10:05
@TomasVotruba We are using it for processing some other file extensions. We have a search and replace processor to replace basic strings inside yaml/twig/scss files.

**Comment by TomasVotruba** [comment] 2023-08-13 10:16
@dannyvw These should be part of another standalone tool in the future in form of file finder + regex.
What else would you need to run it?

**Comment by dannyvw** [comment] 2023-08-13 10:27
@TomasVotruba Yes we can move it to another tool if it does not working anymore with the setup we now have. But I see that the FileProcessorInterface is not removed, so it is possible that our case is still working. I will check that later if everything is released.

**Comment by TomasVotruba** [comment] 2023-08-16 18:59
@dannyvw I've merged the Laravel container yesterday so you can try :+1: 

But the `FileProcessorInterface` will be deprecated this or next month, so better move it to your own package.

Closing as answered.

**Closed by TomasVotruba** 2023-08-16 18:59 UTC
Labels: docs
