### ISSUE TITLE
`StrictArrayParamDimFetchRector` assumes everything is an array while it can be `ArrayAccess`

### ISSUE THREAD

**Issue by RobertMe** [rectorphp/rector#8409] opened 2024-01-17 11:38 UTC
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.19.0      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a9b7d0bf-c5fa-4d77-b87a-a923c83c748a

```php
<?php

function test($data)
{
    $foo = $data['foo'];
    var_dump($foo);
}

test(new ArrayObject(['foo' => 'bar']));
```

### Responsible rules

* `StrictArrayParamDimFetchRector`

## Expected Behavior

In this case no `array` typehint should be set, because the actua passed param is an instance of `ArrayObject` (/implements `ArrayAccess`).
The original code works fine: https://3v4l.org/RbY8B
The result of Rector doesn't: https://3v4l.org/cWK1Z

Based on "Rector should only make changes of which it is confident" I would actually say that this rule "can't exist". Because a "dim fetch" operation can happen on more types / things than only an array so there is absolutely no guarantee that the variable would actually be an array / must be an array.

**Comment by RobertMe** [comment] 2024-01-17 11:44
For the record: I do like the rule, and it also made some proper changes. But it also made changes that are wrong (because something implementing `ArrayAccess` is passed). And as stated I do believe the "motto" of Rector is to not "make changes that could potentially break the code". While this rule can clearly give (a lot) of false positives.

**Comment by samsonasik** [comment] 2024-01-20 23:56
I think add `array|ArrayAccess` can be too much for many projects, while checking its usage can be performance drawback, you can skip it for your project.

 There is already `AddMethodCallBasedStrictParamTypeRector` already which may suitable for most use cases, while need improvement for narrowing exactly different type as you write on different issue

- https://github.com/rectorphp/rector/issues/8406

**Comment by samsonasik** [comment] 2024-02-15 08:12
`StrictArrayParamDimFetchRector` is now executed on last on type declaration list, so executed after external call detection on latest `rector/rector:dev-main`, see PR:

- https://github.com/rectorphp/rector-src/pull/5618

if the issue still happen, you can skip the rule as it consider risky rule. I am closing it,

**Closed by samsonasik** 2024-02-15 08:12 UTC
Labels: bug

**Comment by DvDty** [comment] 2025-06-15 23:11
> `StrictArrayParamDimFetchRector` is now executed on last on type declaration list, so executed after external call detection on latest `rector/rector:dev-main`, see PR:
> 
> * [Move StrictArrayParamDimFetchRector and StrictStringParamConcatRector to last rules on TypeDeclarationLevel rector-src#5618](https://github.com/rectorphp/rector-src/pull/5618)
> 
> if the issue still happen, you can skip the rule as it consider risky rule. I am closing it,

This can be reproduced:

```php
<?php

class Collection implements ArrayAccess
{
    public array $container = [];

    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }
}

class Service
{
    public function run($param)
    {
        return $param['key'];
    }
}

echo (new Service())->run(new Collection());
```

```php
<?php

use Rector\Config\RectorConfig;

return RectorConfig::configure()->withPreparedSets(typeDeclarations: true);
```

```diff
class Service
{
-    public function run($param)
+    public function run(array $param)
```

Ypu mentioned this is "consider risky rule", which is understandable. Are those categorized/flaged somewhere? Can I disable all risky rules at once?

**Comment by samsonasik** [comment] 2025-06-16 05:50
For now, we don't categorize risky rules in specific set due to it can be depends on what kind of codebase, that can be usefull on many project, but on very specific niche usage, it risky, you can skip the rule on specific path for your specific usecase.
