### ISSUE TITLE
Incorrect behavior of RemoveUnusedPrivateMethodRector

### ISSUE THREAD

**Issue by bertrandjamin** [rectorphp/rector#6613] opened 2021-08-04 10:20 UTC
# Bug Report

The rule `RemoveUnusedPrivateMethodRector` don't handle correctly abstract private functions in a trait.

ℹ️ This a new PHP8 capability : https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.abstract.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ebf50d7-992f-63ba-9a8a-bd39c81b9232

```php
<?php

trait MyTrait
{
    abstract private function privateMethod();
        
    public function publicMethod() {
        $this->privateMethod();
    }
}

class MyClass
{
    use MyTrait;

    private function privateMethod()
    {
        //code
    }

}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

As the abstract `privateMethod` is used in `publicMethod` the rule should not remove the `privateMethod` implementation in `MyClass`

Thanks for your help

**Comment by TomasVotruba** [comment] 2021-08-04 10:27
Thank you for your report and demo link!

Could you send a failing test case in a pull-request, so we have it covered in Rector?
Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by Bl00D4NGEL** [comment] 2021-08-06 08:35
@bertrandjamin the issue is now fixed.

Given that the abstract private function is PHP 8.0+ we should probably consider writing a downgrade rector for that, since I didn't find any in the [PHP 8.0 downgrades](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#downgradephp80)., right @TomasVotruba?

**Comment by bertrandjamin** [comment] 2021-08-06 08:42
@Bl00D4NGEL thanks ! 
I have planned to work on it in few days but you were faster than me :)

I let you or @TomasVotruba close the issue according to his answer.

**Comment by bertrandjamin** [comment] 2021-08-06 08:54
@Bl00D4NGEL  after reading your PR I have a question about https://github.com/Bl00D4NGEL/rector-src/blob/06b4aef9aa4607df84ea7f37fa641809ac0b503c/rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/remove_if_method_non_abstract_private_in_trait.php.inc

Given the php documentation (https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.precedence) a method in the class can override the one created in the trait. 
So it seems that this Fixture breaks functional code.

am I missing something ?

**Comment by Bl00D4NGEL** [comment] 2021-08-06 09:25
@bertrandjamin you would be correct. I tested it in the PHPSandbox: http://sandbox.onlinephpfunctions.com/code/fa84c5aaa7ca8433d7b7e486a82bc678f21aaac7 and it seems like you actually can overwrite the private function, my bad there. 
Is this worth a new issue or should this be fixed within this issue @TomasVotruba ?

**Comment by TomasVotruba** [comment] 2021-08-06 10:14
@Bl00D4NGEL  I think you can fix it here, as it's closely related.

**Comment by samsonasik** [comment] 2021-08-09 04:06
It seems already fixed, closing.

**Closed by samsonasik** 2021-08-09 04:06 UTC
Labels: bug
