### ISSUE TITLE
Could not process "/home/pdavie/src2/html/includes/HTML/QuickForm/Rule/Compare.php"

### ISSUE THREAD

**Issue by pdavie** [rectorphp/rector#8682] opened 2024-06-22 11:24 UTC
I have inherited a horrendous old codebase and am trying to migrate it to PHP 8.3 (don't know if I am on a fool's errand)...  I have attached the problem file and the rector config file.

[rector.php.txt](https://github.com/user-attachments/files/15936284/rector.php.txt)
[Compare.php.txt](https://github.com/user-attachments/files/15936285/Compare.php.txt)

[ERROR] Could not process "/home/pdavie/src2/html/includes/HTML/QuickForm/Rule/Compare.php" file, due to:              
         "System error: "Syntax error, unexpected T_VARIABLE, expecting ';'1"                                           
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(146):                         
         PhpParser\ParserAbstract->doParse()                                                                            
         #1 vendor/rector/rector/src/PhpParser/Parser/SimplePhpParser.php(55): PhpParser\ParserAbstract->parse()        
         #2 vendor/rector/rector/src/PhpParser/Parser/InlineCodeParser.php(133):                                        
         Rector\PhpParser\Parser\SimplePhpParser->parseString()                                                         
         #3 vendor/rector/rector/src/PhpParser/Parser/InlineCodeParser.php(103):                                        
         Rector\PhpParser\Parser\InlineCodeParser->parseCode()                                                          
         #4 vendor/rector/rector/rules/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector.php(150):          
         Rector\PhpParser\Parser\InlineCodeParser->parseString()                                                        
         #5 vendor/rector/rector/rules/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector.php(109):          
         Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector->parseStringToBody()                      
         #6 vendor/rector/rector/src/Rector/AbstractRector.php(139):                                                    
         Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector->refactor()                               
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Rector\AbstractRector->enterNode()                                                                      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #19 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #20 vendor/rector/rector/src/Application/FileProcessor.php(110):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                                 
         #21 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(204):                                    
         Rector\Application\FileProcessor->processFile()                                                                
         #22 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(159):                                    
         Rector\Application\ApplicationFileProcessor->processFile()                                                     
         #23 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(136):                                    
         Rector\Application\ApplicationFileProcessor->processFiles()                                                    
         #24 vendor/rector/rector/src/Console/Command/ProcessCommand.php(117):                                          
         Rector\Application\ApplicationFileProcessor->run()                                                             
         #25 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\ProcessCommand->execute()                                                               
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202406\Symfony\Component\Console\Command\Command->run()                                            
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202406\Symfony\Component\Console\Application->doRunCommand()                                       
         #28 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202406\Symfony\Component\Console\Application->doRun()                                              
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun()                                                                     
         #30 vendor/rector/rector/bin/rector.php(130): RectorPrefix202406\Symfony\Component\Console\Application->run()  
         #31 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #32 vendor/bin/rector(119): include('...')                                                                     
         #33 {main}". On line: 272

**Comment by samsonasik** [comment] 2024-06-22 12:18
Reproduced by rule: `CreateFunctionToAnonymousFunctionRector`  https://getrector.com/demo/237e03d7-965e-4c13-906c-b520e160d51b

**Comment by samsonasik** [comment] 2024-06-22 13:51
@pdavie I am looking for fix, this may take time to fix, for now, you can replace create_function with anonymous function like this diff:

```diff
         $operator = $this->_findOperator($operator);
         if ('===' != $operator && '!==' != $operator) {
-            $compareFn = create_function('$a, $b', 'return floatval($a) ' . $operator . ' floatval($b);');
+            $compareFn = function ($a, $b) use ($operator) {
+                return floatval($a) . $operator . floatval($b);
+            };
         } else {
-            $compareFn = create_function('$a, $b', 'return strval($a) ' . $operator . ' strval($b);');
+            $compareFn = function ($a, $b) use ($operator) {
+                return strval($a) . $operator . strval($b);
+            };
         }
```

thank you for understanding.

**Comment by samsonasik** [comment] 2024-06-24 02:38
It seems cause different result, see

- php 7.1 create_function  https://3v4l.org/GdOs2#v7.1.33 result is `3`
- php 7.2+ closure: https://3v4l.org/TVLbM result is "1+2"

the real value of `$operator` seems needs to be appended, 

Re-open for more investigation.

**Comment by samsonasik** [comment] 2024-06-24 02:48
using `eval()` seems can be solution, since `$operator` is dynamic https://3v4l.org/Mm9PN

**Comment by samsonasik** [comment] 2024-06-24 03:05
the solution for now you may need to manually do with `eval()`, while I guess that discourages

```diff
         $operator = $this->_findOperator($operator);
         if ('===' != $operator && '!==' != $operator) {
-            $compareFn = create_function('$a, $b', 'return floatval($a) ' . $operator . ' floatval($b);');
+            $compareFn = function ($a, $b) use ($operator) {
+                return eval("return floatval(\$a) $operator floatval(\$b);");
+            };
         } else {
-            $compareFn = create_function('$a, $b', 'return strval($a) ' . $operator . ' strval($b);');
+            $compareFn = function ($a, $b) use ($operator) {
+                return eval("return strval(\$a) $operator strval(\$b);");
+            };
         }
```

or use switch case code based on `$operator` value, something like:

```php
$compareFn = function ($a, $b) use ($operator) {
    switch ($operator) {
        case '+':
            return floatval($a) + floatval($b);
        case '-':
            return floatval($a) - floatval($b);
        case '*':
            return floatval($a) * floatval($b);
        case '/':
            return floatval($a) / floatval($b);
        default:
            throw new InvalidArgumentException("Unsupported operator: $operator");
    }
};

var_dump($compareFn(1, 2));

```

**Comment by samsonasik** [comment] 2024-06-27 08:34
I am closing it as it should be handled manually, as above noted.

**Closed by samsonasik** 2024-06-27 08:34 UTC
Labels: bug
