### ISSUE TITLE
PropertyTypeDeclarationRector reports wrong type

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#2521] opened 2019-12-29 14:01 UTC
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.6.4          |
| PHP version    | PHP 7.3                           |
| Full Command   | `rector process redaxo/src/core/lib --autoload-file phpstan-bootstrap.php`  | 

## Current Behaviour 

running rector thru https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/util/stream.php leads to a `$nextContent` phpdoc of type `mixed[]`

![image](https://user-images.githubusercontent.com/120441/71557835-0cde5580-2a4c-11ea-9d62-2a7919c753ac.png)

I would expect a `string[]` type

using rector.yaml:
```
# rector.yaml
services:
    Rector\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector: ~
```

**Comment by TomasVotruba** [comment] 2019-12-29 15:11
How do you deduce variable is always string?

**Comment by staabm** [comment] 2019-12-29 17:36
The only occurence where we write the property uses a string argument
https://github.com/redaxo/redaxo/blob/f30a0a6d669481b2789ecbfb21924185adbf2849/redaxo/src/core/lib/util/stream.php#L72

All other related codes are readonly accesses

**Comment by TomasVotruba** [comment] 2019-12-29 19:19
Do you use fixed version of Rector?

**Comment by staabm** [comment] 2019-12-29 20:29
I used the latest dev-master (from somewhen today)

**Comment by TomasVotruba** [comment] 2019-12-29 20:41
Please add test case, so we have it covered

**Comment by TomasVotruba** [comment] 2020-01-11 00:21
Closing as unable to reproduce.

**Closed by TomasVotruba** 2020-01-11 00:21 UTC
