### ISSUE TITLE
Rector prefixed 0.8.56: Class 'Rector\Core\Console\Style\SymfonyStyleFactory' not found

### ISSUE THREAD

**Issue by simivar** [rectorphp/rector#4736] opened 2020-11-30 09:35 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.56             |
| Installed as   | prefixed Rector PHAR                      |

While trying to run a Rector with `vendor/bin/rector` there's an error happening:
```
❯ vendor/bin/rector
PHP Fatal error:  Uncaught Error: Class 'Rector\Core\Console\Style\SymfonyStyleFactory' not found in /Users/[...]/vendor/rector/rector-prefixed/bin/rector:39
Stack trace:
#0 {main}
  thrown in /Users/[...]/vendor/rector/rector-prefixed/bin/rector on line 39
Fatal error: Uncaught Error: Class 'Rector\Core\Console\Style\SymfonyStyleFactory' not found in /Users/[...]/vendor/rector/rector-prefixed/bin/rector:39
Stack trace:
#0 {main}
  thrown in /Users/[...]vendor/rector/rector-prefixed/bin/rector on line 39

```

## Expected Behaviour

Rector running properly.

**Comment by simivar** [comment] 2020-11-30 09:36
I've seen @michaljusiega comment in #4606 but I feel like this is a separate issue not related to PHPStan. I came across that comment by luck and feel that a separate ticket will be easier to find and track for others so they know when the issue is fixed.

**Comment by michaljusiega** [comment] 2020-11-30 09:38
No, is not related to PHPStan issue.

**Comment by staabm** [comment] 2020-11-30 17:06
duplicates https://github.com/rectorphp/rector/issues/4725

**Comment by simivar** [comment] 2020-11-30 17:55
It doesn't duplicates #4725 as I have it installed as a normal Composer dependency, not a global one.

**Comment by staabm** [comment] 2020-11-30 18:42
Sorry „duplicates“ was the wrong wording. It seems to be the same error though :)

**Comment by bbouabou** [comment] 2020-12-07 18:02
Hello,

Did there is any workaround to use rector to upgrade a symfony 2.8  project ?

**Comment by simivar** [comment] 2020-12-07 18:52
@TomasVotruba could you help us with this issue?

**Comment by TomasVotruba** [comment] 2020-12-07 19:04
@simivar Basically, this PR needs to be finished. The fix is included: https://github.com/rectorphp/rector/pull/4559
I'm busy with other work, so no ETA on it. Any help is welcomed there.

**Comment by arnaud-fr** [comment] 2020-12-08 07:30
> 
> 
> Hello,
> 
> Did there is any workaround to use rector to upgrade a symfony 2.8 project ?

A suggested workaround : use the previous version 0.8.52 wich is based on a phar.

If you current environment contains version 0.8.56, first of all remove it : 
_composer remove rector/rector-prefixed._

Then install the previous version :
_composer require rector/rector-prefixed 0.8.52_

_Note : the command init does not work in this version. You will have to copy the rector.php.dist by hand in your main directory._

**Comment by TomasVotruba** [comment] 2020-12-27 10:46
Resolved by https://github.com/rectorphp/rector/pull/4559

**Closed by TomasVotruba** 2020-12-27 10:46 UTC
Labels: bug, prefixed

**Comment by u01jmg3** [comment] 2021-01-06 16:21
Still seeing this problem on 0.9.5

**Comment by TomasVotruba** [comment] 2021-01-06 18:04
We'll need a reproducible repository to verify

**Comment by Aerendir** [comment] 2021-01-11 14:07
@TomasVotruba , I have the same error, also if I use Bamarni composer bin plugin.

But my repo is public: https://github.com/Aerendir/component-array-writer

It is only one class, so is perfect for debugging...

I'm trying to solve the issue, but I have no idea where to start... Maybe you can having more experience with the issue that seems already happened...

**Comment by Aerendir** [comment] 2021-01-11 14:28
Ok, the first problem seems to be in `vendor/rector/rector/bin/rector.php:104`

```diff
    /**
     * In case Rector is installed as vendor dependency,
     * this autoloads the project vendor/autoload.php, including Rector
     */
    public function autoloadProjectAutoloaderFile(): void
    {
        $this->loadIfExistsAndNotLoadedYet(__DIR__ . '/../../autoload.php');
+        $this->loadIfExistsAndNotLoadedYet(__DIR__ . '/../../../../vendor/autoload.php');
    }
```

As I'm using Bamarni Bin Composer plugin, the hard coded path is not correct as Rector is actually installed in `vendor-bin/phpstan/vendor/rector/rector`.

For this reason we need to go

**Comment by staabm** [comment] 2021-01-11 15:17
it seems the fix is the same as the one I suggested in https://github.com/rectorphp/rector/pull/4726

**Comment by Aerendir** [comment] 2021-01-11 17:40
@staabm , similar, not the same: your attempt was to support global install; mine supports installation through Bamarni Composer Bin, that is anyway at project level...

**Comment by Aerendir** [comment] 2021-01-11 17:49
@TomasVotruba , the problem seems to be in Symplify.

I changed this:

```diff
    /**
     * @param object|string $object
     * @param mixed[] $arguments
     */
-    public function callPrivateMethod($object, string $methodName, array $arguments)
+    public function callPrivateMethod($object, string $methodName, $arguments)
    {
        $this->ensureIsNotNull($object, __METHOD__);

        if (is_string($object)) {
            $reflectionClass = new ReflectionClass($object);
            $object = $reflectionClass->newInstanceWithoutConstructor();
        }

        $methodReflection = $this->createAccessibleMethodReflection($object, $methodName);

+        if ($arguments instanceof ArgvInput) {
+            $arguments = $arguments->getArguments();
+        }

        return $methodReflection->invokeArgs($object, $arguments);
    }
```

But now I have other errors:

```console
Aerendir@Archimede component-array-writer % vendor/bin/rector process --dry-run
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Console\Application::configureIO(), 0 passed and exactly 2 expected in /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/symfony/console/Application.php:880
Stack trace:
#0 [internal function]: Symfony\Component\Console\Application->configureIO()
#1 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php(36): ReflectionMethod->invokeArgs(Object(Symfony\Component\Console\Application), Array)
#2 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/rector/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#4 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/rector/rector/bin/rector(4): require_once('/Users/Aerendir...')
#5 {main}
  thrown in /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/symfony/console/Application.php on line 880
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Console\Application::configureIO(), 0 passed and exactly 2 expected in /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/symfony/console/Application.php:880
Stack trace:
#0 [internal function]: Symfony\Component\Console\Application->configureIO()
#1 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php(36): ReflectionMethod->invokeArgs(Object(Symfony\Component\Console\Application), Array)
#2 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/rector/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#4 /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/rector/rector/bin/rector(4): require_once('/Users/Aerendir...')
#5 {main}
  thrown in /Users/Aerendir/Documents/JooServer/Lab/Components/component-array-writer/vendor-bin/phpstan/vendor/symfony/console/Application.php on line 880
```

The problem seems to be deeper than what it appeared at a first sight.

**Comment by TomasVotruba** [comment] 2021-01-11 18:15
Neither barmani and global installation is supported. If paths will be resolved, the different `vendor` directory name or double nesting or package conflicts will appear.

Prefixed version is way to go here.

**Comment by Aerendir** [comment] 2021-01-11 18:58
@TomasVotruba , so have you any solution to suggest?

**Comment by Aerendir** [comment] 2021-01-11 19:00
Ok, so [Phive](https://github.com/phar-io/phive) to the rescue!

**Comment by Aerendir** [comment] 2021-01-11 19:01
Also if this makes really complex to stay updated as Dependabot doesn't support Phive I think 🤔

**Comment by TomasVotruba** [comment] 2021-01-11 19:12
Phive is packaged phar, that's what we droppped in 0.9 - Why? See https://getrector.org/blog/2020/12/28/rector-09-released#debuggable-rector-prefixed

This is prefixed: https://github.com/rectorphp/rector-prefixed

We go for the future of downgraded and prefixed version. Thank's to that Rector will be able to run on PHP 5.6 in composer and without Docker.
