### ISSUE TITLE
You have requested a non-existent service "Rector\Core\Console\ConsoleApplication"

### ISSUE THREAD

**Issue by svilenmarkov** [rectorphp/rector#4820] opened 2020-12-07 16:41 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | [latest](https://hub.docker.com/layers/rector/rector/latest/images/sha256-1f66155729621192a58d52488355804db957f33b2e9013cc9e7b55a6e3a83655) |
| Installed as   | Docker image |

## Issue

Cannot even check the version:

```
λ docker run --rm -v ${pwd}:/project rector/rector:latest --version
Notice: Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in /project/vendor/nette/utils/src/Utils/Strings.php on line 152
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "Rector\Core\Console\ConsoleApplication". Did you mean this: "Rector\Core\Console\Application"? in /project/vendor/symfony/dependency-injection/Container.php:280
Stack trace:
#0 /project/vendor/symfony/dependency-injection/Container.php(228): Symfony\Component\DependencyInjection\Container->make('Rector\\Core\\Con...', 1)
#1 /rector/bin/rector.php(74): Symfony\Component\DependencyInjection\Container->get('Rector\\Core\\Con...')
#2 /rector/bin/rector(4): require_once('/rector/bin/rec...')
#3 {main}
  thrown in /project/vendor/symfony/dependency-injection/Container.php on line 280
```

**Comment by TomasVotruba** [comment] 2020-12-25 17:37
Thanks for reporting. Could you confirm the problem is still on latest Docker image?

**Comment by TomasVotruba** [comment] 2020-12-26 10:43
Resolved by https://github.com/rectorphp/rector/pull/4559

**Closed by TomasVotruba** 2020-12-26 10:43 UTC
Labels: bug
