### ISSUE TITLE
`RenameClassRector` ignored `use`.

### ISSUE THREAD

**Issue by atlance** [rectorphp/rector#7549] opened 2022-10-19 11:49 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.6

1) In `composer.json`
```
        "psr/simple-cache": "^3.0",
        "symfony/cache": "^6.1",
```

2) Rector config:
``` 
use Rector\Symfony\Set\SymfonyLevelSetList;
// ....
    $rectorConfig->sets([
        // ...
        SymfonyLevelSetList::UP_TO_SYMFONY_60, // <- problem here.
        // ...
    ]);
// ....
```

3) Exists class:
```
use Psr\SimpleCache\CacheInterface;

class SimpleCacheBridge implements CacheInterface
```

Problem:
Result after `vendor/bin/rector process`:

```
1) src/SimpleCacheBridge.php:5

    ---------- begin diff ----------
@@ @@

 use Psr\SimpleCache\CacheInterface;

-class SimpleCacheBridge implements CacheInterface
+class SimpleCacheBridge implements \Symfony\Contracts\Cache\CacheInterface
 {
     public function get(string $key, mixed $default = null): mixed
     {
    ----------- end diff -----------

Applied rules:
 .................
 * RenameClassRector
  .................
```

Exists difference between interfaces/classes. Ignored `use`.

Maybe he should skip it? =)

**Comment by samsonasik** [comment] 2023-03-05 19:17
Just tried and it got crash `Undefined array key 0` on no namespace https://getrector.com/demo/2b3a31b6-de88-46ce-b17c-7ec08ed1fc18

When namespaced, it works as expected : 

- without autoimport enabled: not rename use statement https://getrector.com/demo/9e7b08a0-28d6-494a-8492-fc41ed0c6631
- with autoimport enabled, rename use statement as well https://getrector.com/demo/5540f87a-7913-403d-8622-dfc3ca27ab9e

I will check why it crash when no namespace.

**Comment by samsonasik** [comment] 2023-03-05 19:36
@atlance I can't reproduce with unit test and e2e test even with unknown class, could you try latest 0.15.20 and try enable autoimport with:

```php
$rectorConfig->importNames();
```

https://getrector.com/demo/5540f87a-7913-403d-8622-dfc3ca27ab9e

**Comment by samsonasik** [comment] 2023-03-06 00:41
The crash when no namespace resolved in latest dev-main.

Before: https://getrector.com/demo/2b3a31b6-de88-46ce-b17c-7ec08ed1fc18

After: https://getrector.com/demo/1fe1232a-4741-4564-b225-8f0822338071

However, the unused import should not be removed unless configured:

```php
$rectorConfig->removeUnusedImports();
```

It only happen on no namespace, I will look into it.

**Closed** 2023-03-06 11:57 UTC
Labels: bug

**Comment by samsonasik** [comment] 2023-03-06 12:05
@atlance it resolved on latest `"rector/rector": "dev-main"`, you can use:

```php
$rectorConfig->importNames();
```

to automatically replace use statement, or use:

```php
$rectorConfig->removeUnusedImports();
```

If you just want to remove unused use, works for both namespaced and non-namespaced class
