### ISSUE TITLE
In TokenIterator.php line 141:                                                         Unexpected token ":", expected ')' at offset 1182  

### ISSUE THREAD

**Issue by sergey-telpuk** [rectorphp/rector#6863] opened 2021-12-13 06:15 UTC
Config:
```php
return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $services = $containerConfigurator->services();

    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
    $parameters->set(Option::PATHS, [
//        __DIR__ . '/app',
        __DIR__ . '/src',
    ]);

    $parameters->set(Option::SKIP, [
        // absolute directory
        __DIR__ . '/vendor',
        __DIR__ . '/tests',
    ]);
```
```bash
Error:
In TokenIterator.php line 141:
                                                     
  Unexpected token ":", expected ')' at offset 1182  
```

**Comment by samsonasik** [comment] 2021-12-13 11:31
Could you run with `-vvv` to see the possible path that cause it with printed stack trace and file that cause it? Thank you.

**Comment by sergey-telpuk** [comment] 2021-12-13 18:34
```bash
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
Running 2.1.12 (2021-11-09 16:02:04) with PHP 8.0.13 on Linux / 5.13.0-22-generic
Reading ./composer.json (/app/composer.json)
Loading auth config from COMPOSER_AUTH
Loading config file ./composer.json (/app/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/app): git branch -a --no-color --no-abbrev -v
Executing command (/app): git rev-list master..BIG-74-backend-2fa-authentication---sms
Executing command (/app): git rev-list remotes/origin/master..BIG-74-backend-2fa-authentication---sms
Failed to initialize global composer: Composer could not find the config file: /home/road-runner/.composer/composer.json

Reading /app/vendor/composer/installed.json
Loading plugin PackageVersions\Installer (from composer/package-versions-deprecated)
> rector: rector process
Executing command (CWD): rector process
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(

                                                                                                                        
 [WARNING] Your project contains 1 configurable rector rules that are skipped as need to be configured to run.          
                                                                                                                        

 * Rector\Php55\Rector\String_\StringClassNameToClassConstantRector

 ! [NOTE] Do you want to run them?                                                                                      
 !        Configure them in `rector.php` with "...->configure(...);"                                                    

 10/10 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "app/common/AnonymousClassb6ec136e3651ebeb09b602d7a413698e.php" file, due to:                
         "Internal error.". On line: 155                                                                                
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "app/common/AnonymousClass8ca7036f46b757b669ca896ed1dc986d.php" file, due to:                
         "Internal error.". On line: 155                                                                                
                                                                                                                        

Script rector process handling the rector event returned with error code 1

**Comment by sergey-telpuk** [comment] 2021-12-13 18:35
and why rector create Anonymous class, I dont want to have this behavior

**Comment by sergey-telpuk** [comment] 2021-12-13 18:40
```bash
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
Running 2.1.12 (2021-11-09 16:02:04) with PHP 8.0.13 on Linux / 5.13.0-22-generic
Reading ./composer.json (/app/composer.json)
Loading auth config from COMPOSER_AUTH
Loading config file ./composer.json (/app/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/app): git branch -a --no-color --no-abbrev -v
Executing command (/app): git rev-list master..BIG-74-backend-2fa-authentication---sms
Executing command (/app): git rev-list remotes/origin/master..BIG-74-backend-2fa-authentication---sms
Failed to initialize global composer: Composer could not find the config file: /home/road-runner/.composer/composer.json

Reading /app/vendor/composer/installed.json
Loading plugin PackageVersions\Installer (from composer/package-versions-deprecated)
> rector: rector process
Executing command (CWD): rector process
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(

                                                                                                                        
 [WARNING] Your project contains 1 configurable rector rules that are skipped as need to be configured to run.          
                                                                                                                        

 * Rector\Php55\Rector\String_\StringClassNameToClassConstantRector

 ! [NOTE] Do you want to run them?                                                                                      
 !        Configure them in `rector.php` with "...->configure(...);"                                                    

  14/222 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   6%PHP Warning:  Undefined array key "AnonymousClass91bf4b49b3e826e0992d69ae1b89e500" in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php on line 251
Warning: Undefined array key "AnonymousClass91bf4b49b3e826e0992d69ae1b89e500" in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php on line 251
PHP Fatal error:  Uncaught TypeError: RectorPrefix20211209\Nette\Utils\Reflection::getUseStatements(): Return value must be of type array, null returned in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php:251
Stack trace:
#0 /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php(224): RectorPrefix20211209\Nette\Utils\Reflection::getUseStatements()
#1 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(213): RectorPrefix20211209\Nette\Utils\Reflection::expandClassName()
#2 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(184): Rector\CodingStyle\ClassNameImport\ShortNameResolver->fqnizeShortNames()
#3 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(150): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromStmtsDocBlocks()
#4 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(96): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveForStmts()
#5 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php(40): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromFile()
#6 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php(37): Rector\CodingStyle\ClassNameImport\ClassNameImportSkipVoter\FullyQualifiedNameClassNameImportSkipVoter->shouldSkip()
#7 /app/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(118): Rector\CodingStyle\ClassNameImport\ClassNameImportSkipper->shouldSkipNameForFullyQualifiedObjectType()
#8 /app/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(86): Rector\CodingStyle\Node\NameImporter->importNameAndCollectNewUseStatement()
#9 /app/vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(132): Rector\CodingStyle\Node\NameImporter->importName()
#10 /app/vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(87): Rector\PostRector\Rector\NameImportingPostRector->processNodeName()
#11 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\PostRector\Rector\NameImportingPostRector->enterNode()
#12 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode()
#13 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#14 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#15 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode()
#16 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#17 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#18 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#19 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray()
#20 /app/vendor/rector/rector/packages/PostRector/Application/PostFileProcessor.php(66): PhpParser\NodeTraverser->traverse()
#21 /app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(106): Rector\PostRector\Application\PostFileProcessor->traverse()
#22 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#23 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(74): Rector\Core\Application\ApplicationFileProcessor->processFiles()
#24 /app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(165): Rector\Core\Application\ApplicationFileProcessor->run()
#25 /app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(296): Rector\Core\Console\Command\ProcessCommand->execute()
#26 /app/vendor/rector/rector/vendor/symfony/console/Application.php(897): RectorPrefix20211209\Symfony\Component\Console\Command\Command->run()
#27 /app/vendor/rector/rector/vendor/symfony/console/Application.php(300): RectorPrefix20211209\Symfony\Component\Console\Application->doRunCommand()
#28 /app/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211209\Symfony\Component\Console\Application->doRun()
#29 /app/vendor/rector/rector/vendor/symfony/console/Application.php(196): Rector\Core\Console\ConsoleApplication->doRun()
#30 /app/vendor/rector/rector/bin/rector.php(56): RectorPrefix20211209\Symfony\Component\Console\Application->run()
#31 /app/vendor/rector/rector/bin/rector(5): require_once('...')
#32 {main}
  thrown in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php on line 251
Fatal error: Uncaught TypeError: RectorPrefix20211209\Nette\Utils\Reflection::getUseStatements(): Return value must be of type array, null returned in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php:251
Stack trace:
#0 /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php(224): RectorPrefix20211209\Nette\Utils\Reflection::getUseStatements()
#1 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(213): RectorPrefix20211209\Nette\Utils\Reflection::expandClassName()
#2 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(184): Rector\CodingStyle\ClassNameImport\ShortNameResolver->fqnizeShortNames()
#3 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(150): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromStmtsDocBlocks()
#4 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(96): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveForStmts()
#5 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php(40): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromFile()
#6 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php(37): Rector\CodingStyle\ClassNameImport\ClassNameImportSkipVoter\FullyQualifiedNameClassNameImportSkipVoter->shouldSkip()
#7 /app/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(118): Rector\CodingStyle\ClassNameImport\ClassNameImportSkipper->shouldSkipNameForFullyQualifiedObjectType()
#8 /app/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(86): Rector\CodingStyle\Node\NameImporter->importNameAndCollectNewUseStatement()
#9 /app/vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(132): Rector\CodingStyle\Node\NameImporter->importName()
#10 /app/vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(87): Rector\PostRector\Rector\NameImportingPostRector->processNodeName()
#11 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\PostRector\Rector\NameImportingPostRector->enterNode()
#12 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode()
#13 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#14 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#15 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode()
#16 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#17 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#18 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#19 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray()
#20 /app/vendor/rector/rector/packages/PostRector/Application/PostFileProcessor.php(66): PhpParser\NodeTraverser->traverse()
#21 /app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(106): Rector\PostRector\Application\PostFileProcessor->traverse()
#22 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#23 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(74): Rector\Core\Application\ApplicationFileProcessor->processFiles()
#24 /app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(165): Rector\Core\Application\ApplicationFileProcessor->run()
#25 /app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(296): Rector\Core\Console\Command\ProcessCommand->execute()
#26 /app/vendor/rector/rector/vendor/symfony/console/Application.php(897): RectorPrefix20211209\Symfony\Component\Console\Command\Command->run()
#27 /app/vendor/rector/rector/vendor/symfony/console/Application.php(300): RectorPrefix20211209\Symfony\Component\Console\Application->doRunCommand()
#28 /app/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211209\Symfony\Component\Console\Application->doRun()
#29 /app/vendor/rector/rector/vendor/symfony/console/Application.php(196): Rector\Core\Console\ConsoleApplication->doRun()
#30 /app/vendor/rector/rector/bin/rector.php(56): RectorPrefix20211209\Symfony\Component\Console\Application->run()
#31 /app/vendor/rector/rector/bin/rector(5): require_once('...')
#32 {main}
  thrown in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php on line 251
Script rector process handling the rector event returned with error code 255

**Comment by samsonasik** [comment] 2021-12-20 10:16
Could you create sample minimal repository to reproduce the issue? Thank you.

**Comment by TomasVotruba** [comment] 2021-12-31 11:14
This has been probably fixed in https://github.com/rectorphp/rector-src/pull/1480

Please test latest `dev-main` and report reproducible repository, if this problem still occurs. That way we'll be able to see the troublesome code and isolate the fix :hugs:

**Closed** 2021-12-31 11:15 UTC
Labels: bug

**Comment by sergey-telpuk** [comment] 2021-12-31 11:22
@TomasVotruba Hi, I have another one error in dev-main
```php
  18/172 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%PHP Fatal error:  Uncaught TypeError: RectorPrefix20211231\Nette\Utils\Reflection::getUseStatements(): Return value must be of type array, null returned in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php:234
Stack trace:
#0 /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php(208): RectorPrefix20211231\Nette\Utils\Reflection::getUseStatements()
#1 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(213): RectorPrefix20211231\Nette\Utils\Reflection::expandClassName()

**Comment by TomasVotruba** [comment] 2021-12-31 11:54
Try the `--debug` run to find out more.
We'll need a reproducible repository to discover the cause.

**Comment by sergey-telpuk** [comment] 2021-12-31 12:03
> Try the `--debug` run to find out more. We'll need a reproducible repository to discover the cause.

[post rectors] app/common/validator.php
    [post rector] Rector\PostRector\Rector\NodeToReplacePostRector
    [post rector] Rector\PostRector\Rector\NodeAddingPostRector
    [post rector] Rector\PostRector\Rector\PropertyAddingPostRector
    [post rector] Ssch\TYPO3Rector\Rector\PostRector\FullQualifiedNamePostRector
    [post rector] Rector\PostRector\Rector\NodeRemovingPostRector
    [post rector] Rector\PostRector\Rector\ClassRenamingPostRector
    [post rector] Rector\PostRector\Rector\NameImportingPostRector
PHP Fatal error:  Uncaught TypeError: RectorPrefix20211231\Nette\Utils\Reflection::getUseStatements(): Return value must be of type array, null returned in /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php:234
Stack trace:
#0 /app/vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php(208): RectorPrefix20211231\Nette\Utils\Reflection::getUseStatements()
#1 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(213): RectorPrefix20211231\Nette\Utils\Reflection::expandClassName()
#2 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(184): Rector\CodingStyle\ClassNameImport\ShortNameResolver->fqnizeShortNames()
#3 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(150): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromStmtsDocBlocks()
#4 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(96): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveForStmts()
#5 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php(35): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromFile()
#6 /app/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php(37): Rector\CodingStyle\ClassNameImport\ClassNameImportSkipVoter\FullyQualifiedNameClassNameImportSkipVoter->shouldSkip()
#7 /app/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(118): Rector\CodingStyle\ClassNameImport\ClassNameImportSkipper->shouldSkipNameForFullyQualifiedObjectType()
#8 /app/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(86): Rector\CodingStyle\Node\NameImporter->importNameAndCollectNewUseStatement()
#9 /app/vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(132): Rector\CodingStyle\Node\NameImporter->importName()
#10 /app/vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(87): Rector\PostRector\Rector\NameImportingPostRector->processNodeName()
#11 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\PostRector\Rector\NameImportingPostRector->enterNode()
#12 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode()
#13 /app/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()

**Comment by sergey-telpuk** [comment] 2021-12-31 12:05
I can share my repo because it's NDA

**Comment by TomasVotruba** [comment] 2021-12-31 12:12
Not neccesary the whole repository. The breaking code is usually 3-5 lines.
That's where `--debug` option helps.

In the end, the Rector should run only on 1 file to see the error, e.g. `vendor/bin/rector process src/Some/SpecificFile.php`
