### ISSUE TITLE
rector-prefixed misses tag 0.6.10

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#2669] opened 2020-01-15 12:43 UTC
tag 0.6.10 is not existant on the prefixed build:

https://github.com/rectorphp/rector-prefixed/releases

**Comment by staabm** [comment] 2020-01-15 13:11
I guess the github-actions did not work properly

**Comment by TomasVotruba** [comment] 2020-01-15 15:47
Looks at Github Actions... any idea what went wrong?
Maybe the tag was not detected :/

**Comment by TomasVotruba** [comment] 2020-01-15 15:48
I added it manually now

**Comment by TomasVotruba** [comment] 2020-01-15 15:51
Possible fix: https://github.com/rectorphp/rector/commit/2aa4937a60d355a99eff135be80fc81b58f9724b

**Comment by TomasVotruba** [comment] 2020-01-15 16:03
https://github.com/rectorphp/rector/runs/391417714#step:7:25

Not sure what that means :/ any ideas? 

This is the responsible file:
https://github.com/rectorphp/rector/blob/ed868e61fcea58f3322331b8ee18da50ab67bef9/.github/workflows/rector_phar.yml#L40

**Comment by staabm** [comment] 2020-01-15 16:29
hmm.. the solution at https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32163/highlight/true#M1024 is valid for on 
```
on:
  push:
    tags:
```

we use a on push for the commits on master branch.. not sure the GTIHUB_REF contains a tag-name when we are responding to a on-commit push

**Comment by TomasVotruba** [comment] 2020-01-15 16:43
Yea, the problem is to get the tag name.

**Comment by Lctrs** [comment] 2020-01-16 22:44
Maybe you can take inspiration from https://github.com/ergebnis/php-library-template/blob/master/.github/workflows/continuous-deployment.yml ?

**Comment by TomasVotruba** [comment] 2020-01-16 23:12
Could you send PR to try it?

**Comment by Lctrs** [comment] 2020-01-17 08:36
Will do some tests.

**Comment by Lctrs** [comment] 2020-01-17 09:56
Please see #2686

**Comment by TomasVotruba** [comment] 2020-01-17 15:39
Resolved by https://github.com/rectorphp/rector/pull/2686

**Closed by TomasVotruba** 2020-01-17 15:39 UTC
Labels: bug

**Comment by staabm** [comment] 2020-01-17 16:04
Great. Thx guys

**Comment by Lctrs** [comment] 2020-01-18 09:39
Looks like it doesn't worked for 0.6.11 :/

Will take a look at it on monday
