### ISSUE TITLE
Incorrect behavior of AnnotationToAttributeRector PHP 8.1

### ISSUE THREAD

**Issue by mirsch** [rectorphp/rector#7163] opened 2022-05-13 07:46 UTC
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

Rector generates nested Attributes in PHP 8.1 but Doctrine does not support nesting (except for `#[AssociationOverrides]` and `#[AttributeOverrides]`) and probably will never support it. See https://github.com/doctrine/orm/pull/9241
Works as expected using PHP 8.0

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f39d41ae-82fe-44d3-bddc-8ebcfccf2c1e

```php
<?php

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(columns={"bar"})})
 * @ORM\Entity
 */
class Foo
{
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```diff
-/**
- * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(columns={"bar"})})
- * @ORM\Entity
- */
-class Foo
-{
+#[ORM\Table]
+#[ORM\UniqueConstraint(columns: ['bar'])]
+#[ORM\Entity]
+class Foo
+{
```

**Comment by samsonasik** [comment] 2022-05-13 08:53
Hi @acrobat, could you verify if this related with your patch at https://github.com/rectorphp/rector-src/pull/1850 ?

**Comment by samsonasik** [comment] 2022-05-15 16:36
Ref also https://github.com/rectorphp/rector-doctrine/pull/82

**Comment by samsonasik** [comment] 2022-05-15 16:42
@mirsch @acrobat could you point to documentation about it's usage with attributes to avoid invalid rolling patch and tweak thas was added by @acrobat at https://github.com/rectorphp/rector-src/pull/1850 ? thank you.

**Comment by acrobat** [comment] 2022-05-16 05:37
@samsonasik I will take a look what should be kept and what should be reverted from https://github.com/rectorphp/rector-src/pull/1850

**Comment by samsonasik** [comment] 2022-06-07 01:23
I am closing it for now, feel free to point to the documentation/example for the use case to avoid flip flop rollback the current existing implementation when you have a chance. Thank you.

**Closed by samsonasik** 2022-06-07 01:23 UTC
Labels: bug

**Comment by mirsch** [comment] 2022-06-07 15:20
@samsonasik Doctrine documentation can be found at https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/attributes-reference.html
As said before, behavior is correct if using LevelSetList::UP_TO_PHP_80. The Problem only occurs using LevelSetList::UP_TO_PHP_81

**Comment by TomasVotruba** [comment] 2022-06-07 20:16
We'll need a failing test case to the rule with defined PHP version.

**Comment by javaDeveloperKid** [comment] 2022-06-25 18:32
I confirm the error. I've just installed rector/rector and used this config:
```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src'
    ]);
    $rectorConfig->sets([
        DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
    ]);
};
```
The following diff was generated:
```diff
-    /**
-     * @ORM\ManyToMany(targetEntity="User")
-     * @ORM\JoinTable(name="user_group_user",
-     *      joinColumns={@ORM\JoinColumn(name="user_group_id", referencedColumnName="id")},
-     *      inverseJoinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}
-     * )
-     */
+    #[ORM\ManyToMany(targetEntity: 'User')]
+    #[ORM\JoinTable(name: 'user_group_user', joinColumns: [new ORM\JoinColumn(name: 'user_group_id', referencedColumnName: 'id')], inverseJoinColumns: [new ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id')])]
    private Collection $users;
```

FYI: @TomasVotruba @samsonasik

**Comment by TomasVotruba** [comment] 2022-06-25 18:43
We need a test case in PR, so CI fails here.

**Comment by javaDeveloperKid** [comment] 2022-06-25 18:55
What do you mean CI fails? How can CI fail here? It's not a bug, it's just Doctrine that does not support nested attributes.

**Comment by javaDeveloperKid** [comment] 2022-06-25 19:00
I don't know rector codebase and right now I don't have time to fork, introduce myself and create a test case. But this is what happens so I'm reporting this. If you have some kind of online rector I can do this there and past here a permalink.

**Comment by TomasVotruba** [comment] 2022-06-25 19:04
You can use the demo page and create test from there: https://getrector.org/demo
It will still require manual edit though
