### ISSUE TITLE
RemoveExtraParametersRector is overly aggressive.

### ISSUE THREAD

**Issue by wiredfool** [rectorphp/rector#7730] opened 2023-01-21 17:15 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.15.10 ,              |
| php | PHP 7.4.3-4ubuntu2.15, ARM64 in docker |

Running rector on a largish, old codebase, the RemoveExtraParametersRector removes parameters in places where it's not appropriate. I've seen this in a few places in my project. 

Specifically, **when running against a directory**,  (vendor/bin/rector process --dry-run --debug /var/www/xml/1.0/) I get this:

```
 	} elseif (isset($_FILES['file'])) {
 		$path = checkMultipartPost($dialect); // allows the website to actually use this.
 	} else {
-		exit_err(422, "Unprocessable Request", "No file found in POST");
+		exit_err(422);
 	}

```
 * RemoveExtraParametersRector (https://www.reddit.com/r/PHP/comments/a1ie7g/is_there_a_linter_for_argumentcounterror_for_php/)

where exit_err is defined in that file as:
```
function exit_err($code, $header_msg, $str) {
	header($header_msg, True, $code);
	print ('<?xml version="1.0" encoding="iso-8859-1"?>' ."\n\t<ErrorMessage>".$str."</ErrorMessage>\n");
	exit;
}
```
That file is the only file where the term "exit_err" shows up in a grep of that directory. 

When run against the file alone (vendor/bin/rector process --dry-run --debug /var/www/xml/1.0/file_upload.inc) there are no instances of the RemoveExtraParametersRector being applied.

## Minimal PHP Code Causing Issue

I'm not sure how to upload a directory of files to the demo. It works on a single file locally and on an excerpt online. 

## Expected Behaviour

Expected behavior is how rector handles the file when running file at a time, rather than project or directory mode.

**Comment by samsonasik** [comment] 2023-01-21 18:06
That's probably because the source external file is using `.inc` extension which phpstan unable to lookup.

You may need to include or add to bootstrap config for that.

**Comment by wiredfool** [comment] 2023-01-22 15:14
Can you unpack that a bit, I'm not sure what you mean there. 

If `.inc` doesn't work (properly), what other bugs am I likely to run across?

**Comment by samsonasik** [comment] 2023-01-25 13:59
The `NodeScopeResolver` only lookup php files:

```php
$this->nodeScopeResolver->setAnalysedFiles($phpFilePaths);
```

if you have non `.php` file, you may have incorrect "Neighbour" files that used it by current file.

**Comment by wiredfool** [comment] 2023-02-10 16:41
Ok, I've found another case where it breaks rules -- this pattern fails in a `.inc` file: https://getrector.com/demo/167fe25f-e412-4bc1-b09b-31c7fcfa4134 by not changing the constructor call in a subclass, where running it on the `.inc` file directly does work properly. 

Assuming that I'm not going to rename half the files in a 20 year old project -- how can I convince it to use `*.(php|inc)` as a neighbor file?

The fallback that I'm considering is something to the effect of:
```
find . -name '*.inc' | xargs vendor/bin/rector process 
```
Is that just a half solution that's going to miss `.inc`->`.inc` relationships, or is that actually going to properly work?

**Comment by samsonasik** [comment] 2023-02-15 14:36
I am not sure if there is a way to make other `.inc` file as neighbour files.

Did you try preload the `.inc` file? Ref https://www.php.net/manual/en/opcache.preloading.php

**Comment by samsonasik** [comment] 2023-03-26 05:21
@wiredfool I created PR to make configured fileExtension via config:

```php
$rectorConfig->fileExtensions(['php', 'inc']);
```

to make both `.php` and `.inc` will be analyzed from `NodeScopeResolver`

- https://github.com/rectorphp/rector-src/pull/3522

**Comment by samsonasik** [comment] 2023-03-26 08:48
@wiredfool could you try latest `"rector/rector": "dev-main"` and verify if it works now? If the issue persist, we need reproducible repository, better with github action running, thank you.

**Comment by samsonasik** [comment] 2023-05-09 06:11
I am closing it as the solution provided above https://github.com/rectorphp/rector/issues/7730#issuecomment-1483999231

Feel free to create new issue if the issue persist with provide a reproducible repository, better with github action. Thank you.

**Closed by samsonasik** 2023-05-09 06:11 UTC
Labels: bug

**Comment by andreucorrea123** [comment] 2024-12-10 13:52
It is **not** only for .inc files, this is a real bug, still present.

**Comment by TomasVotruba** [comment] 2024-12-10 13:58
@andreucorrea123 Thanks for your feedback. Could you share a demo link https://getrector.com/demo or a reproducer repository, where this happens?

I'll look into it :+1:
