### ISSUE TITLE
[Downgrade PHP 8.0] Constructor property promotion

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#4157] opened 2020-09-08 13:16 UTC
# Feature Request

Downgrade new feature from PHP 8.0 to its equivalent PHP 7.4 code
 
## Diff 

```diff
class Money 
{
-    public function __construct(
-        public Currency $currency,
-        public int $amount,
-    ) {

+    public Currency $currency; 
+    public int $amount; 

+    public function __construct(
+        Currency $currency,
+        int $amount,
+    ) {
+        $this->currency = $currency;
+        $this->amount = $amount;
+    }
}
```

**Comment by TomasVotruba** [comment] 2020-12-03 14:35
Duplicate of https://github.com/rectorphp/rector/issues/3827

**Closed by TomasVotruba** 2020-12-03 14:35 UTC
Labels: feature
