### ISSUE TITLE
Reconnect nodes (parent, siblings) when refactor() returns a new node

### ISSUE THREAD

**Issue by matthiasnoback** [rectorphp/rector#6039] opened 2021-04-05 13:21 UTC
# Feature Request

We've been talking about this before @TomasVotruba, but I don't think we've recorded this somewhere. In the rector rule below I want to prevent capturing the return value of a method in a variable if it is already captured in a variable. So I check if the parent node is an `Assign` node, and do an early return. To make this work, I have to set the `parent` node attribute on the original node manually. This is something I think Rector could do easily for us. My suggestion: when `refactor()` returns a node object, the `AbstractRector::enterNode()` method should run the `NodeConnectingVisitor` again on the returned node, to establish the full hierarchy of nodes (e.g. set parent and sibling references). This makes it less "wtf" for people creating their own rules and running into the problem that a node has no parent attribute, even though it is part of the node hierarchy.

```php
final class CaptureReturnValueRector extends AbstractRector
{
    /**
     * @param MethodCall $node
     */
    public function refactor(Node $node): ?Node
    {
        if (! $this->isName($node->name, 'modify')) {
            return null;
        }

        // If the return value is already captured, do nothing:
        $parent = $node->getAttribute(AttributeKey::PARENT_NODE);
        if ($parent instanceof Assign) {
            return null;
        }

        $assignNode = new Assign($node->var, $node);

        // Create a link between the new node and the old one:
        $node->setAttribute(AttributeKey::PARENT_NODE, $assignNode);

        return $assignNode;
    }
}
```

**Comment by TomasVotruba** [comment] 2021-04-05 14:20
Agreed :+1: 

Possible duplicate of https://github.com/rectorphp/rector/issues/6030

**Comment by matthiasnoback** [comment] 2021-04-05 14:32
Ah, interesting.

**Comment by TomasVotruba** [comment] 2021-04-08 11:58
Looking into it...

**Closed** 2021-04-08 12:44 UTC
Labels: feature

**Comment by TomasVotruba** [comment] 2021-04-08 13:16
This allows to forget about parents completelly :) It also discovered 2 bugs as positive side-effect

**Comment by matthiasnoback** [comment] 2021-04-08 15:00
Nice work! Certainly an improvement in terms of DX. Will update the book soon.
