### ISSUE TITLE
Rector\Core\Exception\ShouldNotHappenException In AbstractScopeAwareRector.php line 53

### ISSUE THREAD

**Issue by Worst45** [rectorphp/rector#8042] opened 2023-07-07 15:45 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | @dev (0.17.2)             |

When upgrading a code from PHP 7.4 to 8.2, I got a "ShouldNotAppenException". So here am I :)

My script (`/home/me/rector/rector.php`):
```php
<?php
declare(strict_types=1);
use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths(["/home/me/rector/conv"]);
    $rectorConfig->disableParallel();
    $rectorConfig->sets([
                \Rector\Set\ValueObject\LevelSetList::UP_TO_PHP_82,
        ]);
};
```

The command line launched:
```bash
/home/me/rector/vendor/bin/rector process -v -c /home/me/rector/rector.php
```

## Minimal PHP Code Causing Issue
`/home/me/rector/conv/common.php`
```php
<?php
namespace XXXX;
defined('_PS_VERSION_') or exit;

class SomeClass extends BaseClass {
    private function aFunction() {
        ${"xxxxxx$tab"} = [
            [
                'name' => "_xxx$tab",
                'operator' => '!=',
                'value' => '',
            ],
        ];
    }
}
```

Error output:
```

In AbstractScopeAwareRector.php line 53:

  [Rector\Core\Exception\ShouldNotHappenException]
  Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of "PhpParser\Node\Expr\ArrayItem", but is required by a refactorWithScope() method of "Rector\Php81\Rector\Array_\FirstC
  lassCallableRector" rule. Fix scope refresh on changed nodes first


Exception trace:
  at /home/me/rector/vendor/rector/rector/src/Rector/AbstractScopeAwareRector.php:53
 Rector\Core\Rector\AbstractScopeAwareRector->refactor() at /home/me/rector/vendor/rector/rector/src/Rector/AbstractRector.php:209
 Rector\Core\Rector\AbstractRector->enterNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:113
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:133
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:133
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at /home/me/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
 PhpParser\NodeTraverser->traverse() at /home/me/rector/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php:43
 Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse() at /home/me/rector/vendor/rector/rector/src/Application/FileProcessor.php:44
 Rector\Core\Application\FileProcessor->refactor() at /home/me/rector/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php:115
 Rector\Core\Application\FileProcessor\PhpFileProcessor->process() at /home/me/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php:162
 Rector\Core\Application\ApplicationFileProcessor->processFiles() at /home/me/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php:132
 Rector\Core\Application\ApplicationFileProcessor->run() at /home/me/rector/vendor/rector/rector/src/Console/Command/ProcessCommand.php:123
 Rector\Core\Console\Command\ProcessCommand->execute() at /home/me/rector/vendor/rector/rector/vendor/symfony/console/Command/Command.php:325
 RectorPrefix202306\Symfony\Component\Console\Command\Command->run() at /home/me/rector/vendor/rector/rector/vendor/symfony/console/Application.php:944
 RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand() at /home/me/rector/vendor/rector/rector/vendor/symfony/console/Application.php:326
 RectorPrefix202306\Symfony\Component\Console\Application->doRun() at /home/me/rector/vendor/rector/rector/src/Console/ConsoleApplication.php:49
 Rector\Core\Console\ConsoleApplication->doRun() at /home/me/rector/vendor/rector/rector/vendor/symfony/console/Application.php:212
 RectorPrefix202306\Symfony\Component\Console\Application->run() at /home/me/rector/vendor/rector/rector/bin/rector.php:132
 require_once() at /home/me/rector/vendor/rector/rector/bin/rector:5
 include() at /home/me/rector/vendor/bin/rector:117

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--no-progress-bar] [--no-diffs] [--output-format OUTPUT-FORMAT] [--debug] [--memory-limit MEMORY-LIMIT] [--clear-cache] [--port PORT] [--identifier IDENTIFIER] [--] [<source>...]
```

## Expected Behaviour

No error

By the way, a big thanks for your huge, great job!

**Comment by samsonasik** [comment] 2023-07-07 15:48
I can't reproduce in latest dev-main https://getrector.com/demo/e14b1ce9-5db0-43fc-8a40-81538af222e7

Please try latest dev-main:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If the issue persist, please provide reproducible test on https://getrector.com/demo/  , or we need simple reproducible code for that that show error, with only 1 or 2 rules, you can provide reproducible github repo, better with github action running

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by Worst45** [comment] 2023-07-10 07:15
I confirm the problem is gone with the latest dev release. Thanks a lot !!!

**Comment by samsonasik** [comment] 2023-07-10 07:20
Thank you for verify, I am closing it then ;)

**Closed by samsonasik** 2023-07-10 07:20 UTC
Labels: bug
