### ISSUE TITLE
[Prefixed] PHP Fatal error:  Declaration of RectorPrefix20210422\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210422\Psr\Container\ContainerInterface::has($id)

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#6192] opened 2021-04-22 10:58 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | latest tagged release and master too              |
| Installed as   | prefixed Rector                           |

I'm getting this error:
```
PHP Fatal error:  Declaration of RectorPrefix20210422\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210422\Psr\Container\ContainerInterface::has($id) in /Volumes/CS/www/website/vendor/rector/rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 41
Fatal error: Declaration of RectorPrefix20210422\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210422\Psr\Container\ContainerInterface::has($id) in /Volumes/CS/www/website/vendor/rector/rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 41
```

Seems like the prefixed build is broken.

**Comment by sabbelasichon** [comment] 2021-04-22 20:32
Seems to be a duplicate of #6176

**Comment by TomasVotruba** [comment] 2021-04-22 21:14
Yea, I've been working on it last 2 days. Covariance with Symfony traits and psr interface is quite a pickle :)

Keep watching the `dev-main`

**Comment by TomasVotruba** [comment] 2021-04-24 13:47
Resolve in:

- https://github.com/rectorphp/rector/pull/6207
- https://github.com/rectorphp/rector/pull/6218
- https://github.com/rectorphp/rector/pull/6224
- https://github.com/rectorphp/rector/pull/6225
- https://github.com/rectorphp/rector/pull/6227

**Closed by TomasVotruba** 2021-04-24 13:47 UTC
Labels: bug
