### ISSUE TITLE
Incorrect behavior of DowngradeTypedPropertyRector, DowngradeAttributeToAnnotationRector

### ISSUE THREAD

**Issue by rs-ubaldi** [rectorphp/rector#6924] opened 2022-01-10 16:59 UTC
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec7232d-ab1f-6fcc-b2da-353706041535

```php
<?php
declare(strict_types=1);

class DemoFile
{
	protected ?string $toto = 'toto';
}
```

### Responsible rules

* `DowngradeTypedPropertyRector`

* `DowngradeAttributeToAnnotationRector`

## Expected Behavior

Original default propery value should be kept (even if nullable) but is instead dropped when downgrading to PHP 7.2.

**Comment by TomasVotruba** [comment] 2022-01-10 17:33
Thanks for reporting :+1: 

Closing as duplicate of https://github.com/rectorphp/rector/issues/6925

**Closed by TomasVotruba** 2022-01-10 17:33 UTC
Labels: bug
