### ISSUE TITLE
Problem with RestoreDefaultNullToNullableTypePropertyRector

### ISSUE THREAD

**Issue by guelosuperstart** [rectorphp/rector#7125] opened 2022-04-22 11:24 UTC
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.21             |
| php version | 8.0.13            |
| SF version | 5.4            |

Hello,

Rector changes the code this way:

```diff
    ---------- begin diff ----------
@@ @@
 {
     #[ORM\Id, ORM\Column(options: ['unsigned' => true]), ORM\GeneratedValue]
     #[Groups(['default', 'id'])]
-    protected int $id;
+    protected int $id = null;

     public function getId(): int
     {
    ----------- end diff -----------

Applied rules:
 * SymplifyQuoteEscapeRector
 * RemoveRedundantDefaultPropertyAnnotationValuesRector (https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/basic-mapping.html#property-mapping)
 * RestoreDefaultNullToNullableTypePropertyRector
 * RenamePropertyRector
```

But my property isn't nullable :

```php
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @SuppressWarnings(PHPMD.ShortVariable)
 */
trait Idable
{
    #[ORM\Id, ORM\Column(options: ['unsigned' => true]), ORM\GeneratedValue]
    #[Groups(['default', 'id'])]
    protected int $id;

    public function getId(): int
    {
        return $this->id;
    }
}
```

**Comment by TomasVotruba** [comment] 2022-04-22 11:35
Hi, thanks for your report.
How can we detect the property should be skipped? I'm not familiar with validator groups.

**Comment by samsonasik** [comment] 2022-04-22 12:26
@guelosuperstart It seems due to multiple rules usage, I can't reproduce with only `RestoreDefaultNullToNullableTypePropertyRector`:

https://getrector.org/demo/e9d7c331-2ee6-42b9-a679-e98c5db6b343

Could you try run with `-vvv` or share a reproducible repository for it? Thank you.

**Comment by samsonasik** [comment] 2022-04-22 12:29
Ok, it seems you're using 0.12.21, it should be fixed in latest dev-main on https://github.com/rectorphp/rector-src/pull/2094 , please try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Closed by samsonasik** 2022-04-22 12:29 UTC
Labels: bug

**Comment by guelosuperstart** [comment] 2022-04-29 12:39
Hello,
I confirm that the version 0.12.22 fixes the problem.

Great work !!
