### ISSUE TITLE
Incorrect fix by `--set code-quality`

### ISSUE THREAD

**Issue by HenkPoley** [rectorphp/rector#2286] opened 2019-11-08 12:44 UTC
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | e.g. v0.5.21         |
| PHP version    | e.g. PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS ) |
| Full Command   | rector process . --set code-quality --dry-run  | 

## Current Behaviour 

It changes a `class SameName extends \Foo\Bar\SameName` to`class SameName extends SameName`. Which breaks PHP compiling the file.

```
$ rector process . --set code-quality --dry-run
Rector v0.5.21

..

2) tests/TestCase.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -7,7 +8,7 @@
 use Illuminate\Foundation\Application;
 use Illuminate\Foundation\Testing\TestCase as IlluminateTestCase;

-abstract class TestCase extends IlluminateTestCase
+abstract class TestCase extends TestCase
 {
     /**
      * The base URL to use while testing the application.
    ----------- end diff -----------
```

## Minimal PHP Code Causing Issue

This ought to cause the problem.

  

Within a Laravel project test:

```php
<?php 
use Illuminate\Foundation\Testing\TestCase as IlluminateTestCase

abstract class TestCase extends IlluminateTestCase {
}
// put file content here
```

**Comment by TomasVotruba** [comment] 2019-11-10 01:23
Could you re-check with current `master`? There were some "import" changes

**Comment by HenkPoley** [comment] 2019-11-26 10:19
With dev-master 225f873d2cca67b40eaffb106848b4258d1e11db I'm still seeing:
```
40) tests/TestCase.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -1,8 +1,9 @@
 <?php

+use Laravel\Lumen\Testing\TestCase;
 use Laravel\Lumen\Application;

-abstract class TestCase extends Laravel\Lumen\Testing\TestCase
+abstract class TestCase extends TestCase
 {
     /**
      * Creates the application.
    ----------- end diff -----------
```

**Comment by TomasVotruba** [comment] 2019-11-26 10:25
That's correct behavior

If you want to disable it, you can: 
https://github.com/rectorphp/rector#import-use-statements

**Comment by TomasVotruba** [comment] 2019-11-26 10:27
That's weird. 

Failing test is needed here: https://github.com/rectorphp/rector/tree/master/packages/Renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames

**Comment by TomasVotruba** [comment] 2019-12-26 11:24
Closing as could not reproduce

![non_confirmed](https://user-images.githubusercontent.com/924196/71474201-a999bc80-27da-11ea-8586-cf666e6382ff.gif)

**Closed by TomasVotruba** 2019-12-26 11:24 UTC
Labels: bug
