### ISSUE TITLE
  PHPStan\Type\IntegerRangeType::fromInterval(): Argument #1 ($min) must be of type ?int

### ISSUE THREAD

**Issue by philsturgeon** [rectorphp/rector#7010] opened 2022-02-18 12:37 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.16  (528d6dd6986c529246832f686e482c3f7bc46a40)            |
| PHP version | 8.0 |

I'm getting an error that shows PHPStan backtrace but doesn't point me to where the issue is in my code, so im not sure how to fix it. 

```
[parsing] app/redacted-file.php

In IntegerRangeType.php line 25:

  PHPStan\Type\IntegerRangeType::fromInterval(): Argument #1 ($min) must be of type ?int, float given, called in phar:///Users/phil/src/cloudbeds/myfrontdesk-docker-local/microservice-compset-rates/ven
  dor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php on line 3590
```

## Minimal PHP Code Causing Issue

Trial and error showed me that commenting out this code would let rector pass instead of tripping on that error.

```php
 <?php

function convert($amount = null)
{
    // absolute value of amount
    $amount = abs($amount);
    // convert amount to cents for more accuracy
    if ($amount >= 1000000000 && $amount < 1000000000000) {
        $amount = $amount * 1000000000000;
    }
    return $amount;
}

```

## Expected Behaviour

Rector could perhaps look at the backtrace to help identify what is wrong with the the code and where?

**Comment by philsturgeon** [comment] 2022-02-18 13:00
Either removing the `$amount = abs($amount);` line or casting $amount seems to hide the error. `$amount = (int) $amount * 1000000000000;`

**Comment by philsturgeon** [comment] 2022-02-18 13:09
It does not show the rule being applied, even using -vvv, as I did with the output I pasted above. I have no further information and thats the problem.

**Comment by TomasVotruba** [comment] 2022-02-18 13:13
Is the `--debug` option any different?

**Comment by samsonasik** [comment] 2022-02-18 13:24
@TomasVotruba -vvv seems showing the rules applied:

```bash
➜  rector-src git:(main) ✗ bin/rector process src/Console -vvv --clear-cache |more
[parsing] src/Console/Command/AbstractProcessCommand.php
[refactoring] src/Console/Command/AbstractProcessCommand.php
    [applying] Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector
    [applying] Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector
    [applying] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector
    [applying] Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector
    [applying] Rector\Nette\Rector\LNumber\ReplaceTimeNumberWithDateTimeConstantRector
```

**Comment by philsturgeon** [comment] 2022-02-18 13:27
-vvv does work in general yes, --debug doesn't make a difference.

The trouble is the order of things. Output shows parsing, then refactoring, then applying, but this file blows up after outputting parsing, before showing refactoring or applying. 

```
[parsing] tests/TestCase.php
[refactoring] tests/TestCase.php
    [applying] Rector\Php80\Rector\Class_\StringableForToStringRector
    [applying] Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector
    [applying] Rector\Php80\Rector\FunctionLike\UnionTypesRector
    [applying] Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector
    [applying] Rector\Php80\Rector\ClassMethod\SetStateToStaticRector
    [applying] Rector\Php80\Rector\ClassMethod\FinalPrivateToPrivateVisibilityRector
    [applying] Rector\Php80\Rector\ClassMethod\OptionalParametersAfterRequiredRector
    [applying] Rector\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector
    [applying] Rector\Transform\Rector\StaticCall\StaticCallToFuncCallRector
    [applying] Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector
    [applying] Rector\Php80\Rector\FuncCall\ClassOnObjectRector
    [applying] Rector\Php80\Rector\FuncCall\TokenGetAllToObjectRector
    [applying] Rector\Renaming\Rector\FuncCall\RenameFunctionRector
    [applying] Rector\Arguments\Rector\FuncCall\FunctionArgumentDefaultValueReplacerRector
    [applying] Rector\Php80\Rector\FuncCall\Php8ResourceReturnToObjectRector
[post rectors] tests/TestCase.php
    [post rector] Rector\PostRector\Rector\NodeToReplacePostRector
    [post rector] Rector\PostRector\Rector\NodeAddingPostRector
    [post rector] Rector\PostRector\Rector\PropertyAddingPostRector
    [post rector] Ssch\TYPO3Rector\Rector\PostRector\FullQualifiedNamePostRector
    [post rector] Rector\PostRector\Rector\NodeRemovingPostRector
    [post rector] Rector\PostRector\Rector\ClassRenamingPostRector
    [post rector] Rector\PostRector\Rector\NameImportingPostRector
    [post rector] Rector\PostRector\Rector\UseAddingPostRector
[print] tests/TestCase.php
```

**Comment by samsonasik** [comment] 2022-02-18 13:37
@philsturgeon you may just run to the 1 file, eg:

```
bin/rector process tests/TestCase.php -vvv --clear-cache
```

narrowing down rector.php config half by half may also help

**Comment by philsturgeon** [comment] 2022-02-18 14:24
TestCase is not the problem, I was just showing how the output works, and explaining why I am not getting a list of applied rules in output for the file in question.

This gives me the same output. I don't get anything useful from the output.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/67381/154699090-b72816a8-eddf-4d87-8e74-371fc79ab2f5.png">

**Comment by samsonasik** [comment] 2022-02-18 14:27
Could you create minimal reproduced repository consist with `Rectatebug.php` and single `rector.php` config that cause it?

**Comment by philsturgeon** [comment] 2022-02-18 15:11
I've popped the single reproduceable file in the issue description already.

Here's my rector.php:

```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SetList::PHP_80);

    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_80);
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false);

    $parameters->set(Option::SKIP, [
      ChangeSwitchToMatchRector::class,
    ]);

    $parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, getcwd() . '/phpstan.neon');
};
```

**Comment by samsonasik** [comment] 2022-02-18 15:40
I can't reproduce it at getrector.org/demo https://getrector.org/demo/615dfedb-caa4-4b30-a022-0cfe7c8843af
I can't reproduce it with create unit test locally for it, possibly already resolved in latest `"rector/rector": "dev-main"`?

```bash
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```

It seems you changed the example code with reduce `if else` statements in the issue description ?

**Comment by samsonasik** [comment] 2022-02-20 07:53
@philsturgeon I still can't reproduce even in php 8.0 (use version 8.0.15) and with the file and rector.php you shared, with rector 0.12.16, phpstan 1.4.6

![Screen Shot 2022-02-20 at 14 52 28](https://user-images.githubusercontent.com/459648/154833605-fb4e74ce-45b0-4ce9-8519-0d2269485823.png)


I probably missing something, I think it would be better if you can create a reproducible repository for it (with github action enabled would be better), Thank you.

**Comment by philsturgeon** [comment] 2022-02-22 11:01
Thank you for looking into this. I'm having the same trouble recreating in a standalone repo. 

I've got the rector.php, phpstan.neon, composer.json and recreatebug.php file all moved over and it's running just fine. 

```
▶ ./vendor/bin/rector process Rectatebug.php -vvv --clear-cache
[parsing] Rectatebug.php
[refactoring] Rectatebug.php
    [applying] Rector\Php80\Rector\FunctionLike\UnionTypesRector
    [applying] Rector\Php80\Rector\FuncCall\ClassOnObjectRector
    [applying] Rector\Php80\Rector\FuncCall\TokenGetAllToObjectRector
    [applying] Rector\Renaming\Rector\FuncCall\RenameFunctionRector
    [applying] Rector\Arguments\Rector\FuncCall\FunctionArgumentDefaultValueReplacerRector
    [applying] Rector\Php80\Rector\FuncCall\Php8ResourceReturnToObjectRector
[post rectors] Rectatebug.php
    [post rector] Rector\PostRector\Rector\NodeToReplacePostRector
    [post rector] Rector\PostRector\Rector\NodeAddingPostRector
    [post rector] Rector\PostRector\Rector\PropertyAddingPostRector
    [post rector] Ssch\TYPO3Rector\Rector\PostRector\FullQualifiedNamePostRector
    [post rector] Rector\PostRector\Rector\NodeRemovingPostRector
    [post rector] Rector\PostRector\Rector\ClassRenamingPostRector
    [post rector] Rector\PostRector\Rector\NameImportingPostRector
    [post rector] Rector\PostRector\Rector\UseAddingPostRector
[print] Rectatebug.php


 [OK] Rector is done!

```

What else can I try? Do you ever do freelance, maybe have an hourly rate for remote debugging?

**Comment by samsonasik** [comment] 2022-02-22 12:11
@philsturgeon yes, you can send me an email to samsonasik@gmail.com for your availability for remote debugging ;)

**Comment by samsonasik** [comment] 2022-03-03 12:58
Solved with using rector global installation.

**Closed by samsonasik** 2022-03-03 12:58 UTC
Labels: bug
