### ISSUE TITLE
Can't load mglaman/phpstan-drupal as the DI container is not available

### ISSUE THREAD

**Issue by mfrieling** [rectorphp/rector#7795] opened 2023-02-21 16:04 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| rector/rector | v0.15.17 |
| palantirnet/drupal-rector | v0.15.0 |
| phpstan/phpstan | v1.10.0 |
| mglaman/phpstan-drupal | v1.1.29 |

I had `mglaman/phpstan-drupal` already installed and working and now installed `palantirnet/drupal-rector` as well. When executing `vendor/bin/rector` I get the following error message:

```
 [ERROR] "PHPStan\ShouldNotHappenException" thrown in                                                                   
         "/var/www/html/vendor/mglaman/phpstan-drupal/drupal-autoloader.php" on line 7 while loading bootstrap file     
         /var/www/html/vendor/mglaman/phpstan-drupal/drupal-autoloader.php: The autoloader did not receive the          
         container.
```
By adding some _printf()_ outputs I could break this down to `Rector\NodeTypeResolver\DependencyInjection\PHPStanExtensionsConfigResolver::resolve()` detecting the _drupal-autoloader.php_ of `mglaman/phpstan-drupal`. But that fails if the variable `$container` isn't set correctly, which here is the case.

## Minimal PHP Code Causing Issue

No custom PHP code is required to cause this issue, just install the packages in the versions mentioned above.

## Expected Behaviour

When resolving the extensions, simply skip `mglaman/phpstan-drupal`.

**Comment by mfrieling** [comment] 2023-02-21 16:48
(Forked the wrong repository. Ignore the commit above.)

**Comment by tr33m4n** [comment] 2023-02-22 08:57
I'm experiencing a very similar issue when attempting to use the latest v0.15.17 version of Rector with https://github.com/bitExpert/phpstan-magento . `phpstan-magento` adds a bootstrap file here https://github.com/bitExpert/phpstan-magento/blob/master/extension.neon#L7 . This is then picked up by Rector when it runs but fails due to `$container` having not been instantiated https://github.com/bitExpert/phpstan-magento/blob/master/magento-autoloader.php#L16

I can confirm that downgrading to v0.15.13 fixes the issue

**Comment by samsonasik** [comment] 2023-02-22 09:41
@mfrieling @tr33m4n could you create simple repoducible repository for it? Better with github action running so it can be resolved once for all.

Thank you.

**Comment by mfrieling** [comment] 2023-02-22 13:54
@samsonasik unfortunatley I have no time to create a repo as my main task is to implement a feature in a customer project For that I needed a contrib module I have to upgrade to be Drupal 10 compatible. For that I needed rector (which I've never used before) and stumbled over this error, which required me to find a fix to be able to upgrade the module. Furthermore I don't know how to create github action as I primarily work with a different git plattform. Maybe @tr33m4n can create a repo?

But the primary goal instead of finding all PHPStan extensions failing to be loaded by rector should be to load the extensions correctly including providing the a properly configured DI $container variable, which according to @mglaman is not the case in the current version.

**Comment by TomasVotruba** [comment] 2023-02-22 16:04
For reference, here are the autoload files from PHPStan extensions:

* https://github.com/mglaman/phpstan-drupal/blob/main/drupal-autoloader.php
* https://github.com/bitExpert/phpstan-magento/blob/master/magento-autoloader.php

**Comment by TomasVotruba** [comment] 2023-02-22 16:08
It looks like all the bootstrap files are passed PHPStan container :thinking: 

https://github.com/phpstan/phpstan-src/blob/34881e682e36e30917dcfa8dc69c70e857143436/src/Command/CommandHelper.php#L513-L515

**Comment by TomasVotruba** [comment] 2023-02-22 16:38
I have a very rough guess :)
Could you try to modify your local `/vendor/rector/rector` files with these? https://github.com/rectorphp/rector-src/pull/3401/files

If it helps, we can merge it and ship it :+1:

**Comment by samsonasik** [comment] 2023-02-28 13:54
Rector 0.15.19 released for it https://github.com/rectorphp/rector/releases/tag/0.15.19

**Comment by mfrieling** [comment] 2023-02-28 17:05
Unfortunately this is not fixed. Now with 0.15.19 I get a new error which has been introduced in 0.15.19:

> [ERROR] "Rector\Core\Exception\ShouldNotHappenException" thrown in                                                     
>          "vendor/palantirnet/drupal-rector/config/drupal-phpunit-bootstrap-file.php" on line 14 while     
>          loading bootstrap file                                                                                         
>          vendor/palantirnet/drupal-rector/config/drupal-9/../drupal-phpunit-bootstrap-file.php: The Drupal
>          PHPUnit Bootstrap file could not access the BootstrapFilesIncluder

My rector.php:

```
<?php

declare(strict_types=1);

use DrupalFinder\DrupalFinder;
use DrupalRector\Set\Drupal8SetList;
use DrupalRector\Set\Drupal9SetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
  // Adjust the set lists to be more granular to your Drupal requirements.
  // @todo find out how to only load the relevant rector rules.
  //   Should we try and load \Drupal::VERSION and check?
  $rectorConfig->sets([
    Drupal8SetList::DRUPAL_8,
    Drupal9SetList::DRUPAL_9,
  ]);

  $parameters = $rectorConfig->parameters();

  $drupalFinder = new DrupalFinder();
  $drupalFinder->locateRoot(__DIR__);
  $drupalRoot = $drupalFinder->getDrupalRoot();
  $rectorConfig->autoloadPaths([
    $drupalRoot . '/core',
    $drupalRoot . '/modules',
    $drupalRoot . '/profiles',
    $drupalRoot . '/themes'
  ]);

  $rectorConfig->skip(['*/upgrade_status/tests/modules/*']);
  $rectorConfig->fileExtensions(['php', 'module', 'theme', 'install', 'profile', 'inc', 'engine']);
  $rectorConfig->importNames(true, false);
  $rectorConfig->importShortClasses(false);
  $parameters->set('drupal_rector_notices_as_comments', true);
};
```

Feel free to create a new issue for that if needed.

**Comment by samsonasik** [comment] 2023-02-28 17:09
we need failing test case repository which you need to invest the time so it can be fixed correctly :)

**Comment by AlexSkrypnyk** [comment] 2023-03-08 01:48
`0.15.19` has completely broken Rector for Drupal using `palantirnet/drupal-rector`. 

Rector cannot bootstrap past the message
```
[ERROR] "Rector\Core\Exception\ShouldNotHappenException" thrown in
"vendor/palantirnet/drupal-rector/config/drupal-phpunit-bootstrap-file.php" on line 14 while
loading bootstrap file
vendor/palantirnet/drupal-rector/config/drupal-9/../drupal-phpunit-bootstrap-file.php: The Drupal
PHPUnit Bootstrap file could not access the BootstrapFilesIncluder
```

Maybe this is the cause https://github.com/rectorphp/rector-src/pull/3401

**Comment by sboden** [comment] 2023-03-10 10:25
I can confirm the same... what I do:
- A drupal9 project setup using ddev
- In the container itself with `ddev ssh` I do following:
- `composer require rector/rector --dev` ... the version is "Using version ^0.15.21 for rector/rector"
- `vendor/bin/rector init` results in `[ERROR] "Rector\Core\Exception\ShouldNotHappenException" thrown in         "/var/www/html/vendor/palantirnet/drupal-rector/config/drupal-phpunit-bootstrap-file.php" on line 14 while loading bootstrap file /var/www/html/vendor/palantirnet/drupal-rector/config/drupal-9/../drupal-phpunit-bootstrap-file.php: The Drupal PHPUnit Bootstrap file could not access the BootstrapFilesIncluder`

Then I reverted to previous versions with:
`composer require rector/rector:=x.y.z --dev`
and the latest version which does not have the problem is 0.15.18

**Comment by samsonasik** [comment] 2023-03-13 11:47
@mfrieling @agentrickard The patch need to be in `palantirnet/drupal-rector`, with update:

```diff
-    $rectorConfig->bootstrapFiles([
+    $rectorConfig->autoloadPaths([
        __DIR__ . '/../drupal-phpunit-bootstrap-file.php'
    ]);
```

in both of files:

- palantirnet/drupal-rector/config/drupal-8/drupal-8-all-deprecations.php
- palantirnet/drupal-rector/config/drupal-9/drupal-9-all-deprecations.php

**Comment by mglaman** [comment] 2023-03-22 19:19
The error seems to be in `\Rector\Core\Autoloading\BootstrapFilesIncluder::tryRequireFile`.

Before this passed in the instance of `BootstrapFilesIncluder`. 

So drupal-rector used it to find the path to Drupal for additional bootstrapping

```
if (!isset($this) || !$this instanceof BootstrapFilesIncluder) {
    throw new ShouldNotHappenException('The Drupal PHPUnit Bootstrap file could not access the BootstrapFilesIncluder');
}
```

This changed along the way when PHPStan extension files were added. The current fix mimics PHPStan's bootstrap/autoloading but broke(ish) how drupal-rector handled bootstrapped autoloading.

**Comment by mglaman** [comment] 2023-03-22 19:21
Found it https://github.com/rectorphp/rector-src/commit/48228edf4647336d860ab24af7d4c62ea06c75a1#diff-749ec1d63457440192b836bf36b12935b190e420ddfe7984d1c2c211f01c7591

Before bootstrap files were included within the scope of the class. That commit mimicked PHPStan to load bootstrap files in a static closure with limited scope.

**Comment by mglaman** [comment] 2023-03-22 19:41
For drupal-rector I think I cleaned up the bootstrap file within PR https://github.com/palantirnet/drupal-rector/pull/220 that removes the need for any additional context. I need to see if the same could be done for phpstan-drupal, but that's outside of this issue.

**Comment by samsonasik** [comment] 2023-03-22 20:09
@mglaman awesome 👍

**Comment by samsonasik** [comment] 2023-03-24 10:50
It seems already resolved at https://github.com/palantirnet/drupal-rector/releases/tag/0.15.1

I am closing it ;)

**Closed by samsonasik** 2023-03-24 10:50 UTC
Labels: bug
