### ISSUE TITLE
Return value of Rector\PhpParser\Node\Value\ValueResolver::Rector\PhpParser\Node\Value\{closure}() must be of the type string or null, int returned

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1672] opened 2019-07-02 14:05 UTC
When running Rector with `vendor/bin/rector --ansi process --dry-run src/Test.php` and 

```php
# src/Test.php
final class Test
{
    /** @var int */
    private const DEFAULT_NUMBER = 85;

    /** @var int */
    private $number;

    public function getNumber(): int
    {
        if (null === $this->number) {
            return self::DEFAULT_NUMBER;
        }

        return $this->number;
    }
}
```

It fails with : 

```
 [ERROR] Could not process "src/Test.php" file, due to:                                                                 
         "Return value of Rector\PhpParser\Node\Value\ValueResolver::Rector\PhpParser\Node\Value\{closure}() must be of 
         the type string or null, int returned"
```

Which I've "solved" by changing the following :
```diff
-            return self::DEFAULT_NUMBER;
+            return static::DEFAULT_NUMBER;
```

But both seems valid to me. And the error message doesn't point at all in this direction, I just found this fix by trial-and-error, reverting my changes bits by bits until I found the culprit line.

**Comment by TomasVotruba** [comment] 2019-07-02 14:18
What's the content of `rector.yaml`?

**Comment by gnutix** [comment] 2019-07-09 10:17
https://github.com/rectorphp/rector/issues/1634#issuecomment-507699985

**Comment by TomasVotruba** [comment] 2019-07-09 15:05
Cannot reproduce on current `master`

**Comment by TomasVotruba** [comment] 2019-07-09 15:06
Fixed by  https://github.com/rectorphp/rector/commit/b8cb084573653aa5e2fb7c277e70d332227b3f3b#diff-c39807abd4d9f96da20d6a6637e25423R91

**Closed by TomasVotruba** 2019-07-09 15:06 UTC
Labels: bug
