### ISSUE TITLE
Incorrect behavior of FinalizeClassesWithoutChildrenRector

### ISSUE THREAD

**Issue by darthf1** [rectorphp/rector#7678] opened 2022-12-19 19:40 UTC
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

Could not reproduce online, but failing test case can be found [here](https://github.com/rectorphp/rector-src/pull/3222).

See https://getrector.org/demo/2232758f-6dc9-447c-a97a-c272c4fcbdfc

```php
<?php

declare(strict_types=1);

namespace Domain\MyDomain\Exception;

class RuntimeException extends \RuntimeException
{
}

?>

<?php

declare(strict_types=1);

namespace Domain\MyDomain\Exception;

class MyException extends RuntimeException
{
}
```

### Responsible rules

* `FinalizeClassesWithoutChildrenRector`

## Expected Behavior

```diff
<?php

declare(strict_types=1);

namespace Domain\MyDomain\Exception;

class RuntimeException extends \RuntimeException
{
}

?>

<?php

declare(strict_types=1);

namespace Domain\MyDomain\Exception;

- class MyException extends RuntimeException
+ final class MyException extends RuntimeException
{
}
```

## Actual Behavior

```diff
<?php

declare(strict_types=1);

namespace Domain\MyDomain\Exception;

- class RuntimeException extends \RuntimeException
+ final class RuntimeException extends \RuntimeException
{
}

?>

<?php

declare(strict_types=1);

namespace Domain\MyDomain\Exception;

- class MyException extends RuntimeException
+ final class MyException extends RuntimeException
{
}
```

**Comment by samsonasik** [comment] 2022-12-20 00:09
Finalize class without children can have this condition due to autoload overlap, you can read the documention how to troubleshot it, all there :) 

https://getrector.org/documentation/static-reflection-and-autoload

**Comment by TomasVotruba** [comment] 2022-12-20 12:31
Closing as expected behavior. The solution is in the link provided by @samsonasik

**Closed by TomasVotruba** 2022-12-20 12:31 UTC
Labels: bug

**Comment by darthf1** [comment] 2022-12-20 17:11
> Finalize class without children can have this condition due to autoload overlap, you can read the documention how to troubleshot it, all there :) 
> 
> https://getrector.org/documentation/static-reflection-and-autoload
> 

Yes I see it now. Thanks @samsonasik
