### ISSUE TITLE
Running out of memory (more than 30 GB used)

### ISSUE THREAD

**Issue by JanWennrichPCSG** [rectorphp/rector#4452] opened 2020-10-19 17:02 UTC
# Question

Hello,

I have an old PHP 5.6 project which we plan to port to PHP 7.4.

Using rector with the `--dry-run` parameter I want to get an overview of what would be changed. But unfortunately I'm running out of memory when rector allocates over 30 Gigabytes of memory. Is this normal behavior?

I tried installing rector via Docker and Composer but the issue occurs with both methods. Strangely the progressbar goes up to 27468 when run via composer but only up to 7736 when run via Docker. Is this because rector scans the `vendor/` directory when installed via Composer?

The project's PHP files are spread around multiple directories, therefore I can't specify a single repository which only contains PHP files but instead have to use the root repository as an entry point which also contains PDF and image files. Could this be the issue or is rector only scanning PHP files? I tried to tell rector to only use PHP files by filters but couldn't get that to work.

The commands I tried are the following:
`vendor/bin/rector process . --dry-run --output-file rector.log --set php74`

and

`docker run --rm -v $(pwd):/project rector/rector:latest process . --set php74 --dry-run`

**Comment by TomasVotruba** [comment] 2020-10-19 20:42
Hi,

that's because of the `vendor`, yeah.

Rule of a thumb: never run tools with `.` as an argument.

```bash
vendor/bin/rector process . 
```

Instead, put explicit paths you want to check, e.g.:

```bash
vendor/bin/rector process src
```

**Comment by JanWennrichPCSG** [comment] 2020-10-20 11:15
Thanks for the advice! Using explicit paths I could narrow the files down to 7556 - which seems quite reasonable.

But after ~1800 files were processed, more than 25 GB of RAM is used. Is this normal or am I doing something wrong?

**Comment by JanWennrichPCSG** [comment] 2020-10-20 11:54
Now I tried to copy the php74 set to my rector.php file and removed all but one Rectors (see below) . But unfortunately I'm still running out of memory.

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Assign\NullCoalescingOperatorRector;
use Rector\Php74\Rector\Class_\ClassConstantToSelfClassRector;
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
use Rector\Php74\Rector\Double\RealToFloatTypeCastRector;
use Rector\Php74\Rector\FuncCall\ArrayKeyExistsOnPropertyRector;
use Rector\Php74\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector;
use Rector\Php74\Rector\FuncCall\FilterVarToAddSlashesRector;
use Rector\Php74\Rector\FuncCall\GetCalledClassToStaticClassRector;
use Rector\Php74\Rector\FuncCall\MbStrrposEncodingArgumentPositionRector;
use Rector\Php74\Rector\Function_\ReservedFnFunctionRector;
use Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector;
use Rector\Php74\Rector\MethodCall\ChangeReflectionTypeToStringToGetNameRector;
use Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Php74\Rector\StaticCall\ExportToReflectionFunctionRector;
use Rector\Renaming\Rector\FuncCall\RenameFunctionRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();

    $services->set(RenameFunctionRector::class)
        ->call('configure', [[
            RenameFunctionRector::OLD_FUNCTION_TO_NEW_FUNCTION => [
                #the_real_type
                # https://wiki.php.net/rfc/deprecations_php_7_4
                'is_real' => 'is_float',
                #apache_request_headers_function
                # https://wiki.php.net/rfc/deprecations_php_7_4
                'apache_request_headers' => 'getallheaders',
                //'hebrevc' => ['nl2br', 'hebrev'],
            ],
        ]]);
};
```

**Comment by TomasVotruba** [comment] 2020-10-20 12:50
> But after ~1800 files were processed, more than 25 GB of RAM is used. 

It seems like memory leak on 1 file. Try narrowing it down to diretctory or file.

Using `--debug` might help:

```php
vendor/bin/rector process src/Specific/Package --debug
```

I suspect it will be some PHP code, that loops itself in one of Rector rules.

**Comment by JanWennrichPCSG** [comment] 2020-10-23 10:04
Unfortunately I didn't had the time to narrow it down to a specific file. But after investigating the legacy code a bit more I found that there were many unused libraries and even applications (like phpMyAdmin) hidden in the depths of the directories. After cleaning that mess up a bit, there were only ~3k files left and the processing went without problems requiring "only" ~16GB of RAM.

**Comment by TomasVotruba** [comment] 2020-10-23 11:09
I see. The library directory should be excluded, like `/vendor`

**Comment by powtac** [comment] 2020-11-14 13:35
I discovered that even commented code counts into memory usage! Probably because php-parser collects this information. Maybe the halt compiler directive would be a solution to this.

**Comment by TomasVotruba** [comment] 2020-11-14 18:33
We need reproducible code.

**Comment by TomasVotruba** [comment] 2020-11-30 23:28
Closing as reproducible repository is needed.

**Closed by TomasVotruba** 2020-11-30 23:28 UTC
Labels: support, test-fixture-needed
