### ISSUE TITLE
Rector fails to convert dataProvider annotation to #[DataProvider] attribute for PHPUnit 10

### ISSUE THREAD

**Issue by rpkamp** [rectorphp/rector#8360] opened 2023-12-14 10:01 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.2 |

When running Rector with the  `\Rector\PHPUnit\Set\PHPUnitSetList::PHPUNIT_100` set list, `@test` is rewritten to `#[Test]` just fine, but all `@dataProvider` are left alone. 

Downgrading to version 0.17.0 and running the same config the `@dataProvider`s are correctly rewritten to `#[DataProvider]`

## Minimal PHP Code Causing Issue
https://getrector.com/demo/4e928445-1701-46ea-a4a4-191a115f82bb

## Expected Behaviour
Rector should rewrite `@dataProvider` to `#[DataProvider]`

**Comment by samsonasik** [comment] 2023-12-26 14:28
I create PR 

- https://github.com/rectorphp/rector-phpunit/pull/300

for it.

**Comment by samsonasik** [comment] 2023-12-26 14:30
Ok, that seems due to class not extending `\PHPUnit\Framework\TestCase`, change the class to extends `\PHPUnit\Framework\TestCase` resolve it, see

https://getrector.com/demo/9de0dba6-ad8c-4c81-96d0-adfe1e6cf139

I am closing it as it is not a bug.

**Closed by samsonasik** 2023-12-26 14:30 UTC
Labels: bug

**Comment by rpkamp** [comment] 2024-01-09 14:50
@samsonasik could you please try it on a bigger codebase? I agree that the example doesn't work, but I've ran into the same issue on a real life project.

**Comment by caricare2** [comment] 2024-09-03 18:07
I ran into this same issue and finally figured out the problem, figured I'd post here in case someone else runs into it. If your test extends a custom test class, which extends TestCase, and the custom test class is not in one of the paths rector is set to scan, it will ignore the dataProviders.

We ran into this because our base test cases are in a separate directory that wasn't included in our scan path. When I changed it to include that directory in our scan path, the dataProviders were detected.
