### ISSUE TITLE
Do I need the highest PHP version to downgrade?

### ISSUE THREAD

**Issue by shyim** [rectorphp/rector#6419] opened 2021-05-15 12:41 UTC
# Question

I would give the downgrade possibility a try and got fast a hidden error: 
````
Analyze error: "ParseError (syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)) thrown while looking for class Frosh\MailArchive\Controller\Api\MailResendController."
```

From the internal error, I assume that I will need PHP 8.0 on cli to downgrade the code from 8.0 to 7.4? Is that right?

Maybe makes sense to check the used PHP version in the CLI then when that set / etc is active 🤔

**Comment by shyim** [comment] 2021-05-15 12:50
Hmm after using PHP 8 on the CLI it works. An RuntimeException would be awesome when the running PHP is below the set

**Comment by sabbelasichon** [comment] 2021-05-15 13:00
If you want to downgrade from PHP 8 to PHP 7.4 PHP 8 is needed. True. 
Could you provide a solution for better / clearer communication?

**Comment by shyim** [comment] 2021-05-15 19:38
Hmm difficult as the set used doesn't matter. Maybe extending the error with a message like: `The file couldn't be parsed. This could be a Syntax error or the used PHP to run rector can't read the file. `

Btw: Should the Reflection Class stuff doesn't execute the PHP code? 🤔

**Comment by sabbelasichon** [comment] 2021-05-15 19:56
We are using Static Reflection here, so no execution involved.

**Comment by TomasVotruba** [comment] 2021-05-15 20:03
The downgrade should work even from version bellow.
It's possible Rector is autoloading projects' vendor/autoload.php. Then the class is invoked from the project and not loaded by static reflection.

Could you provide minimal reproducible repository with failing Github action with the downgrade? We'll be able to help then

**Comment by sabbelasichon** [comment] 2021-05-18 19:22
I am surprised, that this is possible. Downgrade from PHP 8 to let´s say to PHP 7.4 by running 7.4. Is this possible due to static reflection? Otherwise i would say, we can close this issue here.

**Comment by shyim** [comment] 2021-05-18 19:56
I have packed it as zip. I tried `debug_print_backtrace()` but couldn't find a caller.

Zip: https://drive.google.com/file/d/183efpMwiW2nmUWz_kfRq92IqOR5OMlMd/view?usp=sharing

Unpack it and run: rector process -c rector.php src/  -a vendor/autoload.php -vvv
You will see then the error: [printing skipped due error] src/Controller/Api/MailResendController.php on PHP 7.4 and with 8.0 it works

**Comment by TomasVotruba** [comment] 2021-05-18 22:12
@shyim At the moment we'll stick with a practise to use the same PHP we downgrade code. The `composer install` must run on such project anyway. If you don't have such PHP locally and that's a blockre, you can use the GitHub Actions like we do in Rector.


> Downgrade from PHP 8 to let´s say to PHP 7.4 by running 7.4. Is this possible due to static reflection? Otherwise i would say, we can close this issue here.

Agreed, we can close it.

**Closed by TomasVotruba** 2021-05-18 22:12 UTC
