### ISSUE TITLE
Cannot run against php5.6 project using docker

### ISSUE THREAD

**Issue by sinnbeck** [rectorphp/rector#5629] opened 2021-02-20 11:44 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Latest docker              |
| Installed as   | docker                          |

When I try running it against my codebase I get the following error
```
Fatal error: Declaration of Symfony\Component\HttpKernel\Config\FileLocator::locate(string $file, ?string $currentPath = null, bool $first = true) must be compatible with Symfony\Component\Config\FileLocator::locate($name, $currentPath = null, $first = true) in /rector/vendor/symfony/http-kernel/Config/FileLocator.php on line 36
```
I run it using this command
```
docker run -e ENVIRONMENT=docker_testing --rm --user $(id -u):$(id -g) -v $(pwd):/project rector/rector:latest process tests/platform \
    --config rector.php \
    --dry-run
```
I have also tried using docker pull to ensure I have the latest image

## Expected Behaviour

I would expect it to handle the dependencies.

**Comment by TomasVotruba** [comment] 2021-02-20 11:48
Duplicate of https://github.com/rectorphp/rector/issues/5593

**Closed by TomasVotruba** 2021-02-20 11:48 UTC
Labels: bug
