### ISSUE TITLE
Upgrading PHPStan 1.10.50 => 1.10.55 causes Rector 0.18 to die

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#8404] opened 2024-01-15 15:48 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.13             |

A plurality of files in my project emit the following error:

>t/AppDetails/TeamMapping.php" file, due to:
         "Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getRequireExtendsTagValues()". On line:
         328

(Yes, the beginning of every error message is truncated like that, for some reason).

I see this error about 50 times, each for the same function call (`getRequireExtendsTagValues`) on the same line (328), for many different files in my project.

## Minimal PHP Code Causing Issue

>rector process --config=config/rector.php --dry-run

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/../src',
        __DIR__ . '/../tests',
    ]);

    $rectorConfig->ruleWithConfiguration(AnnotationToAttributeRector::class, [new AnnotationToAttribute(Route::class)]);
    $rectorConfig->rule(ReadOnlyClassRector::class);
    $rectorConfig->rule(ReadOnlyPropertyRector::class);
};
```

## Expected Behaviour

Rector does not die with a gorillion error messages.

**Comment by samsonasik** [comment] 2024-01-15 15:50
You need to update to latest rector `^0.19`, you can update your composer.json to require it:

```php
"rector/rector": "^0.19.0"
```

**Comment by Bilge** [comment] 2024-01-15 15:56
Hi @samsonasik and thanks for the prompt reply. Yes, that does seem to "fix" it up to a point, however it now fails with a completely unrelated error: 

> [ERROR] Could not process "vendor\rector\rector\vendor\symplify\easy-parallel\src\ValueObject\ParallelProcess.php" file, due to:
         "Child process timed out after 60 seconds". On line: 108

Notwithstanding that other error, it should not be necessary to upgrade Rector just to get it to work with PHPStan. That is, if Rector 0.18 is not compatible with PHPStan 1.10.56, then it should be stated in its `composer.json` to prevent downloading an incompatible version. However, I will note that since it _is_ compatible with 1.10.50, it seems this is really a failing of PHPStan's adherence to the semantic versioning promise.

**Comment by samsonasik** [comment] 2024-01-15 16:05
Rector 0.19.0 parallel config is default to `60, 32, 20` value, You can update to old config:

```php
$rectorConfig->parallel(120, 16, 15);
```

or configure with your resource.

**Comment by Bilge** [comment] 2024-01-15 16:18
OK, that does "work", but now Rector total compute time has increased from 20 seconds (0.18) to 1m15s (0.19) which is unacceptable.

**Comment by samsonasik** [comment] 2024-01-15 16:27
The issue is may probably on dependency itself, eg: on new PHPStan 1.10.55, the process got slower, so less in rector side can do. 

If you can provide a github repo that show the slow part, we probably can lookup possible improvement in rector side.

**Comment by Bilge** [comment] 2024-01-15 16:30
I was just about to post a note that the incompatibility was introduced in 1.10.55. Interesting that the slowness also came from that (minor) version.

Unfortunately, I have no public source to share, and since Rector provides no stats, I don't even know which file is slow. However, from memory, Rector first became slow when I introduced a really big enumeration into my project (i.e. with almost 1000 members). However, the slowness eventually got fixed when I upgraded to 0.18. Now it seems to be back again in 0.19, and I suspect it may be due to the same files (with no other evidence to base my assumptions on).

**Comment by samsonasik** [comment] 2024-01-15 16:32
I apply some performance improvement on latest dev-main, could you try update to "rector/rector": "dev-main" ? 

Otherwise, the slowness may probably by PHPStan 1.10.55 itself.

**Comment by Bilge** [comment] 2024-01-15 16:41
`dev-main` does not help, and neither does keeping PHPStan back at `1.10.54`. That is, any version of Rector 0.19 is slow for me, and since downgrading PHPStan does not affect it, I don't think the problem is with PHPStan.

**Comment by samsonasik** [comment] 2024-01-15 17:08
That's complex, that can also possibly caused by phpstan-phpdoc-parser itself with new method addition that it relied on phpstan 1.10.55.

Feel free to provide patch on the path that possibly cause memory leak.

**Comment by Bilge** [comment] 2024-01-15 17:29
Sorry, I didn't understand your last post, and still don't, no matter how many times I re-read it. Can you clarify?

**Comment by samsonasik** [comment] 2024-01-15 17:35
The `PhpDocNode::getRequireExtendsTagValues()` is exists since last PHPStan which require the latest https://github.com/phpstan/phpdoc-parser so it can possibly from there.

**Comment by staabm** [comment] 2024-01-15 19:30
A reproducer for the slow analysis would be great

**Comment by Bilge** [comment] 2024-01-15 20:49
Considering Rector doesn't emit any timing information, or anything even remotely useful even with the `--debug` flag, I'm really not sure how I could begin to piece together a reproduction case.

**Comment by TomasVotruba** [comment] 2024-01-15 22:05
That would be work of debug tools like `xdebug` or Blackfire.

Only if you can provide repository with leaking files + rules, we can do something about it.

I personally use this technique to find these spots within our projects: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

Closing as solution is to upgrade to 0.19.1 :+1:

**Closed by TomasVotruba** 2024-01-15 22:05 UTC
Labels: bug

**Comment by Bilge** [comment] 2024-01-15 22:10
I can provide a cachegrind file if you would actually use it without a repro repo.
