### ISSUE TITLE
Cannot redeclare PHPStan\dumpType

### ISSUE THREAD

**Issue by cmodijk** [rectorphp/rector#4667] opened 2020-11-20 20:18 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `0.8.52`             |
| Installed as   |  prefixed                    |

I'm getting the following error. 

```
PHP Fatal error:  Cannot redeclare PHPStan\dumpType() (previously declared in phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/phpstan/phpstan-src/src/dumpType.php:9) in phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/src/dumpType.php on line 9
PHP Stack trace:
PHP   1. {main}() /var/www/testvendor/rector/rector-prefixed/rector:0
PHP   2. require() /var/www/testvendor/rector/rector-prefixed/rector:6
PHP   3. _HumbugBox9a2b3b20a128\AutoloadIncluder->includeDependencyOrRepositoryVendorAutoloadIfExists() phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector:33
PHP   4. _HumbugBox9a2b3b20a128\AutoloadIncluder->loadIfNotLoadedYet() phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector:94
PHP   5. require_once() phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector:143
PHP   6. class_exists() phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php:17
PHP   7. spl_autoload_call() phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php:17
PHP   8. {closure:/var/www/testvendor/phpstan/phpstan/bootstrap.php:3-46}() phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php:17
PHP   9. require() /var/www/testvendor/phpstan/phpstan/bootstrap.php:15
PHP  10. ComposerAutoloaderInit39ad42db351bea2a943d1d6e2a10c40a::getLoader() phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/vendor/autoload.php:9
PHP  11. composerRequire39ad42db351bea2a943d1d6e2a10c40a() phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/vendor/composer/autoload_real.php:50

Fatal error: Cannot redeclare PHPStan\dumpType() (previously declared in phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/phpstan/phpstan-src/src/dumpType.php:9) in phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/src/dumpType.php on line 9

Call Stack:
    0.0175     394472   1. {main}() /var/www/testvendor/rector/rector-prefixed/rector:0
    0.1055    7432656   2. require('phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector') /var/www/testvendor/rector/rector-prefixed/rector:6
    0.1065    7507808   3. _HumbugBox9a2b3b20a128\AutoloadIncluder->includeDependencyOrRepositoryVendorAutoloadIfExists() phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector:33
    0.1066    7508176   4. _HumbugBox9a2b3b20a128\AutoloadIncluder->loadIfNotLoadedYet() phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector:94
    0.1076    7829424   5. require_once('phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php') phar:///var/www/testvendor/rector/rector-prefixed/rector/bin/rector:143
    0.1230   12502552   6. class_exists() phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php:17
    0.1230   12502616   7. spl_autoload_call() phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php:17
    0.1231   12502680   8. {closure:/var/www/testvendor/phpstan/phpstan/bootstrap.php:3-46}() phar:///var/www/testvendor/rector/rector-prefixed/rector/vendor/autoload.php:17
    0.1687   15228408   9. require('phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/vendor/autoload.php') /var/www/testvendor/phpstan/phpstan/bootstrap.php:15
    0.1689   15236984  10. ComposerAutoloaderInit39ad42db351bea2a943d1d6e2a10c40a::getLoader() phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/vendor/autoload.php:9
    0.1712   15849816  11. composerRequire39ad42db351bea2a943d1d6e2a10c40a() phar:///var/www/testvendor/phpstan/phpstan/phpstan.phar/vendor/composer/autoload_real.php:50
```

## Minimal PHP Code Causing Issue

I just tested this in a clean dir

```bash
composer init
composer require --dev rector/rector-prefixed
composer require --dev phpstan/phpstan
./vendor/bin/rector
```

This is the generated `composer.json`

```json
{
    "require-dev": {
        "rector/rector-prefixed": "^0.8.52",
        "phpstan/phpstan": "^0.12.56"
    }
}
```

Maybe the prefixed version is old this seems to work but my project uses an older Symfony version so i need to use the prefixed version

```bash
composer init
composer require --dev rector/rector
composer require --dev phpstan/phpstan
./vendor/bin/rector
```
```json
{
    "require-dev": {
        "rector/rector": "^0.8.56",
        "phpstan/phpstan": "^0.12.56"
    }
}
```

The prefixed version is different than the normal version `0.8.52` v/s`0.8.56`?

**Comment by TomasVotruba** [comment] 2020-11-20 21:59
Duplicate of https://github.com/rectorphp/rector/issues/4606

**Closed by TomasVotruba** 2020-11-20 21:59 UTC
