### ISSUE TITLE
Rector prefixed version 0.7.17 is invalid

### ISSUE THREAD

**Issue by RiKap** [rectorphp/rector#3226] opened 2020-04-23 11:22 UTC
# Bug Report

It looks like that phar tagged as 0.7.17 contains dev version.

- Install rector: `composer require rector/rector-prefixed:0.7.17 --dev`
- Run `vendor/bin/rector --version`
- It returns `Rector 0.8.x-dev@05add9f`, but it should `Rector v0.7.17`

**Comment by shaal** [comment] 2020-04-23 11:28
I noticed the same thing.

**Comment by TomasVotruba** [comment] 2020-04-23 12:01
Any idea how to fix it?

**Comment by RiKap** [comment] 2020-04-23 16:57
It looks like that it is not automated. So I don't see anything to fix from my side.
I think that you should tag new version 0.7.18 (with valid code) and relase new prefixed version tagged as 0.7.18 too.

This issue is only in prefixed version tagged as 0.7.17.
I tested normal version and 0.7.17 is ok.

**Comment by TomasVotruba** [comment] 2020-04-23 17:39
I tried new release: https://github.com/rectorphp/rector/releases/tag/v0.7.18

Let me know if that helps.

**Comment by shaal** [comment] 2020-04-23 23:25
It still returns wrong value.

Using rector-prefixed 0.7.18, 
`rector --version`
```
Rector 0.8.x-dev@8896f0a
```

**Comment by TomasVotruba** [comment] 2020-04-25 09:59
Duplicate of #3256

**Closed by TomasVotruba** 2020-04-25 09:59 UTC
