### ISSUE TITLE
wrong return type of BoolReturnTypeFromBooleanConstReturnsRector

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#8935] opened 2024-12-13 15:24 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v2.0.3  |

## Minimal PHP Code Causing Issue

```php
<?php


final class DemoFile
{
    /**
     * Reset controller to a given one.
     *
     * @param string $controller
     *
     * @return no-return
     */
    public function reset_controller($controller)
    {
        if (!class_exists($controller, true)) {

            return false;
        }
        echo 'ABC';
        exit;
    }
}

```

actual wrong diff:
```diff
-    public function reset_controller($controller)
+    public function reset_controller($controller): bool
     {

```

## Expected Behaviour

no return type added

**Comment by samsonasik** [comment] 2024-12-13 15:42
Reproduced at https://getrector.com/demo/1fbdf68d-77be-4eb8-ab97-1088e8b6af57

**Comment by samsonasik** [comment] 2024-12-13 15:49
@stabm hm.., actually, return type should be ok, since it returns false, or exit, exit/throw means it stopped, which doesn't invalidate return type.

see https://3v4l.org/4IvAO vs https://3v4l.org/IifRm

**Comment by samsonasik** [comment] 2024-12-13 15:56
I am closing as expected,  exit/throw means it stopped and doesn't invalidate return type. 

The `@return no-return` should be fixed instead, see https://phpstan.org/r/24345cdc-eb42-4c32-959a-a1a58aa55bed

**Closed by samsonasik** 2024-12-13 15:56 UTC
Labels: bug
