### ISSUE TITLE
Error: describe() on null

### ISSUE THREAD

**Issue by matbech** [rectorphp/rector#8835] opened 2024-09-22 01:43 UTC
Rector 1.2.5

## Error
```
[ERROR] Could not process "C:\Projects\Web\www.test.com\htdocs\module\Application\src\Navigation\EmptyPage.php"

                                                on describe() on null"


         #0
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/VerbosityLevel.php
         (161):
         PHPStan\Type\Generic\TemplateObjectType->{closure:PHPStan\Type\Generic\TemplateTypeTrait::describe():68}()
         #1
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/Generic/TemplateTy
         peTrait.php(68): PHPStan\Type\VerbosityLevel->handle(Object(Closure), Object(Closure), Object(Closure))
         #2
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(425
         ): PHPStan\Type\Generic\TemplateObjectType->describe(Object(PHPStan\Type\VerbosityLevel))
         #3
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(274
         ): PHPStan\Type\ObjectType->describeCache()
         #4
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/TypeCombinator.php
         (373): PHPStan\Type\ObjectType->isSuperTypeOf(Object(PHPStan\Type\Generic\TemplateObjectType))
         #5
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/TypeCombinator.php
         (248): PHPStan\Type\TypeCombinator::compareTypesInUnion(Object(PHPStan\Type\Generic\TemplateObjectType),
         Object(PHPStan\Type\ObjectType))
         #6
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver
         .php(460): PHPStan\Type\TypeCombinator::union(Object(PHPStan\Type\Generic\TemplateObjectType),
         Object(PHPStan\Type\ArrayType), Object(PHPStan\Type\ObjectType))
         #7
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver
         .php(170):
         PHPStan\PhpDoc\TypeNodeResolver->resolveUnionTypeNode(Object(PHPStan\PhpDocParser\Ast\Type\UnionTypeNode),
         Object(PHPStan\Analyser\NameScope))
         #8
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocNodeResolv
         er.php(271): PHPStan\PhpDoc\TypeNodeResolver->resolve(Object(PHPStan\PhpDocParser\Ast\Type\UnionTypeNode),
         Object(PHPStan\Analyser\NameScope))
         #9
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/ResolvedPhpDocBl
         ock.php(504):
         PHPStan\PhpDoc\PhpDocNodeResolver->resolveParamTags(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode),
         Object(PHPStan\Analyser\NameScope))
         #10
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/ResolvedPhpDocBl
         ock.php(277): PHPStan\PhpDoc\ResolvedPhpDocBlock->getParamTags()
         #11
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanc
         eResolver.php(56): PHPStan\PhpDoc\ResolvedPhpDocBlock->merge(Array, Array)
         #12
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanc
         eResolver.php(42):
         PHPStan\PhpDoc\PhpDocInheritanceResolver->docBlockTreeToResolvedDocBlock(Object(PHPStan\PhpDoc\PhpDocBlock),
         NULL, 'addPage', NULL, NULL)
         #13
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpClass
         ReflectionExtension.php(548): PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod('/**\n * Adds
         a p...', 'C:\\Projects\\Web...', Object(PHPStan\Reflection\ClassReflection), NULL, 'addPage', Array)
         #14
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpClass
         ReflectionExtension.php(521):
         PHPStan\Reflection\Php\PhpClassReflectionExtension->createUserlandMethodReflection(Object(PHPStan\Reflection\
         ClassReflection), Object(PHPStan\Reflection\ClassReflection),
         Object(PHPStan\Reflection\Php\NativeBuiltinMethodReflection), NULL)
         #15
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpClass
         ReflectionExtension.php(336):
         PHPStan\Reflection\Php\PhpClassReflectionExtension->createMethod(Object(PHPStan\Reflection\ClassReflection),
         Object(PHPStan\Reflection\Php\NativeBuiltinMethodReflection), true)
         #16
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflect
         ion.php(539):
         PHPStan\Reflection\Php\PhpClassReflectionExtension->getMethod(Object(PHPStan\Reflection\ClassReflection),
         'addPage')
         #17
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(595
         ): PHPStan\Reflection\ClassReflection->getMethod('addPage', Object(PHPStan\Analyser\MutatingScope))
         #18
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(572
         ): PHPStan\Type\ObjectType->getUnresolvedMethodPrototype('addPage', Object(PHPStan\Analyser\MutatingScope))
         #19
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.
         php(3912): PHPStan\Type\ObjectType->getMethod('addPage', Object(PHPStan\Analyser\MutatingScope))
         #20
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.
         php(1616): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'addPage',
         Object(PhpParser\Node\Expr\MethodCall))
         #21
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.
         php(1622): PHPStan\Analyser\MutatingScope->{closure:PHPStan\Analyser\MutatingScope::resolveType():1615}()
         #22
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.
         php(600): PHPStan\Analyser\MutatingScope->resolveType('$this->parent->...',
         Object(PhpParser\Node\Expr\MethodCall))
         #23
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(1798): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
         #24
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(724):
         PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\MethodCall),
         Object(PHPStan\Analyser\MutatingScope))
         #25
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression),
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #26
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(838): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\If_), Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #27
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_),
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #28
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(652): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod),
         Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #29
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),
         Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
         Object(PHPStan\Analyser\StatementContext))
         #30
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(789): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,
         Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
         Object(PHPStan\Analyser\StatementContext))
         #31
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #32
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(759): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_),
         Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #33
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(429): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_),
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #34
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(288): PHPStan\Analyser\NodeScopeResolver->processNodes(Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #35
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(260):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes(Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #36
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\NodeScopeAndMetadataDecorato
         r.php(43): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array,
         'C:\\Projects\\Web...')
         #37 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\PhpParser\AstResolver.php(298):
         Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile('C:\\Projects\\Web...', Array)
         #38 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\PhpParser\AstResolver.php(112):
         Rector\PhpParser\AstResolver->parseFileNameToDecoratedNodes('C:\\Projects\\Web...')
         #39
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\rules\Php80\Rector\ClassMethod\AddParamBasedOnPar
         entClassMethodRector.php(132):
         Rector\PhpParser\AstResolver->resolveClassMethodFromMethodReflection(Object(PHPStan\Reflection\Php\PhpMethodR
         eflection))
         #40 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Rector\AbstractRector.php(139):
         Rector\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector->refactor(Object(PhpParser\Node\Stmt\C
         lassMethod))
         #41
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(178): Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #42
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray(Array)
         #43
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(198): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #44
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray(Array)
         #45
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(198): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #46
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(85): PhpParser\NodeTraverser->traverseArray(Array)
         #47
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.p
         hp(47): PhpParser\NodeTraverser->traverse(Array)
         #48 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\FileProcessor.php(113):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #49
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(184)
         : Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #50
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(161)
         : Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #51
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(138)
         : Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),
         Object(Closure), Object(Closure))
         #52 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Console\Command\ProcessCommand.php(149):
         Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration),
         Object(RectorPrefix202409\Symfony\Component\Console\Input\ArgvInput))
         #53
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202409\Symfony\Component\Console\Input\Argv
         Input), Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #54 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202409\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202409\Symfony\Component
         \Console\Input\ArgvInput), Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #55 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202409\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessC
         ommand), Object(RectorPrefix202409\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #56 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202409\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202409\Symfony\Component\C
         onsole\Input\ArgvInput), Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #57 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202409\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #58 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\bin\rector.php(130):
         RectorPrefix202409\Symfony\Component\Console\Application->run()
         #59 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\bin\rector(5):
         require_once('C:\\Projects\\Web...')
         #60 C:\Projects\Web\www.test.com\htdocs\vendor\bin\rector(119): include('C:\\Projects\\Web...')
         #61 {main}". On line: 69
```

## PHP file
```
<?php
declare(strict_types=1);

namespace Application\Navigation;

class EmptyPage extends \Laminas\Navigation\Page\AbstractPage
{
	// override
	public function getHref()
	{
		// return an empty string instead of null because the phpdoc in AbstractPage says the method returns a string
		return '';
	}
}
```

**Comment by samsonasik** [comment] 2024-09-22 02:01
Could you create reproducible demo for it at https://getrector.com/demo ?

I tried at https://getrector.com/demo/cb87107a-e91a-40d9-8e93-9b13a37d48f6 and can't reproduce. Thank you.

**Comment by matbech** [comment] 2024-09-22 02:35
I have downgraded from PHP 8.4.0 Beta 5 to PHP 8.3 and I can no longer reproduce the issue. It looks like PHP 8.4 has something to do with it.

**Comment by samsonasik** [comment] 2024-09-22 02:42
Ok, closing then ;) PHP 8.4 is not released so I think phpstan will catch up ;)

**Closed by samsonasik** 2024-09-22 02:42 UTC
Labels: bug
