### ISSUE TITLE
Arrow function on void method 

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector#5235] opened 2021-01-19 12:55 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.10             |
| Installed as   | composer dependency                        |

Calling an arrow function with a void method crashes rector

## Minimal PHP Code Causing Issue

https://getrector.org/demo/ef725295-8234-4fa5-a9a1-b964819138d0

## Expected Behaviour

It analyses the code

**Comment by olivernybroe** [comment] 2021-01-19 12:57
This scenario is pretty common when using a collection. 

```php
collect($data)->each(fn($input) => $input->voidFunction());

```
We already know that each ignores the return data, so it's safe to call it as an arrow function it's easier to read.

**Comment by TomasVotruba** [comment] 2021-01-19 14:49
We'll need a failing test case in one of rules to verify this will be fixed

**Comment by olivernybroe** [comment] 2021-01-20 05:58
@TomasVotruba my rector demo link is not good enough?

**Comment by TomasVotruba** [comment] 2021-01-20 11:15
Demo link is better than nothing, but failing test is require to confirm it for sure.
Also with test we are sure the regression won't happen.

**Comment by olivernybroe** [comment] 2021-01-25 08:42
@TomasVotruba So I see that the rector it fails on is `RemoveDuplicatedArrayKeyRector`, however I don't really see a test added for arrow functions returning null on that rector as valuable. 

Not really sure where to add in the test...

<details>
<summary>Stack Trace</summary>

```
Rector 0.9.10
Config file: rector.php

[parsing] app/Services/Economic/Tasks/CreateJournalEntryTask.php
[refactoring] app/Services/Economic/Tasks/CreateJournalEntryTask.php
    [applying] Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector
    [applying] Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector
    [applying] Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
    [applying] Rector\DeadCode\Rector\Property\RemoveSetterOnlyPropertyAndMethodCallRector
    [applying] Rector\DeadCode\Rector\PropertyProperty\RemoveNullPropertyInitializationRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector
    [applying] Rector\PHPUnit\Rector\ClassMethod\RemoveEmptyTestMethodRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveDuplicatedIfReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDeadRecursiveClassMethodRector
    [applying] Rector\DeadCode\Rector\Expression\RemoveDeadStmtRector
    [applying] Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveAssignOfVoidReturnFunctionRector
    [applying] Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector
    [applying] Rector\DeadCode\Rector\MethodCall\RemoveEmptyMethodCallRector
    [applying] Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector
    [applying] Rector\DeadCode\Rector\If_\SimplifyIfElseWithSameContentRector
    [applying] Rector\DeadCode\Rector\If_\RemoveUnusedNonEmptyArrayBeforeForeachRector
    [applying] Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector
[post rectors] app/Services/Economic/Tasks/CreateJournalEntryTask.php

In NodeTraverser.php line 168:
                                                      
  [LogicException]                                    
  leaveNode() returned invalid value of type integer  
                                                      

Exception trace:
  at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:168
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:146
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
 PhpParser\NodeTraverser->traverseArray() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:146
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
 PhpParser\NodeTraverser->traverseArray() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
 PhpParser\NodeTraverser->traverseArray() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
 PhpParser\NodeTraverser->traverseArray() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
 PhpParser\NodeTraverser->traverseNode() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
 PhpParser\NodeTraverser->traverseArray() at /Users/olivernybroe/Code/worksome-platform/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:91
 PhpParser\NodeTraverser->traverse() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/packages/post-rector/src/Application/PostFileProcessor.php:36
 Rector\PostRector\Application\PostFileProcessor->traverse() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Application/FileProcessor.php:165
 Rector\Core\Application\FileProcessor->postFileRefactor() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Application/RectorApplication.php:143
 Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure}() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Application/RectorApplication.php:227
 Rector\Core\Application\RectorApplication->tryCatchWrapper() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Application/RectorApplication.php:144
 Rector\Core\Application\RectorApplication->runOnFileInfos() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Console/Command/ProcessCommand.php:215
 Rector\Core\Console\Command\ProcessCommand->execute() at /Users/olivernybroe/Code/worksome-platform/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Console/Command/AbstractCommand.php:44
 Rector\Core\Console\Command\AbstractCommand->run() at /Users/olivernybroe/Code/worksome-platform/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /Users/olivernybroe/Code/worksome-platform/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/src/Console/ConsoleApplication.php:115
 Rector\Core\Console\ConsoleApplication->doRun() at /Users/olivernybroe/Code/worksome-platform/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/bin/rector.php:78
 require_once() at /Users/olivernybroe/Code/worksome-platform/vendor/rector/rector/bin/rector:4

```
</details>

**Comment by TomasVotruba** [comment] 2021-01-25 13:27
This might help
https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by olivernybroe** [comment] 2021-01-25 14:28
@TomasVotruba So I tried to follow your guide however no test file exist for this rector, so I had to add all of that in also. 

I couldn't get the test to working, as apparently the Rector class does not implement the rector interface... 
Created a PR with what I had

**Comment by TomasVotruba** [comment] 2021-01-25 14:45
Ah, I see. The `NodeRemovingRector` is generic rule that handles all the removal. It is not used directly.

The test must be added to responsible rule, one of `[applying]`

**Comment by olivernybroe** [comment] 2021-01-26 07:37
Hi @TomasVotruba,

I have updated my pr with a failing test now. 
It took awhile as I had to try all the rectors in the set one by one until I found the one that crashed. 

A good idea would be to improve this flow as it was rather tedious to figure out what rector is failing.

**Comment by TomasVotruba** [comment] 2021-01-26 08:56
Hi, thanks for the update.

This one is tricky, as nodes are removed in the end of whole process. When it happens right in the rule, it might colide with another removal rules.

> It took awhile as I had to try all the rectors in the set one by one until I found the one that crashed.

I see. Have you tried cutting half method? It usually takes 4-5 iteratorions to get the broken rule/part.

**Comment by olivernybroe** [comment] 2021-01-26 09:01
Yeah, I went with a binary search approach to find it 👍 

#5309 contains my failing test case. 
My thoughts were that it might at least be useful to store which rector wanted to remove the node, so you can output that data when verbose mode is on. 
Not sure if this is an issue that often happens, just thought it might be worth mentioning 😄 


Btw. it turned out that it was the RemoveEmpthyMethodCallRector

**Comment by TomasVotruba** [comment] 2021-01-26 15:28
> My thoughts were that it might at least be useful to store which rector wanted to remove the node, so you can output that data when verbose mode is on.

That could be doable.

Looking at https://github.com/rectorphp/rector/blob/87494ce3a69e73ea46b9a712197251aa3b7178fa/packages/node-removal/src/NodeRemover.php#L44, this happens already. But because of exception is probably fails

**Comment by olivernybroe** [comment] 2021-01-26 18:31
Ah so it's more a question about handling when things fail inside that rector I guess 🤔 
So it can output the rector name also.

**Closed** 2021-01-29 07:42 UTC
Labels: bug
