### ISSUE TITLE
Method `sprintf()` is not replaced by `\Safe\sprintf()`

### ISSUE THREAD

**Issue by OskarStark** [rectorphp/rector#5490] opened 2021-02-10 09:56 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.21 with PHP 8.0.1              |
| Installed as   | prefixed Rector                           |

Method `sprintf()` is not replaced by `\Safe\sprintf()`, a testcase already exists especially for this method 🤔 

## Minimal PHP Code Causing Issue

this is my file:
```php
<?php

declare(strict_types=1);

namespace App\Exception;

use App\Domain\Identifier\UserId;

/**
 * @author Oskar Stark <oskarstark@googlemail.com>
 */
final class UserNotFoundException extends NotFoundException
{
    public static function withUserId(UserId $userId): self
    {
        return new self(sprintf(
            'Cannot find User with UserId: %s',
            $userId->toString()
        ));
    }

    public static function withEmail(string $email): self
    {
        return new self(sprintf(
            'Cannot find User with email: %s',
            $email
        ));
    }
}
```

This is my config:
```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Generics\Rector\Class_\GenericsPHPStormMethodAnnotationRector;
use Rector\Renaming\Rector\FuncCall\RenameFunctionRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_80);

    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false);

    $parameters->set(Option::ENABLE_CACHE, false);

    $parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, getcwd() . '/phpstan-default.neon');

    // Define what rule sets will be applied
    $parameters->set(Option::SETS, [
        SetList::DEAD_DOC_BLOCK,
        SetList::PHP_80,
        SetList::PHPUNIT_91,
        SetList::SYMFONY_50_TYPES,
        SetList::SYMFONY_52,
    ]);

    // get services (needed for register a single rule)
    $services = $containerConfigurator->services();

    // register single rules
    /**
     * @see https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#genericsphpstormmethodannotationrector
     */
    $services->set(GenericsPHPStormMethodAnnotationRector::class);

    /**
     * @see https://github.com/thecodingmachine/safe/blob/master/rector-migrate-0.7.php
     */
    $services->set(RenameFunctionRector::class)
        ->call('configure', [[
            RenameFunctionRector::OLD_FUNCTION_TO_NEW_FUNCTION => [
                'sprintf' => 'Safe\sprintf',
            ],
        ]]);
};

```

## Expected Behaviour

```diff
diff --git a/src/Exception/UserNotFoundException.php b/src/Exception/UserNotFoundException.php
index 354c948..4393177 100644
--- a/src/Exception/UserNotFoundException.php
+++ b/src/Exception/UserNotFoundException.php
@@ -13,7 +13,7 @@ final class UserNotFoundException extends NotFoundException
 {
     public static function withUserId(UserId $userId): self
     {
-        return new self(sprintf(
+        return new self(\Safe\sprintf(
             'Cannot find User with UserId: %s',
             $userId->toString()
         ));
@@ -21,7 +21,7 @@ final class UserNotFoundException extends NotFoundException

     public static function withEmail(string $email): self
     {
-        return new self(sprintf(
+        return new self(\Safe\sprintf(
             'Cannot find User with email: %s',
             $email
         ));
```

**Comment by TomasVotruba** [comment] 2021-02-10 10:59
Hi,

we'll need a minimal failing demo link - https://getrector.org/demo
The config is way too huge now, something around 5-10 lines of code should do.

**Comment by OskarStark** [comment] 2021-02-10 11:21
* Sure, I shortened my config
* DI tried to add a demo, but something looks wrong:
![CleanShot 2021-02-10 at 12 21 27](https://user-images.githubusercontent.com/995707/107503695-8d054300-6b9a-11eb-92c3-4aa2f539fb0d.png)

**Comment by TomasVotruba** [comment] 2021-02-10 11:44
> DI tried to add a demo, but something looks wrong:

Seems like `mail()` is called on the background. Could you narrow it to 1 PHP line?

**Comment by OskarStark** [comment] 2021-02-10 11:48
Done: https://getrector.org/demo/dbc1ad3e-4ec4-4f84-abcb-b36c6ddde465

**Comment by TomasVotruba** [comment] 2021-02-10 15:36
Thanks!

I've narrowed down the config too:
https://getrector.org/demo/0592e36c-2123-4f1a-b7ac-18bdcb0110fa

It's seems it's caused by combination of these 2 sets and the function rule.

**Comment by OskarStark** [comment] 2021-02-10 16:01
So this can be considered a bug?

**Comment by TomasVotruba** [comment] 2021-02-10 16:40
Yes. Are you able to figure which rules from those 2 sets causes this collision?

**Comment by OskarStark** [comment] 2021-02-10 19:23
It only occurs when using the `SetList::SYMFONY_52` set.

I will check which rule is it....

**Comment by OskarStark** [comment] 2021-02-10 19:37
Ok if I add all rules from the set manually it works:

https://getrector.org/demo/b724fc2e-d721-4f40-9feb-f0bb61d274e2

**Comment by TomasVotruba** [comment] 2021-02-10 22:03
We'll need to find out the coliding point, where this breaks. It will be some combination of rules from `SYMFONY_52` and `PHP_80`

**Comment by samsonasik** [comment] 2021-02-16 15:28
It seems already fixed in dev-master https://getrector.org/demo/13114bca-1a55-4fc9-82a9-51eadaab3cbd

Closing.

**Closed by samsonasik** 2021-02-16 15:28 UTC
Labels: bug

**Comment by OskarStark** [comment] 2021-02-17 12:19
Thanks, can we please get a release? 🙏

**Comment by OskarStark** [comment] 2021-02-22 12:26
When can we expect a release please? Thanks"

**Comment by samsonasik** [comment] 2021-02-22 12:31
It seems already included in latest release, please try latest version.

**Comment by OskarStark** [comment] 2021-02-23 06:11
Indeed, it works, thanks 👍 

Is there a way to get it fixed with:
```
use function Safe\sprintf;
```

instead of:
```
use Safe\sprintf;
```

❓

**Comment by samsonasik** [comment] 2021-02-23 08:19
that seems related with this failing test PR https://github.com/rectorphp/rector/pull/5520
