### ISSUE TITLE
Rector prefixed build error

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6176] opened 2021-04-20 13:59 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main              |
| Installed as   | github action at https://github.com/rectorphp/rector-prefixed                         |

## Minimal PHP Code Causing Issue

On PHP 7.0: 

```bash
PHP Fatal error:  Uncaught TypeError: Return value of RectorPrefix20210420\AutoloadIncluder::loadIfExistsAndNotLoadedYet() must be an instance of RectorPrefix20210420\void, none returned in /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php:92
Stack trace:
#0 /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php(58): RectorPrefix20210420\AutoloadIncluder->loadIfExistsAndNotLoadedYet('/home/runner/wo...')
#1 /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php(23): RectorPrefix20210420\AutoloadIncluder->includeDependencyOrRepositoryVendorAutoloadIfExists()
#2 /home/runner/work/rector-prefixed/rector-prefixed/bin/rector(5): require_once('/home/runner/wo...')
#3 {main}
  thrown in /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php on line 92
Fatal error: Uncaught TypeError: Return value of RectorPrefix20210420\AutoloadIncluder::loadIfExistsAndNotLoadedYet() must be an instance of RectorPrefix20210420\void, none returned in /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php:92
Stack trace:
#0 /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php(58): RectorPrefix20210420\AutoloadIncluder->loadIfExistsAndNotLoadedYet('/home/runner/wo...')
#1 /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php(23): RectorPrefix20210420\AutoloadIncluder->includeDependencyOrRepositoryVendorAutoloadIfExists()
#2 /home/runner/work/rector-prefixed/rector-prefixed/bin/rector(5): require_once('/home/runner/wo...')
#3 {main}
  thrown in /home/runner/work/rector-prefixed/rector-prefixed/bin/rector.php on line 92
```

On PHP 7.1+ (since https://github.com/rectorphp/rector-prefixed/commit/c948e8c9f7d70cca23325dbd7ac2c51875f174fc yesterday)

```bash
PHP Fatal error:  Declaration of RectorPrefix20210420\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210420\Psr\Container\ContainerInterface::has($id) in /home/runner/work/rector-prefixed/rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 25

Fatal error: Declaration of RectorPrefix20210420\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210420\Psr\Container\ContainerInterface::has($id) in /home/runner/work/rector-prefixed/rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 25
Error: Process completed with exit code 255.
```

**Comment by samsonasik** [comment] 2021-04-20 14:16
On PHP 7.1, it seems string declaration parent child check not works on trait: 

https://github.com/rectorphp/rector-prefixed/blob/056cdf6b69602977e4227fe74e2c8b55ecb26c7f/vendor/symfony/service-contracts/ServiceLocatorTrait.php#L41 

Possibly related to https://github.com/rectorphp/rector/pull/5995 by @leoloso

**Comment by leoloso** [comment] 2021-04-20 14:41
Actually, I've just solved exactly the same issue today, for my project.

The issue is this one: #4816

Whenever the implemented code is in a trait, `DowngradeParameterTypeWideningRector` doesn't modify it. However, elsewhere code is being modified. Then, the method in the interface has the typehint removed, but that same method in the class, when provided via a trait, is kept as it is. Boom! 💣 

The issue is that, even if traits are not common, you only need one instance happening for the whole project to fail downgrading. And Symfony uses traits! So it's a rather serious issue.

What I did in my own project, is to ["manually" fix the methods](https://github.com/leoloso/PoP/blob/d1faaf504635fb4778ca858f68f1540a6bf91431/ci/downgrades/rector-downgrade-code-shared.php#L46-L58):

```php
$services = $containerConfigurator->services();
$services->set(AddParamTypeDeclarationInTraitRector::class)
    ->call('configure', [[
        AddParamTypeDeclarationInTraitRector::PARAMETER_TYPEHINTS => ValueObjectInliner::inline([
            new AddParamTypeDeclaration(AbstractAdapterTrait::class, 'clear', 0, new NullType()),
            new AddParamTypeDeclaration(ServiceLocatorTrait::class, 'has', 0, new NullType()),
            new AddParamTypeDeclaration(ServiceLocatorTrait::class, 'get', 0, new NullType()),
            // The type for this param is being removed, add it again
            new AddParamTypeDeclaration(CacheTrait::class, 'get', 0, new StringType()),
            new AddParamTypeDeclaration(CacheTrait::class, 'get', 2, new NullType()),
            new AddParamTypeDeclaration(CacheTrait::class, 'get', 3, new NullType()),
        ]),
    ]]
);
```

Do you see that `new AddParamTypeDeclaration(ServiceLocatorTrait::class, 'has', 0, new NullType()),`? It's exactly the issue you're having. I'm basically manually removing the type for that parameter, on the trait.

For that I created a new rule [`AddParamTypeDeclarationInTraitRector`](https://github.com/leoloso/PoP/blob/f7606addeb8145e216e916897a6164c99f30a6ba/src/Extensions/Rector/TypeDeclaration/Rector/ClassMethod/AddParamTypeDeclarationInTraitRector.php), completely based on `AddParamTypeDeclarationRector`, which modifies code within a trait.

Now, this solution works, but it's clearly a hack. If you want to solve this issue properly, for everyone, without hacks, and without having to have failing code that is then patched in an ad-hoc manner, then I think you can check out my proposal from #4816

**Comment by TomasVotruba** [comment] 2021-04-23 18:00
Closing as duplicated of https://github.com/rectorphp/rector/issues/6192

The PHP 7.0 build is expected as WIP, see https://github.com/rectorphp/rector/issues/6079

**Closed by TomasVotruba** 2021-04-23 18:00 UTC
Labels: bug
