### ISSUE TITLE
RemoveExtraParametersRector removes all parameters

### ISSUE THREAD

**Issue by anibalsanchez** [rectorphp/rector#8809] opened 2024-08-27 10:02 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.4 |

The `RemoveExtraParametersRector` removes the mandatory parameter.

## Minimal PHP Code Causing Issue

INPUT

```php
        $query = $xtf0FDatabaseDriver->getQuery(true);
        $query->select('extension_id')
            ->from('#__extensions')
            ->where($xtf0FDatabaseDriver->qn('type').' = '.$xtf0FDatabaseDriver->q('component'))
            ->where($xtf0FDatabaseDriver->qn('element').' = '.$xtf0FDatabaseDriver->q($this->componentName));
        $xtf0FDatabaseDriver->setQuery($query);
```

`qn` is an alias of `quoteName` defined via a magic method. `public function __call($name, array $arguments)` calls 
`public function quoteName($name, $as = null)`

OUTPUT

```php
        $xtf0FDatabaseDriver = XTF0FPlatform::getInstance()->getDbo();
        $query = $xtf0FDatabaseDriver->getQuery(true);
        $query->select('extension_id')
            ->from('#__extensions')
            ->where($xtf0FDatabaseDriver->qn().' = '.$xtf0FDatabaseDriver->q())
            ->where($xtf0FDatabaseDriver->qn().' = '.$xtf0FDatabaseDriver->q());
        $xtf0FDatabaseDriver->setQuery($query);
```

I tried to create the isolated test case, but it didn't produce the same result.

## Expected Behaviour

Rector shouldn't drop the required parameters.

**Comment by samsonasik** [comment] 2024-08-27 14:40
That's usually due to some autoload not setup properly, ensure it setup properly, and it will works as is, see https://getrector.com/documentation/static-reflection-and-autoload

**Comment by samsonasik** [comment] 2024-09-01 13:45
closing as answered and needs reproducible code/config to make a fix.

**Closed by samsonasik** 2024-09-01 13:45 UTC
Labels: bug

**Comment by andreucorrea123** [comment] 2024-12-10 13:59
Even _if_ the autoloading is not properly configured, it makes no sense that Rector removes all parameters when it lacks information.

Precisely, when information is not available is when it should be as conservative as possible. This is a bug by all means, and not the fault of the user.
