### ISSUE TITLE
Vendor classes in PHPDoc are not prefixed by `RectorPrefix...`, making PHPStan fails

### ISSUE THREAD

**Issue by Kocal** [rectorphp/rector#6614] opened 2021-08-04 12:49 UTC
Hi! :wave: 

# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.42             |

## Minimal PHP Code Causing Issue

That's not reproducible on https://getrector.org/demo.

When creating a custom Rector by extending `AbstractRector`, using `$this->parameterProvider->...` to retrieve a parameter makes PHPStan fails because it does not know about `\Symplify\PackageBuilder\Parameter\ParameterProvider` class.

Indeed, this vendor class is prefixed by `RectorPrefix20210804` (see https://github.com/rectorphp/rector/blob/main/src/Rector/AbstractRector.php#L48) but is not when used in the phpdoc: https://github.com/rectorphp/rector/blob/main/src/Rector/AbstractRector.php#L78-L81:
![image](https://user-images.githubusercontent.com/2103975/128183941-2f35f70b-bed9-4782-8a3f-47135b2c1407.png)

The same issue applies to other vendor classes like `Symfony\Component\Console\Style\SymfonyStyle`, `Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser` or `Symplify\Skipper\Skipper\Skipper`.

## Expected Behaviour

The `@var` annotation should see its type prefixed by `RectorPrefix20210804` too.

**Comment by TomasVotruba** [comment] 2021-08-04 13:07
Hi,

thanks for reporting. In such case, the class should be excluded in `scoper.php`

**Comment by samsonasik** [comment] 2021-08-04 13:29
@Kocal could you provide patch for it? The code need to be added possibly can duplicate the following lines:

https://github.com/rectorphp/rector-src/blob/1f538c68717d8f04896c6c7a17ff9f761f230612/scoper.php#L105-L109

and update to `Symplify\PackageBuilder\Parameter\ParameterProvider` in next line. Then next process:

- run sh ./full_build.sh
- swith to your project, remove `vendor/rector/rector` content except `preload.php` and `bootstrap.php`.
- copy `rector-prefixed-downgraded` content into your project's `vendor/rector/rector` 
- re-run your custom rector.

**Comment by Kocal** [comment] 2021-08-05 16:34
Hi!

Yes I think I can provide a patch for that, a **big thank you** for the guidelines, that's much appreciated! :)

I will give it a try this week-end, thanks!

**Comment by TomasVotruba** [comment] 2021-08-09 08:36
Hi, I'm looking into this again and it seems the PHPStan needs a Rector autoload file.
Currently the Rector has own autoload that is only available to it's own code. Any other tool cannot access it via `vendor/autoload.php`.

This is blindshot, but you might want to include Rector autoload files it in `phpstan.neon` - https://phpstan.org/config-reference#bootstrap

```neon
parameters:
	bootstrapFiles:
		# https://github.com/rectorphp/rector/blob/main/vendor/autoload.php
		- vendor/rector/rector/vendor/autoload.php

		# https://github.com/rectorphp/rector/blob/main/vendor/scoper-autoload.php
		- vendor/rector/rector/vendor/scoper-autoload.php
```

**Comment by Kocal** [comment] 2021-08-10 07:34
Hi!

I've tried your solution but this does not work, PHPStan still does not known about `Symplify\PackageBuilder\Parameter\ParameterProvider.` class.

This does not look like a PHPStan issue, even with plain PHP, the class does not exist:
![image](https://user-images.githubusercontent.com/2103975/128825706-f9f6e3de-b611-47d4-b499-f867efd288cd.png)

On my side, I was able to write a php-scoper patcher which replace:
```php
/**
 * @var \Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser
 */

/**
 * @var \Symfony\Component\Console\Style\SymfonyStyle
 */

/**
 * @param \Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser $foo
 */

/**
 * @param \Symfony\Component\Console\Style\SymfonyStyle $bar
 */
```

to 
```php
/**
 * @var RectorPrefix20210802\Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser
 */

/**
 * @var RectorPrefix20210802\Symfony\Component\Console\Style\SymfonyStyle
 */

/**
 * @param RectorPrefix20210802\Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser $foo
 */

/**
 * @param RectorPrefix20210802\Symfony\Component\Console\Style\SymfonyStyle $bar
 */
```

but I don't think my solution is the best, I will rework that IMO.

**Comment by TomasVotruba** [comment] 2021-08-10 07:59
That was only my random rought guess. Could make reproducible repository? Might give it a try :)

**Comment by Kocal** [comment] 2021-08-10 09:03
I've just created https://github.com/Kocal/rector-6614. 

> I assume "AddRoutesToPages" is Rector rule without "Rector" suffix that you try to analyze?

Yep! I'm gonna rename it :)

**Comment by TomasVotruba** [comment] 2021-08-10 09:32
Thank you :+1:  Ah, I see it now. The Scoper does the scoping of use imports correctly:

https://github.com/rectorphp/rector/blob/3395b050ee823e78257beffa444ac2a19a07f609/src/Rector/AbstractRector.php#L50

But `@var` doc is not scoped correctly:

https://github.com/rectorphp/rector/blob/3395b050ee823e78257beffa444ac2a19a07f609/src/Rector/AbstractRector.php#L77-L80

This is probably bug in https://github.com/humbug/php-scoper

And would have to be resolved there or somehow in: https://github.com/rectorphp/rector-src/blob/main/scoper.php
Maybe your suggestion might help, but beware, not all "Symfony|Symplify" classes namespace are scoped:

fn (string $filePath, string $prefix, string $content): string => Strings::replace(
    $content,
    '#@(var|param) \\\\(Symplify|Symfony)\\\\([^ ]+)#',
    '@$1 \\\\' . $prefix . '\\\\$2\\\\$3'
),

**Comment by Kocal** [comment] 2021-08-10 09:47
Yeah, I think it would be better to write a fix for php-scoper, there is already an issue opened for phpdoc support https://github.com/humbug/php-scoper/issues/462

**Comment by TomasVotruba** [comment] 2021-08-21 11:17
Could you send PR to updated `scoper.php` here? The feedback from humbug/php-scoper is lagging weeks, so we can close it here

**Comment by Kocal** [comment] 2021-08-22 22:18
Yes, please see #739

**Comment by samsonasik** [comment] 2021-08-22 23:47
Re-open as has false positives https://github.com/rectorphp/rector-src/pull/739#issuecomment-903349730

**Comment by samsonasik** [comment] 2021-08-28 05:30
The issue on it seems because it change the `phpstan.phar` as well. The possible solution is to ensure the file is not `phpstan.phar` first:

```php
function (string $filePath, string $prefix, string $content): string {
    if (str_ends_with($filePath, '.phar')) {
         return $content;
    }

     return Strings::replace(
        $content,
        '#@(var|param) \\\\(Symplify|Symfony)\\\\([^ ]+)#',
       '@$1 \\\\' . $prefix . '\\\\$2\\\\$3'
    );
},
```

**Comment by samsonasik** [comment] 2021-08-28 07:16
I tried with the following config in scoper config but seems still not works:

```php
        function (string $filePath, string $prefix, string $content): string {
            if (str_ends_with($filePath, '.phar')) {
                return $content;
            }

            $matches = Strings::matchAll($content, '#@(var|param) \\\\(Symplify|Symfony)\\\\([^ ]+)#');

            if ($matches === []) {
                return $content;
            }

            foreach ($matches as $match) {
                // get first namespace, eg: Symplify
                $namespace    = $match[2];
                // get sub namespace, eg: PackageBuilder\Parameter\ParameterProvider
                $subNamespace = $match[3];

                $patternInUse = sprintf('#use %s\\\\%s\\\\%s#', $prefix, $namespace, $subNamespace);
                $exists       = Strings::match($content, $patternInUse);

                if (! $exists) {
                    continue;
                }

                $fromContent = sprintf('@%s \%s\%s', $match[1], $namespace, $subNamespace);
                $toContent   = sprintf('@%s \%s\%s\%s', $match[1], $prefix, $namespace, $subNamespace);

                $content = str_replace($fromContent, $toContent, $content);
            }

            return $content;
        },
```

**Comment by TomasVotruba** [comment] 2021-09-06 17:28
Closing as reverted to working state. The issue is in php-scoper itself, it should be fixed to avoid these per-project patches.

Thank you for the effort and exploration :+1:

**Closed by TomasVotruba** 2021-09-06 17:28 UTC
Labels: bug
