### ISSUE TITLE
PropertyTypeDeclarationRector reports wrong type

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#2522] opened 2019-12-29 14:07 UTC
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.6.4          |
| PHP version    | PHP 7.3                           |
| Full Command   | `rector process redaxo/src/core/lib --autoload-file phpstan-bootstrap.php`  | 

## Current Behaviour 

running rector thru https://github.com/redaxo/redaxo/blob/f30a0a6d669481b2789ecbfb21924185adbf2849/redaxo/src/core/lib/util/markdown.php#L108 leads to a `$ids` phpdoc of type `mixed[]`

I would expect a `bool[]` type

using rector.yaml:
```
# rector.yaml
services:
    Rector\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector: ~
```

**Comment by TomasVotruba** [comment] 2019-12-29 15:12
How do you deduce variable is always a bool?

**Comment by TomasVotruba** [comment] 2019-12-29 15:13
Please send failing test case to `PropertyTypeDeclarationRectorTest`

**Comment by staabm** [comment] 2019-12-29 17:32
There is only a single spot where we write into the property. That spot writes a `true`, see https://github.com/redaxo/redaxo/blob/f30a0a6d669481b2789ecbfb21924185adbf2849/redaxo/src/core/lib/util/markdown.php#L151

**Comment by TomasVotruba** [comment] 2019-12-29 19:27
Failing test case is still needed

**Comment by TomasVotruba** [comment] 2020-01-11 00:20
Closing as unable to reproduce.

**Closed by TomasVotruba** 2020-01-11 00:20 UTC
