### ISSUE TITLE
Doctrine Annotation to Attributes Bug report

### ISSUE THREAD

**Issue by tacman** [rectorphp/rector#7330] opened 2022-07-30 12:02 UTC
[rector_bug.zip](https://github.com/rectorphp/rector/files/9226215/rector_bug.zip)

Attached is a bug report, along with the source file and rector.php

**Comment by samsonasik** [comment] 2022-07-30 12:23
I guess you're on windows, it probably due to line ending issue ref https://github.com/nikic/PHP-Parser/issues/599

**Comment by tacman** [comment] 2022-07-31 15:18
I'm not on Windows, but perhaps the file I was converting was.  It was a file from SymfonyCast.

So should I run something first before running rector?

**Comment by samsonasik** [comment] 2022-07-31 15:26
I can't reproduce in macOS, so I guess you're on Linux, right?

If the issue is line ending, it probably needs converting first..., this stackoverflow probably can do this https://askubuntu.com/questions/803162/how-to-change-windows-line-ending-to-unix-version

**Comment by TomasVotruba** [comment] 2022-08-17 14:38
I've checked the zip now and there is no `composer.json`. I used Rector 0.13.10 and dev-main and both run well :+1: 
Closing as fixed then.

If the same issue happens, please provide demo link: https://getrector.org/demo, so we can see it directly and work around live code. Thank you :slightly_smiling_face:

**Closed by TomasVotruba** 2022-08-17 14:38 UTC
