### ISSUE TITLE
SymfonySet 4.2 Method getExtendedTypes() was not found in reflection of class Symfony\Component\Form\AbstractTypeExtension

### ISSUE THREAD

**Issue by spras** [rectorphp/rector#6808] opened 2021-11-16 10:16 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | eaf1f250031db227ef2c623c16753a3642bfa2bb             |

With the SymfonySet 4.2, we get this error on basic symfony 4.4 install : 
```
 [ERROR] Could not process "src/Kernel.php" file, due to:
         "Method getExtendedTypes() was not found in reflection of class Symfony\Component\Form\AbstractTypeExtension.".
         On line: 328
```

Weird : if i run rector twice, it's OK on the second run : 

```
➜  symfony_4_0_rector git:(master) vendor/bin/rector process src --dry-run
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [ERROR] Could not process "src/Kernel.php" file, due to:
         "Method getExtendedTypes() was not found in reflection of class Symfony\Component\Form\AbstractTypeExtension.".
         On line: 328


➜  symfony_4_0_rector git:(master) vendor/bin/rector process src --dry-run
    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

 [OK] Rector is done!


```

## Minimal PHP Code Causing Issue

Clone this repo : https://github.com/spras/symfony_4_rector_issue a fresh install of symfony 4.4 
rector is installed with SymfonySet up to 4.2

## Expected Behaviour

` [OK] Rector is done!`  ... on the first run

**Comment by TomasVotruba** [comment] 2021-11-16 11:17
Duplicate of https://github.com/rectorphp/rector-symfony/issues/61

**Closed by TomasVotruba** 2021-11-16 11:17 UTC
Labels: bug
