### ISSUE TITLE
A flag to disable the cache (or changing cache PATH)

### ISSUE THREAD

**Issue by Grafikart** [rectorphp/rector#6933] opened 2022-01-13 10:05 UTC
# Feature Request

The default cache path can cause problem if the user does not meet the right permissions (already encountered for docker for instance #4568). The same problem appears when you use the `sail` command with laravel for instance.

It could be nice to have a flag to completely disable the cache, or at least move the cache somewhere else to avoid any conflict.

**Comment by TomasVotruba** [comment] 2022-01-13 13:07
Hi, this could be definitely useful  :+1:  Would you like to contribute?

**Comment by Grafikart** [comment] 2022-01-13 13:27
I'll try to take a look at it asap

**Comment by Grafikart** [comment] 2022-01-13 18:58
It's more complicated than what I initially thought (the Cache is instantiated before the createFromInput() is called) If you have a clue on how you would approach it I'm interested. At the moment i'm just trying to make cache path configurable.

**Comment by TomasVotruba** [comment] 2022-01-13 19:28
I don't work around cache, mostly static analysis and node mechanics. So I'm unable to navigate more than what you've found. Btw, if you can backup the cache with few tests, it would help us in the future with changes.

**Comment by TomasVotruba** [comment] 2022-02-23 14:45
We're narrowing issues to keep focus on active and engaging contributor to keep project growing.
Closing as I've shrared what I know. If you find a way to improve this, please send PR :+1: 

 Thank you for understanding.

**Closed by TomasVotruba** 2022-02-23 14:45 UTC
Labels: feature

**Comment by maxbethke** [comment] 2022-11-11 08:03
For everyone who stumbles upon this and just wants to disable the cache on a per-run basis, `--clear-cache` is what you are looking for.

**Comment by ernestbuffington** [comment] 2023-01-03 07:34
> Hi, this could be definitely useful 👍 Would you like to contribute?

I think I brought this up already, In a shared hosting environment, there is trouble on the horizon.

It seems that the sys_get_temp_dir() function in PHP 8.x currently has a bug! When it returns the tmp dir in the string it is somehow sending false permission. It can write the cache but cannot delete it in some cases, In other cases, it can do neither and it is only in shared hosting environments, which most of us are using.

I have had to modify and do a manual delete of the dependency injection cache for PHPstan and also had to move my Rector cache dir. I can find no way to move the PHPstan cache so I have to delete it every so often so I do not get errors.

The problem is with the sys_get_temp_dir() function in PHP 8.x - root has no problem... running it as a regular user with or without open_base dir protection on PHP 8 is a problem.

I would normally use Fixkit7 to replace the function but that does not work in PHP 8.x

https://www.php-nuke-titanium.86it.us/modules.php?name=Forums&file=viewtopic&p=293#293
https://stackoverflow.com/questions/13186069/sys-get-temp-dir-in-shared-hosting-environment

**Comment by ernestbuffington** [comment] 2023-01-03 07:36
> For everyone who stumbles upon this and just wants to disable the cache on a per-run basis, `--clear-cache` is what you are looking for.

depends on the depth of refactoring. It's CPU intensive and the issue really needs to be addressed.

**Comment by live627** [comment] 2023-10-31 04:18
> For everyone who stumbles upon this and just wants to disable the cache on a per-run basis, `--clear-cache` is what you are looking for.

This is a great tip for testing custom rules using multiple dry runs where the cache just gets in the way.
