### ISSUE TITLE
Rector requires the intl extension

### ISSUE THREAD

**Issue by fancyweb** [rectorphp/rector#6513] opened 2021-06-17 14:32 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.20             |

Rector commands don't work if the PHP intl extension is not enabled, even if the functions are polyfilled.

Here is the full stack trace:
```output
/app $ vendor/bin/rector init

Fatal error: Uncaught Error: Call to undefined function normalizer_is_normalized() in /app/vendor/rector/rector/vendor/symfony/string/UnicodeString.php:35
Stack trace:
#0 /app/vendor/rector/rector/vendor/symfony/console/Helper/Helper.php(57): RectorPrefix20210613\Symfony\Component\String\UnicodeString->__construct(' ')
#1 /app/vendor/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php(398): RectorPrefix20210613\Symfony\Component\Console\Helper\Helper::width(' ')
#2 /app/vendor/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php(60): RectorPrefix20210613\Symfony\Component\Console\Style\SymfonyStyle->createBlock(Array, 'OK', 'fg=black;bg=gre...', ' ', true, true)
#3 /app/vendor/rector/rector/vendor/symfony/console/Style/SymfonyStyle.php(118): RectorPrefix20210613\Symfony\Component\Console\Style\SymfonyStyle->block(Array, 'OK', 'fg=black;bg=gre...', ' ', true)
#4 /app/vendor/rector/rector/src/Console/Command/InitCommand.php(62): RectorPrefix20210613\Symfony\Component\Console\Style\SymfonyStyle->success('"rector.php" co...')
#5 /app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(254): Rector\Core\Console\Command\InitCommand->execute(Object(RectorPrefix20210613\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210613\Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/rector/rector/vendor/symfony/console/Application.php(825): RectorPrefix20210613\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20210613\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210613\Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/rector/rector/vendor/symfony/console/Application.php(252): RectorPrefix20210613\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\InitCommand), Object(RectorPrefix20210613\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210613\Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20210613\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20210613\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210613\Symfony\Component\Console\Output\ConsoleOutput))
#9 /app/vendor/rector/rector/vendor/symfony/console/Application.php(153): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20210613\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210613\Symfony\Component\Console\Output\ConsoleOutput))
#10 /app/vendor/rector/rector/bin/rector.php(47): RectorPrefix20210613\Symfony\Component\Console\Application->run()
#11 /app/vendor/rector/rector/bin/rector(5): require_once('/app/vendor/rec...')
#12 {main}
  thrown in /app/vendor/rector/rector/vendor/symfony/string/UnicodeString.php on line 35
```

**Comment by TomasVotruba** [comment] 2021-06-17 15:53
Hi, this seems as requirement, not a bug.

What do you suggest?

**Comment by TomasVotruba** [comment] 2021-06-22 19:26
Feel free to improve this. Closing as not a bug, but rather requirement of symfony/console

**Closed by TomasVotruba** 2021-06-22 19:26 UTC
Labels: bug

**Comment by NotionCommotion** [comment] 2021-07-06 04:53
Considering that a polyfill exists in this package (./vendor/rector/rector/vendor/symfony/polyfill-intl-normalizer/bootstrap.php) but doesn't work, seems a little more like a bug than a requirement.  That being said, appreciate your efforts to provide this tool.  Very new to it but looking forward to learning more.
