### ISSUE TITLE
Create PHAR with prefixes to avoid class and package version conflicts

### ISSUE THREAD

**Issue by soullivaneuh** [rectorphp/rector#177] opened 2017-11-29 13:20 UTC
Is a `.phar` build planned for this tool? I would be interested. :-)

**Comment by TomasVotruba** [comment] 2017-11-29 14:04
Why not :)

I like this approach: https://github.com/phpstan/phpstan-shim

**Comment by Soullivaneuh** [comment] 2017-11-29 14:34
Well, as I can have a link for a `wget`, I'm ok. :stuck_out_tongue:

**Comment by TomasVotruba** [comment] 2017-11-29 14:48
Let's do this then :) could you prepare such repository and test it?
We can move the repo here afterwards and generate phar to GitHub pagest

**Comment by Soullivaneuh** [comment] 2017-11-29 15:14
Not sure to get time to learn how to build a .phar now. But if nobody does it, I'll do it one time.

About the .phar story. What is the interest of a `-shim` repository? Why not publish the phar on a website or on the release file instead like php-cs-fixer?

**Comment by TomasVotruba** [comment] 2017-11-29 18:12
I think it's `composer update` approach. Install and forget.

I never update my phar deps

**Comment by TomasVotruba** [comment] 2017-12-25 17:55
Feel free to re-open with PR or reference to demo repository.
Closing now to keep only valid issues open only

**Comment by TomasVotruba** [comment] 2018-01-31 13:55
Reoped due to: https://github.com/rectorphp/rector/issues/302#issuecomment-361648078

**Comment by TomasVotruba** [comment] 2018-02-13 22:51
### Resources

- https://github.com/box-project/box2

**Comment by TomasVotruba** [comment] 2018-02-14 08:07
I'm making this priority, since the bin plugin doesn't work as expected

**Comment by inverse** [comment] 2018-04-17 19:44
Once we have phar support could we add this to phive?

**Comment by TomasVotruba** [comment] 2018-04-24 21:53
Useful source

- https://andreas.heigl.org/2017/01/18/building-a-phar-automated/

**Comment by TomasVotruba** [comment] 2018-04-28 18:34
As discusses, think of prefixing only:

- https://github.com/humbug/php-scoper

**Comment by mssimi** [comment] 2018-04-29 08:43
Tried php-scoper atm I cannot whitelist namespace easily.

https://github.com/humbug/php-scoper/issues/192

**Comment by TomasVotruba** [comment] 2018-04-29 08:53
Consider using it, as it cover 80 % cases.

The rest need to be resolve our way:

- whitelist can be run done with string replace via cli (Rector => Prefix123Rector by php-scoper, back by [`sed` in cli](https://askubuntu.com/a/20416/325651))
- config files prefixing - simple script should handle that

**Comment by TomasVotruba** [comment] 2018-04-29 12:29
See https://github.com/rectorphp/rector/pull/389/files/cadcd379d31270f499d4df774a55b7630ff021f9#diff-197bb7611c620867d2f3cd1c34653e92

**Comment by TomasVotruba** [comment] 2019-11-06 19:58
**Why/how create the compiler?

- it's nicely explained here https://github.com/fprochazka/phpstan-compiler

**Where to start**

- basically create https://github.com/phpstan/phpstan-compiler that was closed-source recently :/
- this is my last attempt: https://github.com/DeprecatedPackages/compiler

**Comment by ondrejmirtes** [comment] 2019-11-06 20:42
phpstan-compiler isn't closed source, it was moved to phpstan/phpstan-src.

**Comment by TomasVotruba** [comment] 2019-11-06 20:49
I've updated the link.

Btw, how can Rector use PHPStan now without requiring whole prefixed phar? I didn't find https://packagist.org/?query=phpstan-src on packagist :/

**Comment by ondrejmirtes** [comment] 2019-11-06 21:02
It should work exactly the same way for you. I encourage you to try to build Rector on top of phpstan/phpstan dev-master.

**Comment by TomasVotruba** [comment] 2019-11-06 21:07
The problem is, most of vendor will be duplicated/prefixed.
To prefix Rector correctly using PHPStan's vendor, we would need to know the prefix string. It's not possible now

**Comment by ondrejmirtes** [comment] 2019-11-06 21:18
I don’t get it. PHPStan itself and nikic/php-parser aren’t prefixed. As PHPStan user (even of internals like types or Scope), you don’t have to care about the generated prefix of for example symfony/console. You’re not supposed to touch it.

**Comment by TomasVotruba** [comment] 2019-11-06 21:35
There is symfony/console in PHPStan - prefixed,
and one in Rector - currently not prefixed.

**Comment by ondrejmirtes** [comment] 2019-11-06 21:53
I don't see the problem in practice.

> That means almost double the load of files in vendor compared to shared dependencies - now.

There's going to be only one PHPStan file (the .phar) in vendor so this statement isn't true.

**Comment by TomasVotruba** [comment] 2019-11-06 21:56
It is, PHPStan (the .phar with prefixed) + Rector's vendor.
The best solution to keep file load same as now would be to have phpstan-src on Packagist, as was phpstan before.

**Comment by ondrejmirtes** [comment] 2019-11-06 21:59
But why? Just try it and see that it works. No one cares about 5 more megabytes to download. It's better longterm like this.

Basically the main reason for the PHAR is that the latest version will be usable by more people, not creating conflicts in Composer. It was discussed here: phpstan/phpstan#2074

**Comment by TomasVotruba** [comment] 2019-11-06 22:04
Thanks for the link. It looked very random with commit and no PR to master.

> Just try it and see that it works. No one cares about 5 more megabytes to download. It's better longterm like this.

I don't mind that much, but not sure about the community. I'll refer people to this if they complain :)

**Comment by TomasVotruba** [comment] 2019-12-01 14:03
The solution is closer than ever before... :)
https://github.com/rectorphp/rector/pull/2373

We got to overcome some Symfony bugs at first, but now it looks good

**Comment by TomasVotruba** [comment] 2019-12-27 12:54
Resolved by https://github.com/rectorphp/rector/pull/2373

Download and test at https://github.com/rectorphp/rector-prefixed

**Closed by TomasVotruba** 2019-12-27 12:54 UTC
Labels: help wanted
