### ISSUE TITLE
Warning message on PHP files consisting of only comments

### ISSUE THREAD

**Issue by fitztrev** [rectorphp/rector#1157] opened 2019-03-07 18:53 UTC
When I run the following command, I get a warning message when it found a PHP file where the contents were only comments.

```
$ ./vendor/bin/rector process app --level laravel58
```

Contents of *`app/Test.php`*:

```php
<?php

// A single-line comment
```

Output:

```
PHP Warning:  assert(): assert($itemStartPos >= 0 && $itemEndPos >= 0) failed in
vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php on line 753
```

Ref nikic/PHP-Parser#589

**Comment by TomasVotruba** [comment] 2019-03-08 15:45
It looks like it's another file. Running it on the `app/Tests.php` with provided contents works ok.

```bash
vendor/bin/rector process app/Test.php --level laravel58
```

**Comment by fitztrev** [comment] 2019-03-08 16:09
It seems the issue is only on PHP 7.2. Just tried on 7.3 and the warning is not there. Thanks!

**Comment by TomasVotruba** [comment] 2019-03-08 18:47
It should work on any PHP. There will be some bug with one of the rules.

If you can provide failing file, we could spare re-creating the issue in the future by someone else on PHP 7.2

**Comment by fitztrev** [comment] 2019-03-08 19:02
@TomasVotruba Ok, see below:

```shell
$ php -v
// PHP 7.2.4
```

## Steps to reproduce

```shell
mkdir rector-issue
cd rector-issue
composer require rector/rector -q

echo "<?php echo 'hello world';"> FileIsOk.php
vendor/bin/rector process FileIsOk.php --level laravel58
// ^^ All good, works as expected

echo "<?php // comment here"> FileIsNotOk.php
vendor/bin/rector process FileIsNotOk.php --level laravel58
// ^^ Issue
```

## Screenshot

<img width="865" alt="screen shot 2019-03-08 at 11 02 08 am" src="https://user-images.githubusercontent.com/271432/54049492-a7626500-41aa-11e9-98f5-810edf8685fb.png">

**Comment by TomasVotruba** [comment] 2019-03-08 19:26
Thank you :+1: 

What rule from `laravel58.yaml` is causing this? Try commenting out all.

(I'm affraid this is not related to any rule. This might be caused by printer.)

**Comment by fitztrev** [comment] 2019-03-08 19:54
Seems to be all of them -- not related to any specific rule.

**Comment by TomasVotruba** [comment] 2019-03-08 19:56
Hm, then it's related to the printer. Any clue why PHP 7.2 vs 7.3 is different?
Do you have installed same version of `php-parser`?

**Comment by fitztrev** [comment] 2019-03-08 20:09
> Any clue why PHP 7.2 vs 7.3 is different?

```php
$itemEndPos = $origArrItem->getEndTokenPos();
```

This is `int(-1)` which is why the assertion fails.

> Do you have installed same version of php-parser?

Yes, same version.

**Comment by TomasVotruba** [comment] 2019-03-08 20:16
On which PHP version this is `-1`?

```php
$itemEndPos = $origArrItem->getEndTokenPos();
```

Is is possible your `assert.<option>` is disabled on PHP 7.3? It seems weird the same number fails.

**Comment by fitztrev** [comment] 2019-03-08 20:44
Ok, that's not it. It's actually `-1` in both environments. Result for both PHP 7.2 and 7.3:

```php
var_dump($itemEndPos); // int(-1)
var_dump($itemStartPos >= 0 && $itemEndPos >= 0); // bool(false)
```

I just looked at the assert options. Here's the difference:

PHP 7.2 - `zend.assertions => 1 => 1`
PHP 7.3 - `zend.assertions => -1 => -1`

I guess that explains it?

**Comment by TomasVotruba** [comment] 2019-03-08 20:53
Yes :+1: 

I think you have assertions silenced on 7.3.

I'll enable assertions and try it locally, thanks for debugging :+1:

**Comment by TomasVotruba** [comment] 2019-03-31 20:09
Closing as failing test is required and unable to replicate

**Closed by TomasVotruba** 2019-03-31 20:09 UTC
