### ISSUE TITLE
Running rector from Docker

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#2186] opened 2019-10-21 13:40 UTC
I've recently changed my setup to run Rector from Docker instead of including it in my composer.json to avoid #1899 . And it feels to me like one of the "migration step" is not currently documented, which is updating the paths in my `rector.yaml` file's `imports` section, like this : 

```diff
 imports:
-    - { resource: 'vendor/rector/rector/config/set/code-quality/code-quality.yaml' }
-    - { resource: 'vendor/rector/rector/config/set/coding-style/coding-style.yaml' }
-    - { resource: 'vendor/rector/rector/config/set/solid/solid.yaml' }
+    - { resource: '/rector/config/set/code-quality/code-quality.yaml' }
+    - { resource: '/rector/config/set/coding-style/coding-style.yaml' }
+    - { resource: '/rector/config/set/solid/solid.yaml' }
... etc ...
```

Or did I "do it wrong" ?

**Comment by JanMikes** [comment] 2019-10-21 13:59
Hi @gnutix please to help me better understand your situation, could you paste exact command you are trying to run?

**Comment by gnutix** [comment] 2019-10-21 15:01
So I've changed from running Rector using this command : 

```
vendor/bin/rector --ansi process src/ tests/
```

to this one : 

```
docker run -v $(pwd):/project rector/rector:0.5.17 process /project/src /project/tests --config /project/rector.yaml --autoload-file /project/vendor/autoload.php
```

Which required, in order to work, to change my `rector.yaml` as described above. And I've seen no such changes explained in the documentation anywhere, so I'm wondering if the project is simply missing some documentation or if that change is "unexpected" and shouldn't be necessary ? (and therefore it might be caused by a bug)

**Comment by JanMikes** [comment] 2019-10-23 12:15
I am looking into that. 

Expected and desired behaviour is definitely to work with Rector in docker in same way, without need of changing paths in your config.

**Comment by JanMikes** [comment] 2019-10-23 12:17
Anyways i have an idea - did your "migration" to docker include uninstalling rector from your composer dependencies? That would lead into `vendor/rector/rector/config/set/code-quality/code-quality.yaml` file not existing in your application anymore, therefore i would understand why you had to make such change.

**Comment by gnutix** [comment] 2019-10-23 18:44
Indeed. Removing `vendor/rector/rector` was the point, as I wanted to get rid of the `multiple definition exists for class %s` phpstorm inspection caused by the stubs classes.

**Comment by JanMikes** [comment] 2019-10-25 12:35
@TomasVotruba i would like your opinion here.

This is caused by file `vendor/rector/rector/config/set/code-quality/code-quality.yaml` obviously no longer exists, when `rector/rector` removed from dependencies.

We can either:
1) Add info into readme to docker chapter that this change might be required
2) Add some env var to docker, etc `RECTOR_SOURCE_DIR`, then in `TolerantRectorYamlFileLoader` override `parseImports`, check via `getenv('RECTOR_SOURCE_DIR')` and if it exists, then replace `vendor/rector/rector` with that value. This is kind of magic but would solve this issue (at this moment i can not come with another usage than this very specific use case)
3) Just close this issue as it is solved and not relevant to rector/docker

Thank you in advance for your feedback

**Comment by TomasVotruba** [comment] 2019-10-25 12:44
I don't understand the issue. How other container PHP apps require their configs?

**Comment by JanMikes** [comment] 2019-10-25 12:50
Okay, i will try to explain again and more verbose 😄 

This is not related to Docker at all.

Composer.json:
```json
"require-dev": {
        "rector/rector": "dev-master"
    },
```
Now `vendor/rector/rector/config/set/code-quality/code-quality.yaml` exists so you can use it in import.

Then `rector/rector` dependency is removed from composer.json and `vendor/rector/rector/config/set/code-quality/code-quality.yaml` no longer exists.

But, if you run rector from docker, this file is available at `/rector/config/set/code-quality/code-quality.yaml` and therefore you can import it in your config.

I proposed 3 solutions. Can we pick one or come with another?

**Comment by gnutix** [comment] 2019-10-25 13:59
Would there be a way to allow relative paths from the `rector/config` folder ? Or using a parameter like `%rector.config%` ?

**Comment by TomasVotruba** [comment] 2019-10-25 14:19
Where is this in our code?

```
- { resource: 'vendor/rector/rector/config/set/code-quality/code-quality.yaml' }
```

The path should be indeed relative

**Comment by gnutix** [comment] 2019-10-25 14:21
> The path should be indeed relative

Yeah, but it's relative to the position of the `rector.yaml` file, which changes depending if you're running it "standard" or within the Docker container (as the Rector source code is not mounted in `vendor/rector`).

**Comment by TomasVotruba** [comment] 2019-10-25 14:24
Of course, that's expected

**Comment by TomasVotruba** [comment] 2019-10-25 14:24
How does PHPStan approach this?

**Comment by JanMikes** [comment] 2019-10-28 13:37
> How does PHPStan approach this?

I tested it and PHPStan has `%rootDir%` variable which resolves into directory where phpstan is installed. It is very close to what @gnutix proposed.

**Comment by TomasVotruba** [comment] 2019-10-28 14:36
I'm open to PR for the variable then

**Comment by TomasVotruba** [comment] 2019-10-30 11:27
This might help: https://github.com/rectorphp/rector/pull/2221 :)

**Comment by gnutix** [comment] 2019-11-01 15:47
I've tried using this new syntax, but now I get this error : 

```bash
$ docker run -v $(pwd):/project rector/rector:latest process /project/src /project/tests --config /project/rector.yaml --autoload-file /project/vendor/autoload.php --ansi --dry-run

Fatal error: Uncaught Nette\FileNotFoundException: File '/rector/vendor/symplify/phpstan-extensions/config/config.neon' is missing or is not readable. in /rector/vendor/nette/di/src/DI/Config/Loader.php:43
Stack trace:
#0 /rector/vendor/nette/di/src/DI/Config/Loader.php(60): Nette\DI\Config\Loader->load('/rector/vendor/...', false)
#1 /rector/vendor/nette/di/src/DI/Compiler.php(127): Nette\DI\Config\Loader->load('/rector/phpstan...', false)
#2 /rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(258): Nette\DI\Compiler->loadConfig('/rector/phpstan...', Object(Nette\DI\Config\Loader))
#3 /rector/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#4 /rector/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate('Container_48b06...', Array)
#5 /rector/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_48b06...', Array)
#6 /rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(2 in /rector/vendor/nette/di/src/DI/Config/Loader.php on line 43
```

**Comment by TomasVotruba** [comment] 2019-11-01 16:12
Always try the lastest version, if not `dev-master`. We develop rather quickly now :)

It works pretty goo, just Fatal error is cause by issues related to: #177

**Comment by gnutix** [comment] 2019-11-05 16:56
I can only chose `rector/rector:latest` when running rector through Docker, right ?

Still gives me the `Fatal error: Uncaught Nette\FileNotFoundException: File '/rector/vendor/symplify/phpstan-extensions/config/config.neon' is missing` exception, so I can't use it via Docker...

**Comment by gnutix** [comment] 2019-11-06 11:38
I was missing `docker pull rector/rector:latest` ! I thought Docker updated the image if I used `:latest`.

**Comment by TomasVotruba** [comment] 2019-11-06 12:16
I have no idea how Docker works here. I don't use it with Rector

Until #177 is solved, you'll keep getting this error.
Please do not re-open issue anymore, as it's duplicated to #177

**Closed by TomasVotruba** 2019-11-06 12:16 UTC

**Comment by gnutix** [comment] 2019-11-06 17:42
It seems to be more a duplicate of https://github.com/rectorphp/rector/issues/2178

**Comment by TomasVotruba** [comment] 2019-11-06 18:57
Yes, there were many similar errors - just check "Fatal error" in Rector issues. But it has one common point of origin.

Here is the problem that happens:
https://3v4l.org/VT3kf

**Comment by gnutix** [comment] 2019-11-06 19:12
Indeed, my code is using `ocramius/hydrated-generator`, which depends on `nikic/php-parser`, and as we're running on PHP 7.2, it's restricted to a lower version which clashes with the latest included in Rector's vendors.

So I understand that Docker is not really concerned here ; wherever I would be running Rector, I'll run into this conflict. Looking at #117 however, it's not really clear to me what's the path you'd like to take to fix this (if it's fixable ?). Would you mind to elaborate on your ideas ? I might be able to give it a shot, as it would benefit the new project I'm working on to be able to run Rector.

**Comment by TomasVotruba** [comment] 2019-11-06 19:55
Let's continue in #177

**Comment by TomasVotruba** [comment] 2019-12-23 17:53
See https://github.com/rectorphp/rector-prefixed
