### ISSUE TITLE
Rector 0.11.34 Fatal error on `rector process src --dry-run`

### ISSUE THREAD

**Issue by simplegr** [rectorphp/rector#6552] opened 2021-07-05 07:55 UTC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.34           |

On a Symfony 4.4 project when executing `rector process src --dry-run` I 'm getting a Fatal Error:

`PHP Fatal error:  Declaration of RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory::withSingularRules(?RectorPrefix20210704\Doctrine\Inflector\Rules\Ruleset $singularRules, bool $reset = false): RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory must be compatible with RectorPrefix20210704\Doctrine\Inflector\LanguageInflectorFactory::withSingularRules($singularRules, bool $reset = false)`

**Comment by samsonasik** [comment] 2021-07-05 07:59
You can temporary pin the exact version "rector/rector": "0.11.32" in composer.json

**Comment by TomasVotruba** [comment] 2021-07-05 09:37
Duplicate of https://github.com/rectorphp/rector/issues/6543

**Closed by TomasVotruba** 2021-07-05 09:37 UTC
Labels: bug

**Comment by muxx** [comment] 2021-07-05 10:41
It seems that #6543 is not the same

**Comment by TomasVotruba** [comment] 2021-07-05 11:28
It's a different method but same issue. The downgrade rule for `DowngradeParameterTypeWideningRector` was changed from all files to reflection approach, and it causes there bugs.

Basically when child / parent class have different method signatues, this now breaks:

```php
interface SymfonyInterface
{
    public function ask(string $message);
}

class SymfonyStyle implements SymfonyStyle
{
    public function ask($message);
}
```

This example is from broken case in Symfony. 

The ideal way to fix this looks like this: https://github.com/symfony/symfony/pull/41987
